recommendations/__init__.py, routes/bookings.py, routes/offers.py, routes/user_mediations.py, utils/includes.py
=> added bookings get

models/user.py, routes/users.py, scripts/init.py
@arnoo 
Ca aide d'avoir un dateCreated pour reperer les user storés localement et qui sont deprecated en DEV
(parce qu'on a fait un db reset all et ensuite un pc init)
=> add dateCreated for User

requirements.txt, routes/users.py, tests/16_routes_users.py
Pensez à mettre à jour votre repo pass-culture-private, il contient la clé d'API
=> Check emails in Google spreadsheet on signup

models/has_thumb_mixin.py, models/mediation.py
=> Resize thumbs before saving when they are too big

models/booking.py, models/event_occurence.py, models/offer.py, routes/bookings.py, tests/17_routes_bookings.py
Au passage de la revue, si vous comprenez sans y passer trop de temps pourquoi le test ne veut bien fonctionner que lorsqu'il est lancé seul...
=> Booking limit

datascience/__init__.py, datascience/offers.py, routes/recommendations.py, utils/compose.py
=> passing geoloc

utils/includes.py
pour le fix https://github.com/betagouv/pass-culture-browser/pull/298
@arnoo
=> fixed includes for mediated occurences

routes/recommendations.py, routes/venues.py, tests/12_routes_recommendations.py, utils/rest.py
et ça va avec 
https://github.com/betagouv/pass-culture-browser/pull/295
=> added recommendations patch route

scripts/interact.py, utils/context.py
=> added small utils api to change password

models/offerer.py, models/pc_object.py, routes/occasions.py, routes/search.py, utils/search.py
La recherche marche de maniere minimale pour
- Offerer dans OfferersPage
- Event + Thing dans OffersPage
=> fixed search api

models/user.py, routes/providers.py, routes/venue_providers.py, utils/rest.py
=> fixed deletion with rights and return of humanized deleted id

local_providers/openagenda_events.py, local_providers/spreadsheet_exp_offers.py, local_providers/titelive_offers.py, models/__init__.py, models/occasion.py, models/user.py, routes/events.py, routes/occasions.py, routes/things.py, tests/10_local_providers.py, tests/21_routes_occasions.py, utils/includes.py, utils/rest.py
Reste un petit souci au niveau des droits (j'ai l'impression que n'importe qui peut demander n'importe quelle venue), je verrai ça lundi.
=> New occasions model and route

app.py, models/__init__.py, runtime.txt
Update some Flask configuration to meet Scalingo requirements
=> Deploy to Scalingo

routes/users.py, utils/context.py, utils/mailing.py
from https://github.com/betagouv/pass-culture-browser/issues/367
=> added mailjet subscribe at signup time

models/booking.py, tests/02_utils_mailing.py, utils/mailing.py, utils/test_utils.py
Texte du mail à valider.
Je n'ai pas réussi à produire l'e-mail qui est généré dans "if len(offer.bookings) > 0" car je ne comprend pas le format d'offer.bookings (j'ai fait une liste de bookings vide, ne marche pas)
=> Place and structure in booking email

conftest.py, routes/bookings.py, tests/02_utils_mailing.py, utils/mailing.py, utils/test_utils.py
On a ouvert une nouvelle branche pour faire un rebase de place_and_structure_for_user_email https://github.com/betagouv/pass-culture-api/pull/86
=> Rebasing email

app.py, conftest.py, tests/02_utils_mailing.py, utils/mailing.py, utils/test_utils.py
Enlevé les appels à app dans utils/mailing.py, mis dans app.py et conftest.py
Mis le mock pour l'envoi du mail dans conftest.
Enlevé les appels d'app inutile dans tests/02_utils_mailing.py et dans utils/tests_utils.
=> removing app dependences

routes/users.py
c'ets plus facile comme ca pour sagas cote frontend de detecter l'action
SUCCESS_DATA_POST_USERS/SIGNUP
=> changed route for users signup

models/pc_object.py, routes/error_handlers.py, routes/users.py, utils/errors.py
Comme ca la routes users.py renvoie bien maintenant une api errors avec le message comme quoi on peut pas ajouter un email qui existe deja dans la db
=> catched errors in addOrAbortIfErrors

models/event_occurrence.py, models/mediation.py, routes/event_occurrences.py, routes/users.py, utils/includes.py
Pour faire marcher le pro avec le nouveau nommage
https://github.com/betagouv/pass-culture-pro/pull/86
=> fixed routes for pro

app.py, local_providers/__init__.py, local_providers/install.py, local_providers/openagenda_events.py, local_providers/openagenda_stocks.py, local_providers/spreadsheet_exp_stocks.py, local_providers/spreadsheet_exp_thing_stocks.py, local_providers/spreadsheet_exp_venues.py, local_providers/spreadsheet_stocks.py, local_providers/titelive_stocks.py, local_providers/titelive_thing_descriptions.py, local_providers/titelive_thing_thumbs.py, local_providers/titelive_things.py, local_providers/titelive_venues.py, models/install.py, routes/export.py, routes/providers.py, routes/storage.py, routes/validate.py, scripts/__init__.py, scripts/interact.py, scripts/pc.py, scripts/request.py, scripts/testcafe.py, scripts/update_providables.py, tests/10_local_providers_test.py, tests/19_routes_venue_providers_test.py, tests/conftest.py, utils/printer.py
Ca me gênait pour me faire un ptit script pc testcafe qui me permet d'avoir le provider open agenda, deja là disponible, pour les tests testcafe
=> did import fo local providers like models

routes/__init__.py, routes/health_check.py, utils/health_checker.py
Je ne suis pas certains du besoin de faire une requête en DB pour valider le fonctionnement puisqu'il me semble que si la DB n'est plus accessible Flask s'effondre
=> Healthcheck

models/needs_validation_mixin.py, models/user.py, tests/models_users_test.py, utils/rest.py, utils/test_utils.py
=> 476 check current user rights

domain/build_recommendations.py, models/offer.py, recommendations_engine/__init__.py, recommendations_engine/recommendations.py, repository/booking_queries.py, repository/recommendation_queries.py, routes/recommendations.py, tests/12_routes_recommendations_test.py, tests/domain_build_recommendations_test.py, tests/models_offer_test.py, utils/test_utils.py
- simplification de la route PUT recommendations on faisant de l'extraction de fontions, notamment des fonctions de queries
- ajout d'une proprieté dateRange = [start, end] sur le modèle Offer (dateRange = None si l'offer porte sur une thing)
=> 485 date range in recommendation

alembic/versions/10ea71b5a60b_add_is_soft_deleted_to_stock.py, models/offer.py, models/pc_object.py, models/soft_deletable_mixin.py, models/stock.py, repository/booking_queries.py, repository/offer_queries.py, repository/recommendation_queries.py, repository/stock_queries.py, routes/bookings.py, routes/error_handlers.py, routes/stocks.py, scripts/send_final_booking_recaps.py, tests/12_routes_recommendations_test.py, tests/models_event_occurrence_test.py, tests/models_stock_test.py, tests/repository_booking_queries_test.py, tests/repository_recommendation_queries_test.py, tests/routes_stocks_test.py, tests/utils_rest_handle_rest_get_list_test.py, utils/includes.py, utils/rest.py, utils/sandbox.py, utils/test_utils.py, validation/bookings.py
Les stocks deviennent soft deletable.
- Création d'un softDeletableMixin
- Répercutions sur diverses routes / méthodes PcObject, etc (cf https://github.com/betagouv/pass-culture-browser/issues/483 pour plus de détails)
=> 483 soft deleting stocks

alembic/versions/43a686a11027_added_is_from_search_in_recommendation.py, models/recommendation.py, recommendations_engine/__init__.py, recommendations_engine/offers.py, recommendations_engine/recommendations.py, routes/recommendations.py, tests/12_routes_recommendations_test.py, tests/19_routes_venue_providers_test.py
@annemarie35 ca peut deja servir maintenant
from https://github.com/betagouv/pass-culture-browser/issues/501
Pour le moment on part sur:
une route qui cherche parmi les offers (join event, thing, venue)
qui ensuite regarde pour chaque offer trouvee si il n'y a pas deja une recommendation pour ca
sinon elle cree une recommendation avec un tag special recommendation.isSearch = True
=> 501 added recommendations search route

scalingo/backup_prod.sh, scalingo/restore_backup.sh
Used in a cron on OVH instance
=> Script backup prod ovh

routes/users.py
Sinon on perd les expenses quand on utilise la route PATCH users/current dans le formulaire des profile page.
=> added expenses for PATCH user routes

routes/bookings.py, tests/routes_bookings_test.py
petite correction sur le retour d'API dans le get bookings/token/<token>
=> sends humanized bookingId instead of raw

routes/offerers.py
Car c'est trop relou en admin, sur le pro, de telecharger les 750 structures
de https://github.com/betagouv/pass-culture-pro/pull/126
=> paginate offerers

models/event.py, models/thing.py
Voir sur la maquette Invision pour la relation entre le label et le sublabel
=> add sublabels to events and things types

Procfile, scripts/clock.py
Backup TARGET_DATABASE
Restore dump to  DATABASE_URL
=> Restore data from prod

alembic/versions/271d090148dc_add_information_to_user.py, mock/scripts/users.py, models/user.py, tests/domain_internal_emails_test.py, tests/domain_user_emails_test.py, tests/models_deposits_test.py, tests/models_users_test.py, tests/repository_user_queries_test.py, tests/routes_bookings_test.py, tests/routes_event_occurrences_test.py, tests/routes_export_test.py, tests/routes_offerers_test.py, tests/routes_stocks_test.py, tests/routes_users_test.py, tests/routes_validate_test.py, tests/utils_mailing_test.py, utils/test_utils.py
J'hésite à changer aussi la route booking/token pour renvoyer nom prénom tout de suite. Le seul soucis c'est que pour l'instant ce n'est pas renseigné...
=> added extra data to user

repository/booking_queries.py, repository/offer_queries.py, repository/offerer_queries.py, repository/user_offerer_queries.py, repository/venue_queries.py, routes/error_handlers.py, routes/offerers.py, routes/offers.py, tests/repository_offerer_queries_test.py, tests/routes_offerers_test.py, tests/routes_offers_test.py, validation/errors.py, validation/offers.py
Je n'ai pas touché à la requête de find_offerers_with_user_venues_and_bookings_by_departement parce qu'elle n'est utilisée que sur une route export qui n'est pas encore validée.
=> 640 user offerer joins filtered

scalingo/README.md
Merci @DanielBaudry!!!! Je sens la puissance de scalingo dans mes mains.
=> added doc for rebooting a scalingo container

models/pc_object.py
=> removed dehumanized ids in as dict

routes/venues.py, tests/routes_venues_test.py, validation/venues.py
check json on venue patch route to forbid changing managing offerer
=> Route venues. Patching managing offerer id forbidden.

routes/bookings.py, tests/19_routes_venue_providers_test.py, tests/routes_bookings_test.py, utils/includes.py
pour que le frontend puisse bien s'updater à la modiffication booking.isCancelled = True to False.
=> used PATCH instead of DELETE to cancel booking

domain/__init__.py, domain/types.py, mock/scripts/chunks/things.py, recommendations_engine/recommendations.py, repository/offer_queries.py, routes/recommendations.py, scripts/interact.py, tests/domain_types_test.py, tests/repository_offer_queries_test.py
Comme on a changé les types maintenant en mode 'EventType.MACHIN', ben faut readapter.
=> fixed search by categorie/type

tests/validation_headers_test.py, validation/headers.py
Ou sur integration ?
Moi je veux faire un 
export API_URL = <testing ou integration backend> && yarn start pour pouvoir developper le front avec de la donnee des db prods.
=> added localhost also in testing

alembic/versions/4e18b6798915_add_iban_and_bic_to_venue.py, domain/payments.py, models/has_bank_information_mixin.py, models/offerer.py, models/venue.py, tests/domain_payments_test.py, tests/models_venue_test.py, utils/test_utils.py
made offerer and venue versioned, created has_bank_information_mixin, made Offer and Venue inherit from that mixin and adapted payment recipient depending on having the IBAN on venue or offerer
=> Adapting Venue and Offerer for payments

routes/users.py, tests/routes_users_test.py
Je n'ai pas trouvé les TU sur `user/signin` de `routes_users_test`
=> Fixes #797 - 🍕 ajout des expenses au signin de l'user

models/offer.py, models/pc_object.py, tests/models_offer_test.py, tests/models_pc_object_test.py, utils/date.py
Renvoie une liste de deux dates en format ISO 8601
=> 799 datetime format

routes/mediations.py, tests/utils_thumb.py, utils/thumb.py
C'est pour aider les biz dev à remplir les offred de demo via le backoffice testing:) Merci!
=> [URGENT] added more explicit error when thumb has wrong format

tests/routes_bookings_test.py
wrote tests to check that get and patch routes on /bookings/token/<token> work with encoded urls and not if not encoded
=> Ajout de tests pour être sûrs qu'on traite bien les url encodées

local_providers/titelive_things.py, scripts/update_providables.py
Import books from titelive from their FTP.
A priori pas d'impact de merger cela maintenant (sans avoir l'import initial de base de données) puisque l'appel à titetilve things est manuelle.
On est d'accord ? :)
=> Titelive ftp

templates/mails/venue_validation_email.html, tests/utils_mailing_test.py, tests/validation_headers_test.py, validation/headers.py
corrected problems with validation link : header restrictions removed and link corrected
=> 814 Correction d'erreurs dans le mail de validation

models/pc_object.py, repository/offerer_queries.py, routes/error_handlers.py, routes/export.py, tests/repository_offerer_queries_test.py, tests/routes_export_test.py, utils/includes.py, validation/exports.py, validation/headers.py
for pc team, creating a first export routes on pending validations, error when user is not logged or not admin and tests.
=> 940 responses for admin users

.circleci/config.yml
=> Correct typo in ci conf

routes/users.py
- ce n'est testable qu'en intégration (ça dépend d'une variable d'environnement)
- j'ai testé ça manuellement en local en changeant la variable
- on ne peut donc pas écrire de test automatisé là dessus
- ça partira dans une version v5.1.0
=> Set the new user department code to '00' if env is integration

domain/types.py, models/event.py, models/pc_object.py, models/thing.py, routes/offers.py, tests/models_event_test.py, tests/models_pc_object_test.py, tests/models_thing_test.py, tests/routes_events_test.py, tests/routes_offerers_test.py, tests/routes_offers_test.py, utils/includes.py
API returns enum value instead of str(enum) for ThingType and EventType in route offers
=> (PC-1089) correct event and thing types on offers route

domain/types.py, models/event.py, models/offer_type.py, models/thing.py, tests/models_event_test.py, tests/models_thing_test.py, tests/routes_events_test.py, tests/routes_offerers_test.py, tests/routes_offers_test.py, utils/includes.py
- Modifié offerType pour qu'elle renvoie None quand la valeur présente dans la base SQL ne correspond pas au str d'une valeur d'énum
- Modifié PRO_BOOKING_INCLUDES pour renvoyer les informations sur les offerType pour la compta
=> 1089 bug fix

tests/routes_export_test.py, utils/includes.py
2 fichiers modifiés, 
includes 
enlever des éléments de l'include pending validation
et tests/routes_export_test.py
-tester complétemetn la route
- 2 imports
- renommer les tests pending_validation
=> pc-1133 modifying includes for pending_val and adding a test

repository/booking_queries.py, tests/routes_bookings_test.py, validation/bookings.py
Pour le utilisateurs pro ou au solde insuffisant.
=> (PC-26) Changement des messages d'erreur lors de la réservation

models/db.py, models/install.py, tests/repository_offerer_queries_test.py, tests/repository_stock_queries_test.py, tests/repository_venue_queries_test.py
au deuxieme commit... mon pep a du changer pas mal de lignes pour des raisons de sautage de lignes... Mais en gros, y a ue deux tests un peu à la con de rajouter à la fin des deux fichiers de test.
=> 1305 activity localhost

domain/keywords.py, tests/domain_keywords_test.py, tests/routes_recommendations_get_test.py, utils/nltk_downloader.py
il faut juste regarder le dernier commit (382cf1c) qui fix le probleme de chercher avec des stopwords
(tout le reste est de 1364 qui sera squashé et mergé en un seul commit)
=> [AFTER PC-1364 (doit être dedans ou pas)] Keywords fix with removing stop words

routes/event_occurrences.py, routes/stocks.py, routes/users.py, tests/10_local_providers_test.py, tests/19_routes_venue_providers_test.py, utils/mailing.py, utils/test_utils.py
Je n'arrive pas à lancer les tests cafe pro pour valider le code :( si un reviewer peu le faire je serai très reconnaissant ! :)
=> [PC-1284] Test mailjet response before extract data

repository/offerer_queries.py, routes/export.py, tests/repository_offerer_queries_test.py, tests/routes_export_test.py, utils/includes.py
https://passculture.atlassian.net/browse/PC-1212
modifier, pending validation pour ajouter les venue devant être validées :
- modification de l'includes
- petite modif de l'offerer queries
- ajout des tests pour coller aux nouveaux cas : 
ça en fait 16, leur logiques est écrite dans le ticket jira, je suis pas hyper content de leur nom (si vous avez des idées je suis preneur)
"test_pending_validation_return_requested_token_case_1()"
=> Pc 1212 pendings validation

domain/keywords.py, repository/keywords_queries.py, repository/offer_queries.py, tests/repository_keywords_queries.py
get_keywords_analyser va etre pratique pour comprendre pk un objet est selectionné par la recherche par mot-clés
Exemple d'utilisation:
```
from model import Offer
from repository.keywords_queries import get_keywords_analyser
my_offer_to_be_analyzed = Offer.query.first()
print_keywords_analyzer(my_offer_to_be_analyzed, 'activa')
```
ca affiche 
```
{
"Event_description": "Venez \u00e0 ce rendez-vous pour activer l'argent de votre pass.",
"Event_name": "Activation de votre Pass Culture",
"Offerer_name": false,
"Thing_name": false,
"Thing_description": false,
"Venue_name": false
}
```
=> (pc-1333) added a keywords analyser

routes/events.py, routes/offers.py, routes/things.py, templates/mails/offer_creation_notification_email.html, tests/domain_user_activation_test.py, tests/utils_mailing_test.py, utils/config.py
send email in thing and event route instead of offer and made the lin…k clickable on dev environment
=> (PC-1400) correctif suite à revue PO

tests/routes/recommendations_get_test.py
Finalement, pas de bug, le cas de test soulevé dans la story ne contenait que des stop words. J'ai ré-ordonné les tests et ajouté un test qui prouve que la recherche avec apostrophe fonctionne.
=> Pc 1439 search with quote

routes/bookings.py, tests/routes/bookings_test.py, utils/test_utils.py, validation/bookings.py
Sur le POST d'un nouveau booking :
- ajout d'une fonction qui valide si la date de début d'évènement n'est pas périmée pour un event
(la fonction qui teste la date limite de réservation existe déjà)
- ajout de tests sur une thing sans date limite de réservation
- ajout de tests sur une thing avec date limite de réservation
=> Pc 1394 can book outdated offer

tests/utils_mailing_test.py, utils/mailing.py
Je n'ai pas testé sur la webapp et pro.
=> Pc 1505 fix error 500 on booking patch

repository/stock_queries.py, tests/conftest.py, tests/routes/stocks_id_test.py, tests/routes/stocks_test.py, utils/test_utils.py
- refacto des tests de routes pour le stock
=> PC-1497 refactoring test file with new standards

sandboxes/scripts/creators/industrial/create_industrial_bookings.py, sandboxes/scripts/creators/industrial/create_industrial_event_stocks.py, sandboxes/scripts/creators/industrial/create_industrial_thing_stocks.py, sandboxes/scripts/getters/__init__.py, sandboxes/scripts/getters/webapp_04_verso.py, tests/test_utils.py
- ajout du param 'booking_amount' à test_utils::create_booking
- les users 'has-no-more-money' detiennent un seul booking de 500
- dans create_industrial_bookings ne cree que ce seul booking en mettant les users HNMM dans une liste
=> (PC-1448) udpate industrial sandbox

sandboxes/scripts/getters/__init__.py, sandboxes/scripts/getters/webapp_08_booking.py
ajout de getters sur les users pour booking et verso
=> (PC-1448) update des helpers des users sandbox industrial

tests/repository_booking_queries_test.py
Je n'ai pas réussi à reproduire le bug, mais j'ai deux nouveaux tests
=> (PC-1630) added tests

sandboxes/scripts/getters/webapp_08_booking.py
Ajout des helpers pour les différents types d'offres, thing, digital, event
=> (PC-1448) update du sandbox helper pour booking

utils/includes.py
- affiche les bookings pour une offre
=> (PC-1537) include bookings in offers

routes/users.py, tests/routes/users_test.py
=> (PC-1545): Creating a new route /users/tokens/:tokenid:

models/booking.py, models/pc_object.py, models/stock.py, repository/booking_queries.py, repository/stock_queries.py, routes/bookings.py, routes/stocks.py, tests/models_stock_test.py, tests/repository_booking_queries_test.py
Car on avait avant une integrity error pas catchée avec l'api quand on pousse une beginningdatetime egale à enddatetime
=> (PC-1707) added api errors for stock model

alembic/versions/d76f83432485_venue_can_have_comment_and_siret.py, models/venue.py, tests/models/venue_test.py
https://passculture.atlassian.net/secure/RapidBoard.jspa?rapidView=2&modal=detail&selectedIssue=PC-1762
=> Pc 1762 change constraint on venue

repository/booking_queries.py, tests/utils_rest_handle_rest_get_list_test.py, tests/utils_rest_test.py, tests/validation_export_test.py, utils/rest.py
C'est du temporaire, en attendant la mise à jour de SQLAlchemy.
=> [PC-1788] Sanitize Order By statements coming from user inputs

models/stock.py, routes/stocks.py, tests/models/stock_test.py, tests/routes/stocks_test.py, tests/test_utils.py
https://passculture.atlassian.net/secure/RapidBoard.jspa?rapidView=2&projectKey=PC&modal=detail&selectedIssue=PC-1584
=> Pc 1584 booking limit datetime validation when patch stock thing

domain/admin_emails.py, domain/user_emails.py, routes/offers.py, tests/domain/admin_emails_test.py, tests/domain/user_emails_test.py, utils/mailing.py
3 new variables must be added in your configuration (zsh or bashrc)
- SUPPORT_EMAIL_ADDRESS
- ADMINISTRATION_EMAIL_ADDRESS
- DEV_EMAIL_ADDRESS
=> (PC-1893): change email

routes/signup.py
Je ne peux pas tester parce que je ne peux pas mocker mailjet dans les routes
=> (PC-2010) catch MailServiceException in signup webapp

domain/expenses.py, tests/domain/expenses_test.py
Le test ajouté est bien rouge avant modification du code ;-)
=> [PC-2075] Expenses on music instruments should be capped

sandboxes/scripts/utils/helpers.py
il manquait le validationToken utilisé par le Pro dans un testcafe sur le signup
=> (PC-1890) remove include and add properties needed

alembic/versions/926f236ee66f_unique_user_offerer.py, models/pc_object.py, models/user_offerer.py, repository/user_offerer_queries.py, routes/offerers.py, routes/validate.py, tests/models/user_offerer_test.py, tests/repository/offerer_queries_test.py, tests/repository/user_offerer_queries_test.py, tests/repository/venue_queries_test.py, tests/routes/export_test.py, tests/routes/post_offerer_test.py
aussi sur pro, 
cf :
https://passculture.atlassian.net/secure/RapidBoard.jspa?rapidView=8&modal=detail&selectedIssue=PC-1841
=> Pc 1841 just create user offerer when offerer

sandboxes/scripts/creators/industrial/create_industrial_admin_users.py, sandboxes/scripts/creators/industrial/create_industrial_offerers_with_pro_users.py, sandboxes/scripts/creators/industrial/create_industrial_pro_users.py, sandboxes/scripts/creators/industrial/create_industrial_webapp_users.py, sandboxes/scripts/testcafe_helpers.py, sandboxes/scripts/utils/helpers.py, tests/sandboxes/industrial_test.py
On gagne 35 secondes sur l'exécution des tests du backend en utilisant un mot de passe par défaut dans la sandbox
=> Pc 2082 faster tests

local_providers/titelive_thing_thumbs.py, models/has_thumb_mixin.py, models/local_provider.py, tests/local_providers/local_provider_titelive_test.py, tests/local_providers/local_provider_titelive_thumbs_test.py
J'ai retiré les fichiers "vignettes" des images traitées par le provider
=> (PC-2096) TiteLive thing thumbs - synchronisation journalière

.circleci/config.yml
This reverts commit 6838046159543a7c9a945d83f0586ef462417dcc.
=> Revert "(pC-2139) remove coveralls on CI config"

models/api_errors.py, recommendations_engine/__init__.py, recommendations_engine/recommendations.py, repository/booking_queries.py, repository/feature_queries.py, repository/mediation_queries.py, repository/offer_queries.py, routes/error_handlers.py, routes/offers.py, routes/recommendations.py, routes/stocks.py, routes/validate.py, sandboxes/scripts/getters/webapp_08_booking.py, tests/repository/booking_queries_test.py, tests/repository/feature_queries_test.py, tests/repository/offer_queries_test.py, tests/routes/get_recommendations_by_offer_test.py, tests/routes/put_recommendations_test.py, validation/offers.py, validation/validate.py
Sur la base d'un profiling de PUT /recommendations, les commits de cette PR font passer l'appel d'environ 40s à environ 2s.
=> [PC-2281] recommendations route performance

domain/favorites.py, domain/payments.py, domain/user_emails.py, repository/CONTRIBUTING.md, repository/booking_queries.py, repository/reimbursement_queries.py, routes/bookings.py, routes/recommendations.py, scripts/beneficiary/file_import.py, scripts/dashboard/diversification_statistics.py, scripts/dashboard/users_statistics.py, scripts/fill_date_used_for_bookings.py, scripts/payment/batch_steps.py, scripts/update_booking_used.py, tests/repository/booking_queries_test.py, tests/routes/get_bookings_test.py, tests/utils/mailing_test.py, utils/includes.py, utils/mailing.py
- La route bookings sort que des bookings valides (c'est-à-dire que l'on ne renvoit plus les bookings qui auraient été annulés puis re-réservés) triés par date d'event décroissante
- BSR sur bookings-queries
=> (PC-640) bookings route returns valid bookings

models/offer.py, tests/models/offer_test.py, tests/routes/get_bookings_test.py, tests/routes/get_recommendations_test.py, utils/includes.py
=> (pC-2431) isFinished -> isNotBookable

scripts/clean_activity.py, tests/scripts/clean_activity_test.py
https://github.com/betagouv/pass-culture-api/pulls
=> (PC-2729): modified logic to update dateCreated from stock

routes/offers.py, utils/includes.py
Fonctionnel :
- J'ai ajouté offerType dans OFFER_INCLUDES
Refacto :
- routes/offers
=> (pC-2854) add offerType to OFFER_INCLUDES

connectors/thumb_storage.py, routes/mediations.py, routes/storage.py, sandboxes/scripts/creators/industrial/__init__.py, sandboxes/scripts/creators/industrial/create_industrial_activation_offers.py, sandboxes/scripts/creators/industrial/create_industrial_bookings.py, sandboxes/scripts/creators/industrial/create_industrial_event_stocks.py, sandboxes/scripts/creators/industrial/create_industrial_mediations.py, sandboxes/scripts/creators/industrial/create_industrial_offerers_with_pro_users.py, sandboxes/scripts/creators/industrial/create_industrial_pro_users_api_keys.py, sandboxes/scripts/creators/industrial/create_industrial_recommendations.py, sandboxes/scripts/creators/industrial/create_industrial_thing_stocks.py, sandboxes/scripts/save_sandbox.py, sandboxes/scripts/utils/storage_utils.py, tests/utils/tutorials_test.py, utils/tutorials.py
On passe de 16s à 10s !!!!
Essentiellement car on sauvegardait trop de fois, j'ai juste fait en sorte que la fonction `save` prenne plusieurs model.
=> [QUICKWIN] (pC-2944) reduce time for making a sandbox

.circleci/config.yml
=> (pC-2182) update node version

.circleci/config.yml
Link api and metabase ci
Add metabase tests in nightly jobs
=> Pc 2821 link api and metabase ci

alembic/versions/04928427ce14_add_status_on_bank_informations.py, connectors/api_demarches_simplifiees.py, domain/bank_information.py, domain/demarches_simplifiees.py, local_providers/demarches_simplifiees_bank_information.py, local_providers/demarches_simplifiees_bank_information_without_siret.py, local_providers/demarches_simplifiees_offerer_bank_information.py, local_providers/demarches_simplifiees_venue_bank_information.py, local_providers/local_provider.py, models/bank_information.py, models/offerer.py, repository/offerer_queries.py, scripts/beneficiary/old_remote_import.py, scripts/beneficiary/remote_import.py, tests/domain/bank_information_test.py, tests/domain/demarches_simplifiees_test.py, tests/local_providers/demarches_simplifiees_bank_information_test.py, tests/local_providers/demarches_simplifiees_offerer_bank_information_test.py, tests/local_providers/demarches_simplifiees_venue_bank_information_test.py, tests/local_providers/demarches_simplifiees_without_siret_test.py, tests/model_creators/generic_creators.py, tests/models/offerer_test.py, tests/repository/repository_test.py, tests/routes/get_offerers_test.py, tests/validation/models/bank_information_test.py, utils/includes.py, validation/models/bank_information.py
Mieux vaut regarder commit par commit normalement ils sont bien découpés
Par contre mon linter ajoute pleins de retours à la ligne sur les fichiers modifiés, ça fait pas mal de bruits dans le diff :/
Je sais pas s'il y a une politique de pas passer à la ligne du tout ? Ou si au contraire on le fait petit à petit, sur le fichiers où c'est pas fait encore ?
=> PC-3269 Upload de rib : track application status

app.py, tests/workers/logger_test.py, workers/bank_information_job.py, workers/decorators.py, workers/logger.py, workers/worker.py
add logs to dms webhook worker, add error to sentry and create grafana panel
=> (PC-3421): DMS webhook monitoring

repository/payment_queries.py, tests/repository/payment_queries_test.py, tests/scripts/payment/batch_steps_test.py
=> (PC-3699): do not put to retry not_processable payment with not accepted bank information

domain/venue/venue_repository.py, infrastructure/container.py, infrastructure/repository/venue/venue_sql_repository.py, repository/venue_queries.py, routes/serialization/venues_serialize.py, routes/venues.py, tests/infrastructure/venue/venue_sql_repository_test.py, tests/repository/venue_queries_test.py, tests/routes/get_venues_test.py, tests/routes/serialization/venues_serialize_test.py, tests/use_cases/get_all_venues_by_pro_user.py, use_cases/get_all_venues_by_pro_user.py
Revoir https://github.com/betagouv/pass-culture-api/pull/1261 avant
=> Pc 3536 migrate clean archi get venues application side

repository/offerer_queries.py, repository/venue_queries.py, routes/__init__.py, routes/export.py, tests/repository/offerer_queries_test.py, tests/repository/venue_queries_test.py, tests/routes/export_test.py, tests/validation/routes/export_test.py, validation/routes/exports.py, validation/routes/headers.py
This reverts commit 5969ea488de15acb9ed9d5d8fffca22ae2a1c974.
=> Revert "(PC-2717): delete export routes"

local_providers/libraires_stocks.py, sandboxes/scripts/creators/bookings_recap/bookings_recap.py, sandboxes/scripts/creators/helpers/sql_creators.py, tests/sandboxes/scripts/bookings_recap/bookings_recap_test.py
- Ajout de plusieurs cas pour la sandbox bookings recaps
- Copie des fonctions de creators de tests pour supprimer la dépendance entre les dossiers sandbox et tests (cela permettrait de ne pas déployer le dossier test sur les envs scalingo => taille de l'image)
=> (PC-3759) Add cases to bookings recap sandbox

.circleci/config.yml
Correction du job circleci "tests-data-analytics"
⚠️ ce job ne s'éxécute que sur la branch master, toutes les heures
Pour pouvoir tester, son exécution a été forcée pour le premier commit, voir le résultat de sa ci
(Le deuxième commit ne fait qu'enlever cette exécution forcée)
=> (PC-3715): Data-analytics tests

scripts/iris/import_iris.py, tests/scripts/iris/import_iris_test.py
On passe de 50s à moins de 20s pour la sandbox.
=> (PC-4141): reduce time for iris sandbox

infrastructure/repository/beneficiary/beneficiary_jouve_converter.py, tests/infrastructure/repository/beneficiary/beneficiary_jouve_repository_test.py
because we were expecting something else from Jouve
=> (PC-4239): ID Check - Temporarily changing date format for birthdate

models/venue_sql_entity.py, tests/routes/post_offerer_test.py, tests/routes/signup_pro_test.py, tests/scripts/offerer/file_import_test.py
Sur celles qui sont crées par defaut a la creation d'une structure ou compte pro
=> (PC-3668): Ajout du VenueType "Offre Numerique" sur les venues digitales par défaut

pytest.ini
Le format des traceback actuel est très verbeux et en rend compliqué la lecture. Le but est de les rendre plus lisibles:
Actuellement:
```
mock_api_entreprise = <MagicMock name='get' id='4850703808'>, app = <Flask 'tests.conftest'>
@patch('connectors.api_entreprises.requests.get')
@patch('utils.mailing.DEV_EMAIL_ADDRESS', 'dev@example.com')
def test_maybe_send_offerer_validation_email_sends_email_to_pass_culture_dev_when_objects_to_validate_and_send_email_disabled(
mock_api_entreprise,
app):
response_return_value = MagicMock(status_code=200, text='')
response_return_value.json = MagicMock(
return_value={"unite_legale": {"etablissement_siege": {}, "etablissements": []}})
mock_api_entreprise.return_value = response_return_value
offerer = create_offerer(validation_token='12345')
user = …
```
=> (PC-4539) : shorten test traceback

local_providers/fnac/fnac_stocks.py, local_providers/generic_provider/generic_stocks.py, local_providers/libraires/libraires_stocks.py, local_providers/praxiel/praxiel_stocks.py, local_providers/titelive_stocks/titelive_stocks.py, tests/local_providers/titelive_stocks_test.py
Implentation - Fnac / Praxiel / Les Libraires / Titelive Stocks
=> (PC-4471): Local Provider - Refacto

domain/reimbursement.py, tests/domain/reimbursement_test.py
https://passculture.atlassian.net/browse/PC-4549
=> PC-4549: edit reimbursement thresholds

src/pcapi/flask_app.py, src/pcapi/scheduled_tasks/algolia_clock.py, src/pcapi/scheduled_tasks/clock.py, src/pcapi/scheduled_tasks/titelive_clock.py, src/pcapi/scheduled_tasks/utils.py
This will help seeing the errors that happens when scheduled
tasks are run.
=> (PC-4763) : Configure Sentry for scheduled tasks

src/pcapi/scripts/venue/modify_allocine_price_rule_for_venue.py, tests/scripts/venue/modify_allocine_price_rule_for_venue_test.py
A voir avant de merger : pourquoi le commit n'était pas possible sans --no-verify
=> (PC-4191): Add script to update price for venue linked to provider Allocine

src/pcapi/core/bookings/repository.py, src/pcapi/scripts/dashboard/diversification_statistics.py, src/pcapi/scripts/payment/batch_steps.py, tests/core/bookings/test_repository.py
For events, do not reimburse ones that have not yet begun.
=> [PC-4689] edit reimbursement script rules

src/pcapi/sandboxes/scripts/creators/allocine/__init__.py
Ajout d'un user admin pour la sandbox allociné.
Note: Il serait intéréssant d'inclure ces données dans la sandbox industrial ?
=> sandbox.allocine: add admin user

src/pcapi/core/recommendations/factories.py, src/pcapi/core/testing.py, src/pcapi/models/db.py, src/pcapi/repository/recommendation_queries.py, src/pcapi/utils/credentials.py, tests/conftest.py, tests/core/bookings/test_api.py, tests/routes/get_offers_test.py, tests/routes/get_recommendations_by_offer_test.py, tests/routes/serialization/bookings_serialize_test.py
=> [PC-4744] Ajout de assert_num_queries et optimisation pour éviter 2 requêtes SQL

src/pcapi/domain/pro_offers/paginated_offers_recap_repository.py, src/pcapi/infrastructure/repository/pro_offers/paginated_offers_recap_sql_repository.py, src/pcapi/routes/offers.py, src/pcapi/routes/serialization/offers_serialize.py, src/pcapi/use_cases/list_offers_for_pro_user.py, tests/infrastructure/repository/pro_offers/paginated_offers_recap_sql_repository_test.py, tests/use_cases/list_offers_for_pro_user_test.py
Ajout du filtre par catégories pour la liste des offres
=> (PC-4291): add offers filter by type

src/pcapi/routes/native/v1/authentication.py, src/pcapi/routes/native/v1/serialization/authentication.py, tests/routes/native/authentication_test.py
Requires #1514 (PC 4962) to be merged first.
=> PC 4963: access token refresh

src/pcapi/repository/clean_database.py
Pas du tout lié à PC-4030, mais voilà.
=> (PC-4030) repository: Add a safety belt in `clean_all_database`

src/pcapi/connectors/thumb_storage.py, src/pcapi/core/offerers/factories.py, src/pcapi/core/offers/factories.py, src/pcapi/domain/mediations.py, src/pcapi/local_providers/local_provider.py, src/pcapi/routes/mediations.py, src/pcapi/sandboxes/scripts/utils/storage_utils.py, tests/core/offers/test_api.py, tests/local_providers/local_provider_test.py, tests/routes/post_mediation_test.py
Commits à relire séparément. Le 2ème commit peut être vu rapidement : je n'ai pas modifié l'intention des tests, j'ai juste réécrit avec des factories.
=> (PC-4881) thumbs : Réécriture (pour réutilisation de code) + factories + correction d'un bug

src/pcapi/core/bookings/api.py, src/pcapi/core/offers/api.py, tests/core/bookings/test_api.py, tests/core/offers/test_api.py
=> (PC-5080): Mise a jour de la date de confirmation lors du report

requirements.txt, src/pcapi/connectors/google_spreadsheet.py, tests/connectors/google_spreadsheet_test.py
=> (PC-4881) : suppression de la dépendance à pygsheets, simplification du code dans pcapi.connectors.google_spreadsheet

src/pcapi/domain/departments.py, src/pcapi/routes/serialization/reimbursement_csv_serialize.py, src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_event_occurrences.py, src/pcapi/utils/date.py, tests/utils/date_test.py
Commits à relire séparément. J'en ai profité pour faire un peu de ménage dans le module `utils.date`.
=> (PC-5246) Définition des fuseaux horaires pour d'autres départements et territoires hors de la métropole

src/pcapi/core/users/api.py
This was lost during rebase of b1afaf6ae7c6a59920528e6cc2e94ff18c14f4fd
=> (PC-4964) : remove functions moved to core.users.repository

src/pcapi/domain/pro_offers/paginated_offers_recap.py, src/pcapi/infrastructure/repository/pro_offers/paginated_offers_recap_domain_converter.py, src/pcapi/routes/serialization/offers_recap_serialize.py, src/pcapi/routes/serialization/offers_serialize.py, tests/routes/pro/get_offers_test.py, tests/routes/serialization/offers_recap_serialize_test.py
The pro frontend needs the venue departementCode to display the stock hours correctly when the timezone is different...
=> (PC-5454) Add venue departementCode in offer query

src/pcapi/admin/custom_views.py
=> (PC-5433) Add CanBookFreeOffers as editable in user form

src/pcapi/core/bookings/api.py, src/pcapi/core/bookings/repository.py, src/pcapi/scripts/beneficiary/file_import.py, src/pcapi/utils/token.py, tests/core/bookings/test_repository.py, tests/scripts/beneficiary/file_import_test.py
=> (PC-5536) Token de réservations : vérification de l'unicité du token et changement de l'implémentation

src/pcapi/scripts/beneficiary/migrate_can_book_free_offer_data.py
=> (PC-5622) Add script to migrate canBookFreeOffers data

src/pcapi/core/offers/factories.py, src/pcapi/routes/serialization/offers_serialize.py, tests/routes/pro/get_offer_test.py
Plusieurs commits à relire séparément.
=> (PC-5710) Permettre l'accès aux offres même si l'offreur n'a pas de SIREN

.circleci/config.yml, Dockerfile.gcp, entrypoint.sh
- Un nouveau fichier .env créé pour chaque environnement GCP (testing, integration, staging, production)
- Ajout des variables non secretes dans les fichiers .env GCP (les variables secretes restent dans le fichier config.yaml)
- Creation d'un Dockerfile pour le run GCP
=> (PC-5571) Create new env for gcp

src/pcapi/scripts/interact.py
=> interact: set a distinctive prompt in testing env

src/pcapi/core/offers/models.py, src/pcapi/model_creators/generic_creators.py, src/pcapi/routes/CONTRIBUTING.md, src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_offerers_with_pro_users.py, src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_recommendations.py, tests/routes/pro/put_venue_offers_test.py, tests/routes/shared/get_features_test.py, tests/routes/webapp/delete_favorites_test.py, tests/routes/webapp/get_favorites_test.py, tests/routes/webapp/post_favorites_test.py
=> Divers : Utilisation de NeedsValidationMixin.isValidated ; suppression du préfixe API_URL dans les tests

src/pcapi/scripts/beneficiary/remote_import.py
Log the traceback if an exception occurs, but log at INFO level not to
pollute Sentry.
=> scripts: Log traceback details on error in beneficiary remote_import

src/pcapi/emails/beneficiary_activation.py, tests/emails/beneficiary_activation_test.py
& rename the deep link (cc @BenStirrup)
=> [PC 5889] add email in activation deeplink

.circleci/config.yml
Enveloppe chaque bloc susceptible de fail avec
```shell
set +eo pipefail
true
```
=> fix(CI) handle-gcp-workflow-failure non failing job

src/pcapi/scripts/booking/handle_expired_bookings.py
This will help Grafana monitoring
=> (PC-5477) scripts: edit handle_expired_bookings logs

src/pcapi/workers/worker.py
Tout OK :
Redis KO :
Database KO :
=> (PC-5465) Add worker log on connection success

src/pcapi/core/bookings/api.py, src/pcapi/core/bookings/conf.py, src/pcapi/core/bookings/validation.py, src/pcapi/core/payments/api.py, src/pcapi/core/payments/factories.py, src/pcapi/model_creators/generic_creators.py, src/pcapi/sandboxes/scripts/creators/bookings_recap/bookings_recap.py, src/pcapi/sandboxes/scripts/creators/helpers/sql_creators.py, tests/core/bookings/test_api.py, tests/core/bookings/test_validation.py
=> (PC-5828) Adaptations pour seuils multiples selon version du dépôt

.dockerignore, Dockerfile.gcp, entrypoint.sh
[PC-5904](https://passculture.atlassian.net/browse/PC-5904?atlOrigin=eyJpIjoiYjExYjBlNTU1NjkxNGEyOTg4NGI2MjFjYjgzYjVhZTkiLCJwIjoiaiJ9)
=> (PC-5904) gunicorn+docker optimisations for cloudrun

src/pcapi/alembic/versions/09857d7d7492_migrate_activity_triggers.py, src/pcapi/alembic/versions/775d3270a33c_payment_recipient_name_validate_.py, src/pcapi/alembic/versions/77c4edf7c1fe_payment_recipient_remove_check.py, src/pcapi/alembic/versions/9e677288a5a3_payment_recipient_name_not_null.py, src/pcapi/alembic/versions/ebce3e2bdd8d_payment_recipient_name_check_constraint.py, src/pcapi/core/payments/factories.py
See https://github.com/pass-culture/pass-culture-api/pull/1724 for the comments
=> (Pc-5508) Add not null constraint on payment recipientName

src/pcapi/alembic/versions/44c394e902b7_add_not_null_constraint_to_email_datetime.py, src/pcapi/alembic/versions/541e87e7b7bb_add_not_null_to_email_datetime.py, src/pcapi/alembic/versions/692f4bd89a83_drop_not_null_constraint_on_email_datetime.py, src/pcapi/alembic/versions/eb7d08bda995_validate_email_datetime_is_not_null.py
Le détail est étapes en expliqué dans la PR #1724
=> (PC-5508) : Add not null constraint on email.datetime

src/pcapi/validation/models/stock.py, tests/models/stock_sql_entity_test.py
https://passculture.atlassian.net/browse/PC-5716
=> (PC-5716): Add dedicated message for stock price too low

src/pcapi/workers/worker.py
The database connection test was opening a connection that was causing troubles.
Instead of having to kill the connection at each job beggining: https://stackoverflow.com/a/17523913 we'd rather remove this db connection test
=> (PC-6267) Fix worker db connections and exception handler

src/pcapi/routes/webapp/beneficiaries.py, tests/routes/webapp/post_signin_beneficiary_test.py
Ticket: https://passculture.atlassian.net/browse/PC-3347
=> (PC-3347) [Sécurité] Adapter les messages d'erreur de connexion - webapp

src/pcapi/domain/user_activation.py, src/pcapi/scripts/beneficiary/remote_import.py, tests/domain/user_activation_test.py, tests/scripts/beneficiary/remote_import_test.py
Allow DMS to turn a non beneficiary account into beneficiary
through DMS.
=> (PC-6011) : native app accounts to become beneficiary via DMS

src/pcapi/emails/beneficiary_activation.py, tests/domain/user_emails_test.py, tests/emails/beneficiary_activation_test.py, tests/routes/native/v1/account_test.py
Adds specific sections for under age and eligible users
=> (PC-6111) : Change activation email template

src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_bookings.py
Pour déconstruire la sandbox dans un code maintenable, j'ai utilisé l'IDE et la technique de legacy qui commence par faire une branche avec un `if` et la duplication du code, puis le nettoyage.
=> (PC-6381): Fix expenses maximum for sandbox account

src/pcapi/app.py, src/pcapi/load_environment_variables.py, src/pcapi/scheduled_tasks/titelive_clock.py, src/pcapi/workers/worker.py
Attendre que la version v117.x soit en production avant de merger cette PR.
=> [PC 4923] one more (last) thing

src/pcapi/core/offers/factories.py, src/pcapi/routes/pro/offers.py, src/pcapi/routes/serialization/offers_serialize.py, tests/routes/native/v1/offers_test.py, tests/routes/pro/get_offers_test.py
[la PR frontend](https://github.com/pass-culture/pass-culture-pro/pull/989) correspondante pour le jira https://passculture.atlassian.net/browse/PC-6293
=> [PC-6293] offers accessibility

src/pcapi/core/offers/validation.py, tests/core/offers/test_api.py
=> (PC-6089): Allow edition of externalTicketOfficeUrl for synchronized offers

src/pcapi/core/bookings/repository.py, src/pcapi/domain/payments.py, src/pcapi/model_creators/specific_creators.py, src/pcapi/settings.py, tests/core/bookings/test_repository.py, tests/domain/payments_test.py, tests/domain/reimbursement_test.py
=> Suppression de `find_date_used`, `create_booking_for_event()` et `create_booking_for_thing()`

src/pcapi/alembic/versions/aa3691cfdc6d_add_product_offerer_foreign_key_step_2.py, src/pcapi/alembic/versions/e8ba63242789_add_product_offerer_foreign_key.py
Doc postgre : https://docs.postgresql.fr/9.6/sql-altertable.html
=> (PC-5508) Add foreign key on product.owningOffererId

src/pcapi/routes/native/security.py, src/pcapi/routes/native/v1/blueprint.py
This will fix using the Swagger UI with authenticated operations.
=> (PC-6594) : declare the security info in OpenAPI schema

src/pcapi/admin/custom_views/pro_user_view.py, src/pcapi/flask_app.py, tests/admin/custom_views/pro_user_view_test.py
Commits à relire séparément. Le premier va vous étonner (petit bonus).
=> (PC-6018) Correction sur la page d'admin des utilisateurs pro

src/pcapi/alembic/versions/514dfbeddddf_fix_get_wallet_balance.py, src/pcapi/core/bookings/models.py
And by "all", I mean all deposits. Of all users. Which made for a
substantial wallet balance...
=> bookings: Fix get_wallet_balance that would sum all deposits

src/pcapi/routes/native/v1/serialization/account.py, tests/routes/native/v1/account_test.py
Shows when a user should see the eligibility card
=> (PC-6297) : Add showEligibleCard to the profile

src/pcapi/admin/custom_views/offer_view.py, src/pcapi/admin/custom_views/venue_view.py, src/pcapi/admin/install.py, src/pcapi/templates/admin/venue_offers_list.html
=> (PC-6901) Add offer for venue view to prevent timeout on offer name search

src/pcapi/core/offerers/repository.py, src/pcapi/routes/pro/offerers.py, src/pcapi/routes/serialization/offerers_serialize.py, tests/routes/pro/get_offerers_names_test.py
PR frontend liée: https://github.com/pass-culture/pass-culture-pro/pull/1089
=> [PC-6524] offerers: allow to get not validated offerers

src/pcapi/workers/worker.py
https://python-rq.org/docs/workers/#the-worker-lifecycle
> Fork a child process. A child process (the “work horse”) is forked off to do the actual work in a fail-safe context.
https://docs.sqlalchemy.org/en/13/core/connections.html?highlight=dispose#engine-disposal
>  When a program uses multiprocessing or fork(), and an Engine object is copied to the child process, Engine.dispose() should be called so that the engine creates brand new database connections local to that fork. Database connections generally do not travel across process boundaries.
=> (PC-6328) Close db connections before starting worker jobs

src/pcapi/validation/routes/features.py, tests/local_providers/allocine_stocks_test.py, tests/local_providers/venue_provider_worker_test.py, tests/routes/pro/patch_venue_test.py, tests/routes/pro/put_venue_offers_test.py, tests/routes/pro/validate_offerer_test.py, tests/scheduled_tasks/decorators_test.py, tests/utils/feature_test.py, tests/validation/routes/features_test.py
=> Utilisation de override_settings et override_features dans les tests

tests/scripts/booking/handle_expired_bookings_test.py
The `assert_num_queries` fixture ignores the `SAVEPOINT` statements added by flask/SQLA/pytest during tests
=> tests: use assert_num_queries instead of get_debug_queries

.circleci/config.yml
Same as 3e8a112fedc71159707591f06367a27a1096a47d...
=> ci: Do not cache requirements on "master" builds (for quality build)

src/pcapi/sandboxes/scripts/creators/industrial/__init__.py, src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_event_stocks.py, src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_thing_stocks.py, src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_webapp_users.py, tests/sandboxes/scripts/create_industrial_webapp_users_test.py
User names:
- pctest.jeune93.has-booked-some-but-deposit-expired.v1@example.com
- pctest.jeune93.has-booked-some-but-deposit-expired.v1@example.com
- pctest.jeune97.has-booked-some-but-deposit-expired.v2@example.com
- pctest.jeune97.has-booked-some-but-deposit-expired.v2@example.com
=> (PC-6935) sandbox: Add user who has booked but whose deposit has expired

src/pcapi/admin/custom_views/criteria_view.py, src/pcapi/alembic/versions/b00c0a0dec8f_criterion_scoredelta_nullable.py, src/pcapi/core/offers/factories.py, src/pcapi/model_creators/generic_creators.py, src/pcapi/models/criterion.py, src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_criterion.py
This column is not used since dde59b1d66df0fa1f843bfa3a2a2775f5b09455d.
It will be removed. For this we first need to make it nullable. We can
also stop displaying it.
=> offers: Make unused column Criterion.scoreDelta nullable

src/pcapi/infrastructure/repository/stock_provider/provider_api.py, src/pcapi/local_providers/fnac/fnac_stocks.py, src/pcapi/local_providers/fnac/fnac_stocks_provider.py, src/pcapi/local_providers/generic_provider/generic_stocks.py, src/pcapi/local_providers/libraires/libraires_stocks.py, src/pcapi/local_providers/praxiel/praxiel_stocks.py, src/pcapi/local_providers/titelive_stocks/titelive_stocks.py, tests/infrastructure/repository/stock_provider/provider_api_test.py, tests/infrastructure/repository/stock_provider/titelive_provider_api_test.py, tests/local_providers/fnac_stocks_test.py, tests/local_providers/libraires_stocks_test.py, tests/local_providers/praxiel_stocks_test.py, tests/local_providers/titelive_stocks_test.py
Commits à relire séparément, j'ai fait un peu de ménage au passage.
=> (PC-5668) Providers : Ne pas ignorer les réponses invalides des providers de stocks

src/pcapi/routes/serialization/offerers_serialize.py, tests/routes/pro/get_offerer_test.py
Encore un champs manquant afin que le front puisse déterminer si des dossier bancaire sont en cours de traitement.
=> [PC-6667] routes.pro.get_offerer: add field: venue.demarchesSimplifieesApplicationId

src/pcapi/core/object_storage/backends/local.py, src/pcapi/core/object_storage/backends/ovh.py, src/pcapi/core/object_storage/testing.py, src/pcapi/scripts/delete_unused_mediations_and_assets.py, tests/conftest.py, tests/scripts/delete_unused_mediations_and_assets.py
Cette PR permettra de supprimer les Médiations et les assets désormais inutiles
On ajoute au module scripts 2 fonctions, et au backend OVH une méthode permettant de récupérer les infos du container.
...
=> PC-5329: delete unnecessary mediations and sets

src/pcapi/core/offerers/repository.py, src/pcapi/routes/pro/offerers.py, src/pcapi/routes/serialization/offerers_serialize.py, tests/routes/pro/get_offerers_names_test.py
* add "validated_for_user" filter
=====
@todo:
=> [PC-7136] get_offerer_names: add filter

src/pcapi/routes/native/utils.py, src/pcapi/routes/native/v1/__init__.py, src/pcapi/routes/native/v1/favorites.py, src/pcapi/routes/native/v1/serialization/favorites.py, tests/routes/native/v1/favorites_test.py, tests/routes/native/v1/utils.py
First draft to add a list of favorites for the native applications.
Optimizations and refactoring will come later - front devs need
to get started.
=> (PC-7033) : Add favorite list for native app

src/pcapi/core/offers/api.py
This fixes what appears to be an obsolete reference to a Model during
the create_mediation() workflow.
https://logs.passculture.app/organizations/sentry/issues/2891/
=> (PC-7263) offers: fix ObjectDeletedError

src/pcapi/domain/venue/venue_with_offerer_name/venue_with_offerer_name_repository.py, src/pcapi/infrastructure/repository/venue/venue_with_offerer_name/venue_with_offerer_name_sql_repository.py, src/pcapi/routes/pro/venues.py, src/pcapi/use_cases/get_venues_by_pro_user.py, tests/infrastructure/repository/venue/venue_with_offerer_name/venue_with_offerer_name_sql_repository_test.py, tests/routes/pro/get_venues_test.py
* validated_offerer
* validated_user_offerer
===
utilisation de ces filtres dans le front : https://github.com/pass-culture/pass-culture-pro/pull/1147
=> [PC-7136] add filters to get_venues

src/pcapi/admin/custom_views/offer_view.py
Needs https://github.com/pass-culture/pass-culture-api/pull/2060 to be merged
=> (PC-7145):  LCF - add offer validation column to flaskadmin

src/pcapi/local_providers/titelive_things/titelive_things.py
It's useful when a bookstore asks why a particular ISBN does not
appear in our product repository. Now we at least have a log that
tells us why a product was not imported.
=> (PC-7490) titelive: Log ineligible products that we do not import

src/pcapi/routes/serialization/beneficiaries.py, tests/routes/serialization/beneficiary_serialize_test.py, tests/routes/webapp/patch_beneficiary_test.py
Ticket Jira associé : https://passculture.atlassian.net/browse/PC-6360
=> (PC-4847) Add pk property (I.e. user.id) in '/current' response for webapp

src/pcapi/core/offers/models.py, src/pcapi/routes/native/v1/favorites.py, src/pcapi/routes/native/v1/serialization/favorites.py, tests/routes/native/v1/favorites_test.py
Expired offers are those whose booking date is past.
TODO:
=> (PC-7035) : native app favorites now compute expired offers

src/pcapi/core/bookings/repository.py, src/pcapi/routes/pro/bookings.py
Tokens are stored as uppercase in the database, but users may enter
them in lowercase. We should handle that.
=> (PC-7607) bookings: Always do an insensitive case lookup on booking tokens

src/pcapi/routes/native/v1/favorites.py, tests/routes/native/v1/favorites_test.py
Quick and easy win, turns out I could add an extra join to improve
Also don't count soft deleted stocks when computing exhausted offer
=> (PC-7034) : improve favorite performance

src/pcapi/notifications/push/backends/batch.py
Custom API success code is 200 but Transactional is 201
=> (PC-6835) Use response.ok to tell if batch request has error

src/pcapi/admin/custom_views/many_offers_operations_view.py, src/pcapi/core/offers/api.py, tests/core/offers/test_api.py
Currently, some products are duplicated: we may have the same ISBN in
an automatically-synchronized product and a manually-created product.
In that case, we should process both products and all their offers.
=> (PC-7719) admin: Handle duplicate products in batch operation on offers

src/pcapi/core/offers/api.py, tests/core/offers/test_api.py
The Offer should immediately be deactivated
=> (PC-7528) edit Offer creation when using the mock validation

src/pcapi/admin/custom_views/beneficiary_user_view.py, tests/admin/custom_views/beneficiary_user_view_test.py
=> (PC-7711) Modifications sur la page admin des bénéficiaires

src/pcapi/core/bookings/api.py, src/pcapi/core/offers/api.py, src/pcapi/core/users/api.py, src/pcapi/local_providers/provider_api/synchronize_provider_api.py, src/pcapi/routes/error_handlers/generic_error_handlers.py, src/pcapi/routes/error_handlers/thumbnails_error_handlers.py, src/pcapi/routes/pro/offerers.py, src/pcapi/routes/pro/validate.py, src/pcapi/routes/shared/passwords.py
This commit adds new logs where necessary, and adapts existing logs to
the new mechanism, using the new `extra` argument.
This is not exhaustive. I focused on bookings, offers and users `api`
modules, and the new provider synchronization mechanism.
=> (PC-7670) Add new logs and extend/adapt existing ones

src/pcapi/infrastructure/repository/pro_offerers/paginated_offerers_sql_repository.py, tests/routes/pro/get_offerers_test.py
jira: https://passculture.atlassian.net/browse/PC-3074
PR frontend: https://github.com/pass-culture/pass-culture-pro/pull/1194
=> [PC-3074] Offerer route get_offerers: add isActive filter

src/pcapi/core/bookings/models.py, src/pcapi/core/bookings/repository.py
The previous version of the query took about 60 seconds on staging. By
applying some filters first (before the JOIN on the "offer"), the
query is much quicker: around 200 ms on staging.
The `Booking.expirationDate` hybrid property may have been a good
idea, but here it made us perform an under-optimized SQL query. To
avoid this in the future, let's remove it. We can keep a "standard"
property for this (and hope that the caller will have joinedload'ed
the offer to avoid N+1 SQL queries).
=> (PC-7830) bookings: Optimize `find_soon_to_be_expiring_booking_ordered_by_user()`

src/pcapi/core/bookings/repository.py, src/pcapi/routes/serialization/reimbursement_csv_serialize.py, src/pcapi/scripts/payment/batch_steps.py, tests/scripts/payment/batch_steps_test.py
Commits à relire séparément, j'en ai profité pour faire un peu de ménage.
=> (PC-7188) Utilisation du nouvel état UNDER_REVIEW dans la génération des paiements

src/pcapi/scripts/stock/fully_sync_venue.py, tests/scripts/stock/fully_sync_venue_test.py
=> (PC-7772) Optimisation de fully_sync_venue

entrypoint.sh
Set to 3000 to force worker restart approximately every 2H
=> feat(gunicorn): add --max-requests

README.md, src/pcapi/connectors/beneficiaries/jouve_backend.py, tests/connectors/beneficiaries/beneficiary_jouve_repository_test.py
https://passculture.atlassian.net/secure/RapidBoard.jspa?rapidView=34&modal=detail&selectedIssue=PC-7845&quickFilter=278
=> [PC-7845] Temporary fix on jouve_backend

src/pcapi/admin/custom_views/allocine_pivot_view.py, src/pcapi/alembic/versions/20210329_202ae94f2c8f_add_internal_id_to_allocine_venue_.py, src/pcapi/alembic/versions/20210329_5a767131f3ec_add_internal_id_to_allocine_pivot.py, src/pcapi/core/providers/factories.py, src/pcapi/local_providers/allocine/allocine_stocks.py, src/pcapi/model_creators/generic_creators.py, src/pcapi/model_creators/specific_creators.py, src/pcapi/models/allocine_pivot.py, src/pcapi/models/allocine_venue_provider.py, src/pcapi/repository/allocine_pivot_queries.py, src/pcapi/routes/serialization/bookings_serialize.py, src/pcapi/scripts/add_allocine_internal_ids.py, src/pcapi/use_cases/connect_venue_to_allocine.py, tests/local_providers/allocine_stocks_functions_test.py, tests/local_providers/allocine_stocks_test.py, tests/repository/allocine_pivot_queries_test.py, tests/routes/pro/get_booking_by_token_v2_test.py, tests/routes/pro/post_venue_provider_test.py, tests/routes/serialization/bookings_serialize_test.py, tests/use_cases/connect_allocine_to_venue_test.py
=> (PC-7234) Add theater information for boost

src/pcapi/core/bookings/api.py, src/pcapi/core/offers/api.py, tests/core/bookings/test_api.py, tests/core/offers/test_api.py
Dans le portail Pro, lors de la suppression d’un Stock, ses Bookings associées qui sont effectivement supprimées (pas dans le passé ou déjà annulées) doivent enregistrer la BookingCancellationReason suivante: `OFFERER`.
 D’autre part, la `dnBookedQuantity` doit également être mise à jour.
=> (PC-7903) fix booking cancellation when deleting stock

src/pcapi/core/mails/CONTRIBUTING.md, src/pcapi/emails/beneficiary_activation.py, tests/emails/beneficiary_activation_test.py
https://passculture.atlassian.net/secure/RapidBoard.jspa?rapidView=34&modal=detail&selectedIssue=PC-7881&quickFilter=267
=> [PC-7881] Configure depositAmount for account confirmation mail

src/pcapi/routes/serialization/users.py, src/pcapi/routes/webapp/beneficiaries.py, src/pcapi/use_cases/update_user_informations.py, src/pcapi/validation/routes/users.py, tests/routes/pro/patch_user_test.py, tests/routes/webapp/patch_beneficiary_test.py, tests/use_cases/update_user_informations_test.py
Une meilleure correction serait de passer à pydantic sur ce point d'entrée. Mais, en attendant, cette pull request suffira.
=> (PC-7923) Do not allow a user to change their e-mail without confirmation

src/pcapi/alembic/versions/20210402_5e52ca521f36_feature_auto_activate_bookings.py, src/pcapi/core/bookings/api.py, src/pcapi/models/feature.py, tests/core/bookings/test_api.py, tests/routes/pro/patch_booking_by_token_test.py, tests/routes/pro/patch_booking_use_by_token_test.py, tests/routes/pro/validate_bookings_test.py
=> (PC-7783) Activation automatique des réservations numériques

src/pcapi/core/users/api.py, src/pcapi/routes/serialization/beneficiaries.py, src/pcapi/routes/webapp/beneficiaries.py, tests/routes/webapp/patch_beneficiary_test.py
=> (PC-7955) Correction de la route de mise à jour des infos relatives aux tutoriels + sondage pour la webapp

src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_webapp_users.py, tests/sandboxes/scripts/create_industrial_webapp_users_test.py
https://passculture.atlassian.net/secure/RapidBoard.jspa?rapidView=16&modal=detail&selectedIssue=PC-7906
=> [PC-7906] Add not beneficiary users to sandbox

src/pcapi/core/bookings/api.py, src/pcapi/scripts/booking/handle_expired_bookings.py, tests/scripts/booking/handle_expired_bookings_test.py
The expired bookings scheduled tasks must recompute the associated
stock's dnBookedQuantity.
Since there are - sometimes - a lot fo bookings to cancel, the
scheduled task cancels by batches, it does not use the usual
process and dnBookedQuantity update needs to be explicitly performed.
=> (PC-8103) : update dnBookedQuantity when bookings are auto cancelled

src/pcapi/admin/custom_views/admin_user_view.py, src/pcapi/admin/custom_views/partner_user_view.py, tests/admin/custom_views/admin_user_view_test.py, tests/admin/partner_user_view_test.py
Lien vers ticket Jira : https://passculture.atlassian.net/browse/PC-8102
Test unitaires ajoutés : ✅
=> (PC-8102) Allow suspension of admin and partner accounts by super admin

src/pcapi/scripts/stock/fully_sync_venue.py
Now that we have denormalized the number of non-cancelled bookings, we
don't need to calculate it again for `fully_sync_venue()`.
----
J'ai essayé d'écrire quelque chose comme
Stock.query.join(Offer).filter(Offer.venueId == venue.id).update(
{Stock.quantity: Stock.dnBookedQuantity},
)
...mais SQLAlchemy refuse:
sqlalchemy.exc.InvalidRequestError: Can't call Query.update()
J'ai cherché environ 12 secondes et je me suis dit : "À quoi bon ? La
requête SQL brute est lisible, ça marche, on garde."
=> scripts: Use `Stock.dnBookedQuantity` in `fully_sync_venue()`

src/pcapi/core/offers/factories.py, src/pcapi/core/users/factories.py, src/pcapi/models/feature.py, src/pcapi/sandboxes/scripts/__init__.py, src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_offerers_with_pro_users.py, src/pcapi/sandboxes/scripts/creators/testcafe/__init__.py, src/pcapi/sandboxes/scripts/getters/__init__.py, src/pcapi/sandboxes/scripts/getters/pro_01_signup.py, src/pcapi/sandboxes/scripts/getters/pro_02_signin.py, src/pcapi/sandboxes/scripts/getters/pro_04_offerer.py, src/pcapi/sandboxes/scripts/getters/pro_05_venue.py, src/pcapi/sandboxes/scripts/getters/pro_06_offers.py, src/pcapi/sandboxes/scripts/getters/pro_07_offer.py, src/pcapi/sandboxes/scripts/getters/pro_08_stocks.py, src/pcapi/sandboxes/scripts/getters/pro_10_desk.py, src/pcapi/sandboxes/scripts/getters/pro_11_lost_password.py, src/pcapi/sandboxes/scripts/getters/pro_14_home_profile.py, src/pcapi/sandboxes/scripts/sandbox_testcafe.py, tests/routes/pro/get_offer_test.py, tests/routes/serialization/reimbursement_csv_test.py
frontend: https://github.com/pass-culture/pass-culture-pro/pull/1214
jra: https://passculture.atlassian.net/browse/PC-7899
=> [PC-7899] testcafe: add test for home profile modal

requirements.txt, src/pcapi/admin/custom_views/venue_provider_view.py
=> Add wtforms_sqlalchemy to remove deprecation warning

src/pcapi/notifications/push/__init__.py, src/pcapi/notifications/push/backends/batch.py, src/pcapi/notifications/push/backends/logger.py, src/pcapi/notifications/push/backends/testing.py, src/pcapi/notifications/push/user_attributes_updates.py, src/pcapi/scripts/batch_update_users_attributes.py, tests/scripts/batch_update_users_attributes_test.py
**Besoin**
Disposer d'un script permettant de mettre à jour les attributs des utilisateurs.
=> (PC-6882) Permettre l'envoi de mise à jour des attributs de plusieurs utilisateurs à la fois

src/pcapi/core/offerers/api.py, src/pcapi/routes/serialization/venues_serialize.py, tests/routes/pro/patch_venue_test.py
Je ne sais pas comment j'ai laissé passé ca, il manquait un test .
=> [PC-7813] pro.edit_venue: add missing "address" field

src/pcapi/app.py, src/pcapi/routes/native/security.py, src/pcapi/routes/native/v1/blueprint.py, src/pcapi/routes/pro/blueprints.py, src/pcapi/routes/pro/stocks.py, src/pcapi/routes/serialization/stock_serialize.py, src/pcapi/serialization/spec_tree.py, src/pcapi/serialization/utils.py, src/pcapi/validation/routes/users_authentifications.py, tests/conftest.py, tests/routes/pro/post_venue_stocks_test.py
Derniers ajustements avec que l'api ne soit utilisée publiquement
=> (PC-8100): Catch ups on stock api

src/pcapi/connectors/redis.py
The previous implementation used `LPOP <list> <count>`, but the
`count` argument appeared in Redis 6.2. We currently have Redis 5.0,
so we cannot use LPOP to pop multiple items at once.
Instead, we get and delete items within a transaction.
=> (PC-8290) redis: Implement pop_offer_ids without LPOP for old Redis version

src/pcapi/admin/custom_views/booking_view.py, src/pcapi/admin/custom_views/pro_user_view.py, src/pcapi/admin/custom_views/venue_provider_view.py, src/pcapi/core/bookings/repository.py, src/pcapi/core/offerers/api.py, src/pcapi/core/providers/repository.py, src/pcapi/core/users/api.py, src/pcapi/core/users/repository.py, src/pcapi/domain/user_emails.py, src/pcapi/emails/offerer_attachment_validation.py, src/pcapi/infrastructure/repository/bank_informations/bank_informations_sql_repository.py, src/pcapi/infrastructure/repository/offerer/offerer_sql_repository.py, src/pcapi/repository/allocine_pivot_queries.py, src/pcapi/repository/api_key_queries.py, src/pcapi/repository/beneficiary_import_queries.py, src/pcapi/repository/feature_queries.py, src/pcapi/repository/offerer_queries.py, src/pcapi/repository/providable_queries.py, src/pcapi/repository/user_queries.py, src/pcapi/repository/user_session_queries.py, src/pcapi/repository/venue_queries.py, src/pcapi/routes/pro/validate.py, src/pcapi/scripts/stock/soft_delete_stock.py, src/pcapi/scripts/update_venue_type.py, src/pcapi/utils/rest.py, tests/domain/user_emails_test.py, tests/emails/offerer_attachment_validation_test.py, tests/repository/offerer_queries_test.py, tests/routes/native/v1/authentication_test.py
Ça ne traite pas le ticket 8025, mais c'est par là que j'ai commencé.
=> (PC-8025) Utilisation de `first()` vs. `one_or_none()` et nettoyage divers

src/pcapi/core/users/api.py, src/pcapi/core/users/factories.py, src/pcapi/core/users/models.py, src/pcapi/core/users/repository.py, src/pcapi/models/beneficiary_import.py, tests/core/users/test_api.py, tests/core/users/test_repository.py
Ajouter une fonction qui : 
* regarde si l'utilisateur peut passer bénéficiaire ;
* si oui, il le devient ;
* renvoie la liste des étapes manquantes (liste vide si aucune).
=> (PC-8396) beneficiary activation tool

src/pcapi/notifications/sms/backends/sendinblue.py, src/pcapi/settings.py, src/pcapi/utils/settings.py, tests/utils/settings_test.py
=> (PC-8298) Add WHITELISTED_SMS_RECIPIENTS

src/pcapi/core/offerers/models.py, tests/models/offerer_test.py
PR pour ne pas prendre en compte les offres en statut draft `(validation=DRAFT)` dans la property `nOffers` de `Offerer`
=> (PC-8611): update offerer nOffers property to doesn't count Offers with draft status

src/pcapi/scripts/catching_up_dms_beneficiaries_addresses.py, tests/scripts/catching_up_dms_beneficiaries_addresses_test.py
Le script permet de faire le rattrapage des données `Address` pour les bénéficieras inscrits via DMS à partir d'un fichier csv.
=> (PC-8009): add script for catching up dms registred beneficiaries addresses

src/pcapi/core/providers/repository.py, src/pcapi/routes/pro/venue_providers.py, src/pcapi/routes/serialization/venue_provider_serialize.py, src/pcapi/utils/includes.py, tests/routes/pro/get_venue_providers_test.py
jira: https://passculture.atlassian.net/browse/PC-7817
frontend: https://github.com/pass-culture/pass-culture-pro/pull/1304
=> [PC-7817] Api migration list_venue_providers

src/pcapi/repository/user_queries.py, src/pcapi/routes/pro/users.py, src/pcapi/scripts/booking/cancel_bookings_of_events_from_file.py, src/pcapi/scripts/booking/cancel_old_unused_bookings_for_venue.py, tests/routes/pro/patch_user_has_seen_tuto_test.py, tests/routes/shared/post_new_password_test.py, tests/scripts/booking/cancel_bookings_of_events_from_file_test.py, tests/scripts/booking/cancel_old_unused_bookings_for_venue_test.py
Pour la route "seen tutorial", cf. PR correspondante côté frontend : pass-culture/pass-culture-pro#1305
=> (PC-8769) Simplification de la route "seen tutorial" + corrections/nettoyages divers

src/pcapi/core/providers/api.py, src/pcapi/local_providers/provider_api/synchronize_provider_api.py, tests/local_providers/synchronize_provider_api_test.py
2 commits à relire séparément.
=> (PC-8765) Prise en compte du prix spécifique si fourni par le provider

src/pcapi/core/bookings/api.py, tests/core/bookings/test_api.py
From time to time, bookings are cancelled by two requests with
less than a few ms between both.
Since the booking is read before the stock lock to check various
business rules without locking the stock too long.
The downside being that once we reach the stock lock, the booking
may be out of date and already cancelled. Therefore we need to
read again the booking *after* the lock so we ensure we have
a consistent and unique state. The lock will be released with
the commit of the cancellation and the next request will get
the cancelled booking and abort but will not update the
dnBookedQuantity by error.
=> (PC-8795) : Fix dnBookedQuantity with concurent booking cancellation

src/pcapi/core/offers/api.py
Values in `extra` should be JSON-serializable.
=> offers: Fix logging extra

src/pcapi/admin/custom_views/admin_user_view.py, src/pcapi/admin/custom_views/beneficiary_user_view.py, src/pcapi/admin/custom_views/partner_user_view.py, src/pcapi/admin/custom_views/pro_user_view.py
=> (PC-8830) Ajout de User.isActive sur les pages d'admin utilisateurs

src/pcapi/connectors/beneficiaries/jouve_backend.py, src/pcapi/domain/beneficiary_pre_subscription/beneficiary_pre_subscription.py, src/pcapi/domain/beneficiary_pre_subscription/beneficiary_pre_subscription_exceptions.py, src/pcapi/domain/beneficiary_pre_subscription/beneficiary_pre_subscription_fraud_validator.py, src/pcapi/use_cases/create_beneficiary_from_application.py, src/pcapi/workers/beneficiary_job.py, tests/connectors/beneficiaries/beneficiary_jouve_repository_test.py, tests/domain_creators/generic_creators.py, tests/use_cases/create_beneficiary_from_application_test.py, tests/workers/beneficiary_job_test.py
**Besoins**
+ ajout logs create beneficiary from application pour savoir si l'import a échoué ou créé un utilisateur
+ màj des règles de fraude
+ bypass la validation de la fraude si on relance à la main l'import du dossier (suite à un KO abusif)
=> (PC-8597) update jouve fraud detection

src/pcapi/domain/beneficiary_pre_subscription/beneficiary_pre_subscription_fraud_validator.py
the extra args to the logging message must be JSON serializale.
=> (PC-8597) : fix fraud detection logging message

src/pcapi/routes/native/v1/bookings.py
We noticed quite some 400 error code on the native booking route
and have no way to figure what is wrong with the bookings.
This adds some log to understand what's going on.
=> (PC-8923) : log why booking could not be performed

src/pcapi/routes/native/v1/serialization/account.py, tests/routes/native/v1/account_test.py
Temporary fix - this should be reverted later.
=> (PC-8941) : expose needsToFillCulturalSurvey=False to all users

src/pcapi/alembic/versions/20210517_865dbe4bec27_force_phone_validation.py, src/pcapi/alembic/versions/20210520_c83abec806af_offer_ranking_weight.py, src/pcapi/alembic/versions/20210521_5d6f3407546c_add_is_used_to_token.py, src/pcapi/alembic/versions/20210521_e442fb5ac4e6_feature_disable_booking_recap.py, src/pcapi/alembic/versions/20210524_9908a2709641_add_idx_offer_validation.py
historique de la pr vs v135.10.1:
```
8bdc4df58856 -> 9908a2709641 (head), add_idx_offer_validation |	0fe847be8089 -> 2c062a40154e (head), add_author_to_offer
ae87394773a0 -> 8bdc4df58856, Add ENABLE_NEW_VENUE_PAGES feat <
e63d336e9da8 -> ae87394773a0, remove_WEBAPP_PROFILE_PAGE_feat <
e7a7fdd9c4e1 -> e63d336e9da8, populate_provider_prices_in_cen <
40afbb732e70 -> e7a7fdd9c4e1, Add `Provider.pricesInCents`    <
97553c40978d -> 40afbb732e70, Remove activity-related _trigge <
2c062a40154e -> 97553c40978d, drop_if_exists_User_canBookFree <
865dbe4bec27 -> 2c062a40154e, add_author_to_offer	      <
0fe847be8089 -> 865dbe4bec27, add_feature_flag		      <
6999a11484ba -> 0fe847be8089, feature enable idcheck fraud co	6999a11484ba -> 0fe847be8089, feature enable idcheck fraud co
5d6f3407546c -> …
```
=> (PC-8952) : reorder migrations so we can move smoothly forward

src/pcapi/core/users/api.py, src/pcapi/core/users/exceptions.py, src/pcapi/domain/user_activation.py, src/pcapi/routes/native/v1/account.py, src/pcapi/routes/webapp/beneficiaries.py, src/pcapi/scripts/beneficiary/remote_import.py, tests/routes/native/v1/account_test.py, tests/routes/webapp/phone_validation_test.py
Sur `/validate_phone_number` (webapp et native), l'utilisateur devient bénéficiaire si tous les critères sont remplis.
=> (PC-8467) validate phone number -> beneficiary

src/pcapi/routes/native/v1/account.py, src/pcapi/routes/native/v1/authentication.py, src/pcapi/routes/native/v1/serialization/account.py, src/pcapi/routes/native/v1/serialization/authentication.py
This will help the front to figure out whether or not a token
is expired and should be renewed or not.
=> (PC-8956) : return ID-Check token expiration whenever possible

src/pcapi/admin/custom_views/suspend_fraudulent_users.py, src/pcapi/core/bookings/api.py, src/pcapi/core/users/api.py, src/pcapi/core/users/constants.py, src/pcapi/routes/native/v1/account.py, src/pcapi/scripts/suspend_fraudulent_beneficiary_users.py, src/pcapi/scripts/suspend_fraudulent_pro_users.py, tests/core/users/test_api.py, tests/routes/native/v1/account_test.py
=> (PC-8934) native: Allow user to suspend their own account

src/pcapi/routes/native/v1/authentication.py, src/pcapi/routes/native/v1/serialization/authentication.py
1. parameter missing from Pydantic model
2. use camel_case
=> (PC-8116) fix: needs_to_validate_phone

src/pcapi/admin/custom_views/beneficiary_user_view.py, src/pcapi/admin/custom_views/pro_user_view.py, tests/admin/custom_views/beneficiary_user_view_test.py
Rendu pour la liste des bénéficiaires (nouvelle colonne "Dépôt valable ?" à droite) :
=> (PC-8868) admin: Modifications sur la page des pros et la page des bénéficiaires

src/pcapi/flask_app.py
Currently, flask_limiter registers its "before_request" callback
before ours. If it raises a RateLimitExceeded exception, our own
callback is not called. Thus, `g.request_start` is not set and an
AttributeError is raised in our "after_request" callback.
If we register our "before_request" callback before others, we're sure
that it will be called.
Also, register our after_request callback first so that it will be
called last (sic).
=> (PC-8729) Register our before_request and after_request callbacks first

src/pcapi/core/users/api.py, src/pcapi/routes/native/v1/account.py, src/pcapi/routes/native/v1/authentication.py, src/pcapi/routes/native/v1/serialization/account.py, src/pcapi/routes/native/v1/serialization/authentication.py, tests/core/users/test_api.py, tests/domain/user_emails_test.py, tests/routes/native/v1/account_test.py, tests/routes/native/v1/authentication_test.py, tests/routes/webapp/post_id_check_application_update_test.py
the frontend will use this endpoint instead of returning info in other endpoints like "/validate_email" or "/validate_phone_number"
=> (PC-9024) Add /next_beneficiary_validation_step endpoint

src/pcapi/admin/custom_views/offer_view.py
Approuver ou rejeter plusieurs offres en même temps depuis la liste de la vue admin Validation
- Ajout d'`actions` dans la `ValidationView`
=> (PC-9240) admin: edit validation from ValidationView list

src/pcapi/admin/custom_views/mixins/suspension_mixin.py, src/pcapi/admin/custom_views/offer_view.py, src/pcapi/admin/custom_views/venue_provider_view.py, src/pcapi/admin/custom_views/venue_view.py
(Also, clean up our use of Markup.)
Credit goes to Aethlios who responsibly disclosed this vulnerability.
=> (PC-9311) admin: Fix XSS vulnerabilities in offer validation view

src/pcapi/domain/admin_emails.py, src/pcapi/scripts/payment/batch_steps.py, src/pcapi/utils/mailing.py, tests/domain/admin_emails_test.py, tests/emails/payment_reports_test.py, tests/scripts/payment/batch_steps_test.py
=> (PC-9228) payments: Remove ERROR payments CSV attachment from report email

src/pcapi/alembic/versions/20210607_2a4bf5f4d9c2_validate_update_payment_constraint.py, src/pcapi/alembic/versions/20210607_558aec8c0580_update_payment_constraints.py, src/pcapi/alembic/versions/20210607_b74c334c8095_add_payment_custom_reimbursement_rule_id.py, src/pcapi/alembic/versions/20210607_d93ff67e391f_add_custom_reimbursement_rule.py, src/pcapi/core/offers/api.py, src/pcapi/core/offers/validation.py, src/pcapi/core/payments/factories.py, src/pcapi/core/payments/models.py, src/pcapi/domain/payments.py, src/pcapi/domain/reimbursement.py, src/pcapi/models/__init__.py, src/pcapi/models/payment.py, src/pcapi/scripts/payment/batch_steps.py, tests/core/offers/test_validation.py, tests/core/payments/test_models.py, tests/domain/payments_test.py, tests/domain/reimbursement_test.py, tests/scripts/payment/generate_new_payments_test.py
Commits à relire séparément. Cf. ticket Jira pour le contexte.
=> (PC-9232) Permettre des règles de remboursement personnalisé

src/pcapi/domain/payments.py, src/pcapi/repository/payment_queries.py, tests/domain/payments_csv_test.py, tests/domain/payments_test.py
=> (PC-9229) Ajout et suppression de champs dans les fichiers CSV de paiement

src/pcapi/admin/custom_views/offer_category_view.py
Modifier quelques éléments d'UI de 2 vues FA:
- ajout de boutons d'export CSV
- affichage des colonnes en vue liste
- affichage de noms de colonnes
=> (PC-8283) admin: tweak OfferSubcategoryView and OfferCategoryView

src/pcapi/routes/adage/v1/__init__.py, src/pcapi/routes/adage/v1/educational_institution.py, src/pcapi/routes/adage/v1/prebooking.py, src/pcapi/routes/adage/v1/serialization/educational_institution.py, src/pcapi/routes/adage/v1/serialization/prebooking.py
Points à challenger : 
- les noms PreBookings et School
- l'endopint get prebookings en mode ressource REST nestée (dont l'implem est pas forcément tiptop, quand on passera à Flask 2 on aura les blueprint nestés probablement faits pour ça 👍 )
=> (PC-9305): Swagger pour ADAGE

src/pcapi/alembic/versions/20210614_0affae55cf74_add_beneficiary_fraud_result_table.py, src/pcapi/core/fraud/factories.py, src/pcapi/core/fraud/models.py, src/pcapi/models/__init__.py
First draft to add BeneficiaryFraudResult
=> Add fraud models

src/pcapi/alembic/versions/20210614_aaad66e34f30_add_app_search_feature_flags.py, src/pcapi/models/feature.py, src/pcapi/routes/native/v1/serialization/settings.py, src/pcapi/routes/native/v1/settings.py, tests/routes/native/v1/settings_test.py
Commits à relire indépendamment, j'en ai profité pour faire une petite
optimisation dans la route "/settings" pour l'app native.
=> (PC-9381) search: Add App Search-related feature flags

src/pcapi/domain/admin_emails.py, src/pcapi/domain/payments.py, src/pcapi/repository/payment_queries.py, src/pcapi/scripts/payment/batch.py, src/pcapi/scripts/payment/batch_steps.py, src/pcapi/templates/mails/payments_report_email.html, src/pcapi/templates/mails/payments_xml_email.html, src/pcapi/utils/mailing.py, tests/domain/payments_test.py, tests/emails/payment_reports_test.py, tests/repository/payment_queries_test.py, tests/scripts/payment/batch_steps_test.py
=> (PC-9230) Paiements : envoi par mail d'un fichier CSV des lieux remboursés

src/pcapi/connectors/user_profiling.py, tests/connectors/user_profiling_test.py
- use json arguments instead of plain http query params 
- fix enums value instead of using symbol names 
- fix reason code returns when the score is not low
=> PC-9256 : a few fixes after some tests on the API 

src/pcapi/connectors/user_profiling.py, src/pcapi/routes/native/v1/serialization/account.py, tests/connectors/user_profiling_test.py, tests/routes/native/v1/account_test.py
* Validate the session_id format
* Switch a few response from user profiling optionnal
=> PC-9256 : Harden the user profiling request:

src/pcapi/algolia/usecase/orchestrator.py
=> algolia: Éviter une requête au Redis et meilleur log pour l'utilisation du hashmap "indexed_offers"

src/pcapi/emails/user_document_validation.py, tests/core/users/test_api.py
Before: if error code is unknwon -> error
After: if error code is unknwon -> use default handler
=> (PC-9650) use default email data handler

src/pcapi/scripts/beneficiary/remote_import.py, tests/scripts/beneficiary/remote_import_test.py
A few cleanups to increase script readability, and use python common way of patching imports
=> remote_import: correctly patch functions

src/pcapi/routes/native/v1/favorites.py
On a regular basis, the native application sends favorite creation
request on a very short time interval, like in less than 5ms.
This gracefully handles integrity errors whenever one happens.
=> (PC-9333) : graceful return when concurrent favorite creation happens

src/pcapi/repository/reimbursement_queries.py, src/pcapi/routes/serialization/reimbursement_csv_serialize.py, tests/repository/reimbursement_queries_test.py, tests/routes/pro/get_reimbursements_csv_test.py, tests/routes/serialization/reimbursement_csv_test.py
jira: https://passculture.atlassian.net/browse/PC-5232
=> [PC-5232] Reimbursement csv: only return "SENT" payments

src/pcapi/admin/base_configuration.py, src/pcapi/core/users/models.py, tests/admin/base_configuration_test.py, tests/core/users/test_models.py
Create a user `is_super_admin` to use it in template for instance.
=> users: add is_super_admin method

src/pcapi/core/fraud/api.py, tests/core/fraud/test_api.py
Explained in PC-9703. Also refer to commit
4f7c70f7ea40ea2bc53a43d36d64a8b6cc90e6e0
=> (PC-9270) : Strict IDCheck security checks are now "soft"

src/pcapi/utils/mailing.py, tests/emails/user_wallet_balance_test.py, tests/scripts/payment/batch_steps_test.py, tests/scripts/payment/batch_test.py
The CSV file is getting too big to be sent through Mailjet, which has
a 15Mb limit.
=> (PC-9463) payments: Compress "wallet balance" e-mail attachment

src/pcapi/admin/custom_views/fraud_view.py, src/pcapi/connectors/beneficiaries/jouve_backend.py, src/pcapi/core/bookings/api.py, src/pcapi/core/bookings/conf.py, src/pcapi/core/bookings/validation.py, src/pcapi/core/fraud/api.py, src/pcapi/core/offers/api.py, src/pcapi/core/users/api.py, src/pcapi/domain/beneficiary_pre_subscription/beneficiary_pre_subscription_validator.py, src/pcapi/emails/beneficiary_booking_confirmation.py, src/pcapi/emails/offerer_booking_recap.py, src/pcapi/infrastructure/repository/beneficiary/beneficiary_pre_subscription_sql_converter.py, src/pcapi/models/feature.py, src/pcapi/repository/feature_queries.py, src/pcapi/routes/native/v1/account.py, src/pcapi/routes/native/v1/authentication.py, src/pcapi/routes/native/v1/bookings.py, src/pcapi/routes/pro/bookings.py, src/pcapi/routes/pro/reimbursements.py, src/pcapi/routes/serialization/offers_serialize.py, src/pcapi/routes/webapp/bookings.py, src/pcapi/scheduled_tasks/decorators.py, src/pcapi/scripts/beneficiary/send_mail_after_idcheck_outage.py, src/pcapi/scripts/payment/batch.py, src/pcapi/utils/feature.py, tests/core/testing/tests.py, tests/models/feature_test.py, tests/repository/feature_queries_test.py, tests/routes/webapp/get_bookings_test.py
Goal : simplify the use of FeatureToggle and avoid an import.
Before:
`feature_queries.is_active(FeatureToggle.NEW_ACTIVABLE_FEATURE)`
Now:
`FeatureToggle.NEW_ACTIVABLE_FEATURE.is_active()`
=> featuretoggle: Simplify API to guess if a feature is active or not

requirements.txt, src/pcapi/routes/serialization/stock_serialize.py, src/pcapi/serialization/utils.py, tests/routes/pro/post_venue_stocks_test.py
Erreur de débutant 🙈 
J'ai upgrade pydantic pour avoir le nouveau type il est récent
Et le nouvelle version intègre un fix de sécurité donc c'est pas plus mal
=> (PC-9947): Correct null stock in stock api

src/pcapi/routes/native/v1/offers.py, src/pcapi/routes/native/v1/serialization/offers.py, tests/routes/native/v1/offers_test.py
**Besoin**
Fournir une route qui renvoie la liste des signalements d'offres d'un utilisateur.
=> (PC-9480) get user's reported offers

src/pcapi/repository/reimbursement_queries.py, src/pcapi/routes/serialization/reimbursement_csv_serialize.py, tests/repository/reimbursement_queries_test.py, tests/routes/pro/get_reimbursements_csv_test.py, tests/routes/serialization/reimbursement_csv_test.py
This reverts commit b89c8f0f1cdfb7177ad9a4155adeb77c371545e8.
====
La requette est bien trop long et trop complexe à hotfixe.
https://passculture.atlassian.net/browse/PC-9904
=> Revert "[PC-5232] Reimbursement csv: only return "SENT" payments"

.env.production, src/pcapi/core/search/backends/appsearch.py, tests/core/search/test_backend_appsearch.py
=> App Search : Pas de stockage Redis des offres indexées dans App Search + activation du double run sur la prod

src/pcapi/domain/beneficiary_pre_subscription/beneficiary_pre_subscription_validator.py, tests/use_cases/create_beneficiary_from_application_test.py
This regression is introduced by PC-9862
=> (PC-10010): Fix unhandled condition on bodyPieceNumberCtrl

tests/notifications/push/user_attributes_updates_test.py
The last_booking_date has also to take cancelled booking in consideration
=> (PC-9959) Fix flaky test

tests/routes/pro/validate_offerer_test.py
Cf ce fail https://app.circleci.com/pipelines/github/pass-culture/pass-culture-api/8856/workflows/106d10ec-fe70-4b3d-90ba-6eb1249554aa/jobs/20735/tests#failed-test-0
=> Fix flaky validate_offerer_test

src/pcapi/core/bookings/models.py, src/pcapi/core/search/backends/appsearch.py, src/pcapi/scripts/setup_app_search.py, tests/core/search/test_serialize_appsearch.py
- nouveau champ `group`
- changement du champ `venue_position`
- configuration des synonymes
- correction de la désindexation (en cas de grand nombre de documents)
- implémentation du vidage total des documents indexés
=> search: Diverses modifications pour App Search

src/pcapi/core/offerers/api.py, src/pcapi/core/offerers/factories.py, src/pcapi/core/offerers/models.py, src/pcapi/core/users/factories.py, src/pcapi/core/users/models.py, src/pcapi/domain/password.py, src/pcapi/utils/crypto.py, src/pcapi/utils/requests.py, tests/core/users/test_users_sql_entity.py, tests/routes/native/v1/authentication_test.py, tests/routes/pro/post_offerer_api_key_test.py, tests/utils/crypto_test.py
=> ApiKey.check_secret ; renommage d'un argument de fonction dépréciées par urllib3 ; trucs divers que j'ai vu en passant ;)

src/pcapi/core/fraud/api.py, tests/core/fraud/test_api.py
**Besoin**
Retour PO : faire en sorte de ne pas avoir la même raison (FraudResult.reason) qui se répète lorsqu'un utilisateur essaie la même opération encore et encore (par exemple demander recevoir un sms alors qu'il a déjà dépassé la limite). Le but est d'avoir un historique des actions, mais sans avoir de spam.
On ne veut plus voir :
> Le nombre maximum de sms envoyés est atteint ; Le nombre maximum de sms envoyés est atteint ; Le nombre maximum de sms envoyés est atteint
mais 
> Le nombre maximum de sms envoyés est atteint
Et si différentes raisons interviennent, on veut quelque chose comme : 
> Le nombre maximum de sms envoyés est atteint ; Le numéro saisi est interdit ; Le nombre maximum de sms envoyés est atteint
=> (PC-9793)[UPDATE] do not repeat reason

src/pcapi/use_cases/create_beneficiary_from_application.py, tests/use_cases/create_beneficiary_from_application_test.py
Objectif : Corriger une erreur qui peut apparaître dans sentry
=> (PC-10098) Fix Jouve Exception Handling

helm/pcapi/values.production.yaml
Objectif: ajout des configuration necessaires pour faire fonctionner l' User Profiling
=> PC-10116: Define User profiling configuration in production

src/pcapi/routes/native/v1/__init__.py, src/pcapi/routes/native/v1/offerers.py, src/pcapi/routes/native/v1/serialization/offerers.py, tests/routes/native/v1/offerers_test.py
Ajouter une route (app native uniquement) qui renvoie les informations de base d'un lieu.
=> (PC-10032) add new native route /venue/<venue_id>

src/pcapi/connectors/beneficiaries/jouve_backend.py, src/pcapi/core/fraud/api.py, tests/core/fraud/test_api.py, tests/routes/webapp/post_id_check_application_update_test.py, tests/use_cases/create_beneficiary_from_application_test.py
The only possible value for some validable fields are "OK" and must be filled by jouve.
=> PC-10119 : Correctly validate jouve response

src/pcapi/admin/base_configuration.py, src/pcapi/admin/custom_views/fraud_view.py, src/pcapi/core/users/models.py, src/pcapi/templates/admin/fraud_details.html, tests/admin/custom_views/fraud_view_test.py, tests/core/users/test_models.py
Objectif : Permettre au support de pouvoir manuellement valider un n° de téléphone
=> (PC-10083) : Allows support to manually validate a user phone number

src/pcapi/workers/synchronize_stocks_job.py
More and more actors are using the api, we need to be able to measure 
and analyze this use.
=> [TECH]: Add a log to monitor api stock

src/pcapi/domain/user_emails.py, src/pcapi/emails/beneficiary_activation.py, src/pcapi/scripts/beneficiary/send_dms_application_emails.py, tests/scripts/beneficiary/test_send_dms_application_emails.py
**Besoin**
1. retrouver les utilisateurs associés à certains dossier Jouve ;
2. leur envoyer un email les invitant à terminer leur inscription via DMS.
=> (PC-10133) scipt: send dms emails to users

src/pcapi/workers/update_all_venue_offers_email_job.py, src/pcapi/workers/update_all_venue_offers_withdrawal_details_job.py
job decorator change since 24546cc637
jira: PC-8552 & PC-9816
[erreur sentry de reference](https://sentry.internal-passculture.app/organizations/sentry/issues/113382/?environment=staging&project=5&statsPeriod=1h)
=> [PC-8552] workers.update_all_venue_offers_*: fix decorator

src/pcapi/admin/custom_views/offer_view.py
=> (PC-10153) Auto/Optim - Ajout de filtres sur les offres FlaskAdmin

src/pcapi/templates/admin/custom_model_layout.html, src/pcapi/templates/admin/venue_offers_list.html
=> (PC-10196) Override Flask-Admin template to circumvent bootstrap 4 bug

.env.integration
This should fix deploy on integration
=> (PC-10319) : add native cors configuration for integration

src/pcapi/scripts/fill_allocine_pivot.py
also prints statements about entries that have integrity errors
=> (PC-9314) Add script to batch import allocine pivot

src/pcapi/templates/admin/custom_model_layout.html, src/pcapi/templates/admin/venue_offers_list.html
=> (PC-10196) Override Flask-Admin template for filters to circumvent bootstrap 4 bug

src/pcapi/admin/custom_views/offer_view.py
=> (PC-10421) Flask-Admin: Update offer category filters to have searchable dropdowns

src/pcapi/admin/custom_views/offer_view.py, src/pcapi/templates/admin/edit_many_offers_components/custom_list_with_modal.html
=> (PC-10154) Flask-Admin: Add bulk edit for offers

src/pcapi/core/bookings/repository.py, src/pcapi/domain/payments.py, src/pcapi/scripts/payment/batch_steps.py
=> (PC-10522) Optimisation et simplification de `find_bookings_eligible_for_payment_for_venue()`

src/pcapi/core/payments/models.py, src/pcapi/domain/reimbursement.py, tests/domain/reimbursement_test.py
=> (PC-10436) Implémentation des nouvelles règles de remboursement

src/pcapi/core/logging.py
=> (PC-9785) Log offerer id when authenticated with api key

src/pcapi/connectors/beneficiaries/id_check_middleware.py
**Fix**
Éviter des JSONDecodeError lorsque l'api externe renvoie une erreur sans JSON.
**Au passage**
Ajouter le code renvoyé dans le log.
=> (PC-fix) id check json parse: avoid JSONDecodeError

src/pcapi/domain/demarches_simplifiees.py, src/pcapi/scripts/beneficiary/remote_import.py, src/pcapi/use_cases/create_beneficiary_from_application.py, tests/routes/webapp/post_id_check_application_update_test.py, tests/scripts/beneficiary/fixture.py, tests/scripts/beneficiary/remote_import_test.py, tests/use_cases/create_beneficiary_from_application_test.py
the user should have been pre created on the app
=> DMS and Jouve validation process journey now requires an existing user

src/pcapi/alembic/versions/20210903_d324e17d5314_remove_feature_flag_search_algolia.py
Unused since pass-culture/pass-culture-browser@b9f4c71d2f4998b1e83fde8b6b424e4021ab63ca.
=> feature: Remove unused SEARCH_ALGOLIA feature flag.

src/pcapi/routes/serialization/venues_serialize.py, tests/routes/pro/get_venue_test.py
Missing from pydantic model used for GET /venues/<venue>
=> (PC-10404)[fix] add missing venue information

src/pcapi/routes/pro/venues.py, src/pcapi/routes/serialization/venues_serialize.py, tests/routes/pro/patch_venue_test.py, tests/routes/pro/post_venue_test.py
**Besoin**
PRO : ajout des nouveaux champs de lieux pour pour la création.
=> (PC-10404)[fix] update venue creation: missing fields

src/pcapi/routes/native/v1/serialization/offerers.py, tests/routes/native/v1/offerers_test.py
**Besoin**
Déplacer les informations d'accessibilité dans un objet à part afin d'avoir la même logique que les offres.
=> (PC-10032)[fix] format venue's accessibility

.github/pull_request_template.md
​
​
- Exemples : nettoyage de code, utilisation de factories, BSR
​
=> Proposition de template de pull request

.dockerignore, Dockerfile
Restaurer le fichier `Dockerfile`, supprimé par erreur dans https://github.com/pass-culture/pass-culture-api/commit/89b6a95e22644a44b6039eb74b3a83c87b02c011.
- restaurer `Dockerfile` et le remettre dans `dockerignore`
- peaufiner le `Dockerfile` en y supprimant un layer grâce à `build-essential` (merci @dzen pour la suggestion)
​
- Ces changements ont été testés dans des [pipelines](https://app.circleci.com/pipelines/github/pass-culture/pass-culture-api?branch=PC-10773-fix-Dockerfile) utilisant une configuration temporaire de circleci
​
=> (PC-10773) restore Dockerfile

src/pcapi/core/bookings/conf.py, tests/core/payments/test_api.py
=> (PC-10524) Correct expiration date if birthday is already past this year

.env.production, .env.staging
Ajout des clefs publiques d'Adage aux variables d'environnement staging et production pour qu'elles soient correctement utilisées
​
​
=> (BSR) Add adage public key path to env files

src/pcapi/admin/custom_views/venue_view.py, src/pcapi/core/offerers/api.py, src/pcapi/core/search/__init__.py, src/pcapi/core/search/backends/algolia.py, src/pcapi/core/search/backends/appsearch.py, src/pcapi/core/search/backends/base.py, src/pcapi/routes/pro/venues.py, src/pcapi/scheduled_tasks/algolia_clock.py, src/pcapi/scripts/algolia_indexing/commands.py, src/pcapi/scripts/setup_app_search.py, tests/admin/custom_views/venue_view_test.py, tests/core/offerers/test_api.py, tests/core/search/test_api.py, tests/core/search/test_backend_algolia.py, tests/core/search/test_backend_appsearch.py, tests/core/search/test_integration.py, tests/core/search/test_serialize_appsearch.py
https://passculture.atlassian.net/browse/PC-10071
- - - - - - - -
EDIT (@jeremieb-pass )
**Besoin**
Ajouter l'indexation des lieux à AppSearch
Lorsqu'un lieu est créé ou modifié : l'indexer.
Renommer certaines fonctions et méthodes dont le nom pourrait faire croire qu'elles indexent des lieux alors qu'elles ne s'ocupent que de leurs offres (cf commentaire de @dbaty plus bas).
=> (PC-10071) Venue indexation on AppSearch

src/pcapi/routes/pro/bookings.py, src/pcapi/routes/serialization/__init__.py, src/pcapi/routes/serialization/bookings_serialize.py, src/pcapi/serialization/decorator.py, src/pcapi/serialization/spec_tree.py, src/pcapi/validation/routes/users_authentifications.py
=> Revert spectree contremarque

src/pcapi/routes/adage_iframe/bookings.py, src/pcapi/routes/adage_iframe/serialization/educational_booking.py, tests/routes/adage_iframe/post_educational_booking_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-10237
Utiliser les informations données dans le token adage plutôt que devoir les récupérer dans le body
​
=> (PC-10237) Get uai code and redactor email from jwt token

src/pcapi/repository/clean_database.py
Corriger le nettoyage de la base de données avant une sandbox
=> (BSR) Clean custom reimbursement rules when cleaning whole database

src/pcapi/routes/serialization/offerers_serialize.py, tests/routes/pro/get_offerer_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-10266
Ajout de champs manquant dans le serialiser de structure
=> [PC-10266] offerer serialization: add accessibility fields

src/pcapi/repository/reimbursement_queries.py, src/pcapi/routes/pro/reimbursements.py, src/pcapi/routes/serialization/reimbursement_csv_serialize.py, tests/routes/pro/get_reimbursements_csv_test.py
=> [PC-10216] give admins access to reimbursements

src/pcapi/scripts/setup_app_search.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-10071
Indexer les lieux sur AppSearch
- changement de script​
- ajout de cron
=> (PC-10071) Indexation des lieux sur AppSearch

src/pcapi/admin/custom_views/feature_view.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-10861
(oups)
Permettre de voir et retrouver plus facilement les features flag sur l'admin.
quelques modifications dans la vue d'admin pour :
- afficher 100 résutats par defaut
- trier les flags par ordre alphabétique
- permettre de rechercher un FF.
N/A
j'ai rien coché pour voir si vous suivez.
=> Admin: improve feature flip admin page

src/pcapi/scripts/benchmark_search.py
... and fix links in table of contents (descriptions contain quotes,
which cannot be used as is within HTML attributes).
=> search (benchmark script): Highlight slow queries in table of contents

src/pcapi/core/users/repository.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-10884
---
If the user exists, we check the password by hashing it, which takes
time. With the previous implementation, we exited early when the user
did not exist. An attacker could notice the difference in response
time and use that to enumerate user identifiers.
Now we do spend time hashing the password even if the user does not
exist. The response time is now roughly the same, whether the user
exists or not.
=> users: Avoid possible user enumeration

src/pcapi/routes/serialization/offers_serialize.py, src/pcapi/routes/webapp/__init__.py, src/pcapi/routes/webapp/subcategories.py, tests/routes/webapp/get_subcategories_test.py
Ajouter un endpoint pour webapp fournissant les sous-catégories et les searchgroups
- sérialisation des `Subcategories` et `SearchGroupChoicesEnum`
=> (PC-10765) add webapp endpoint for subcategories and search groups

src/pcapi/core/educational/api.py, tests/core/educational/test_api.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-10850
​
​
=> (PC-10850) Send email on prebooking

src/pcapi/core/educational/api.py, tests/core/educational/test_api.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-10850
​
​
=> (PC-10850) Fix decimal not being serializable

src/pcapi/core/educational/api.py, tests/core/educational/test_api.py
=> (PC-10850) Add missing mailjet vars

helm/pcapi/values.production.yaml, helm/pcapi/values.staging.yaml
=> (FIX) Change adage api key secret values

src/pcapi/core/educational/api.py, src/pcapi/routes/adage_iframe/bookings.py, tests/core/educational/test_api.py
=> (FIX) Use informations from token to create institutional_redactor

src/pcapi/scripts/booking/handle_expired_bookings.py, tests/scripts/booking/handle_expired_bookings_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-10898
​
​
=> (PC-10898) Fix handle expired bookings cron

src/pcapi/core/bookings/repository.py, src/pcapi/scripts/booking/handle_expired_bookings.py, tests/scripts/booking/handle_expired_bookings_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-10898
Correction bug emnvoi email
​
​
=> (PC-10898) FIX send email to user

src/pcapi/scripts/stock/fully_sync_venue.py
Do not try to sync a provider that's not active.
=> [BSR] fix script.stock.fully_sync_venue

helm/pcapi/values.integration.yaml, helm/pcapi/values.perf.yaml, helm/pcapi/values.production.yaml, helm/pcapi/values.staging.yaml, helm/pcapi/values.testing.yaml
=> (FIX) Set get offerer by id as high latency pod

src/pcapi/core/search/backends/appsearch.py, tests/core/search/test_serialize_appsearch.py
It has been suggested that we omit fields whose value is empty. It
will use less space, and may improve search response time.
---
https://passculture.atlassian.net/browse/PC-10910
=> (PC-10910) search: Omit empty values for App Search

tests/core/search/test_serialize_appsearch.py
Since 3feeb5d16c83998a79c652ceb74, we should not index empty values.
​
​
=> (PC-10910) search: Adapt checks on empty values in App Search tests

.circleci/config.yml
Requesting a pull to pass-culture:master from pass-culture:bcz/test_disable_coveralls
Write a message for this pull request. The first block
of text is the title and the rest is the description.
=> Disable coveralls until they're back from DB maintenance

src/pcapi/core/providers/models.py, tests/routes/pro/get_venue_providers_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/https://passculture.atlassian.net/browse/PC-10372
=> [PC-10372] venue provider nb offers active offer only

src/pcapi/scripts/educational/update_educational_institutions_deposits.py, tests/scripts/educational/fixtures/update_deposits.csv, tests/scripts/educational/update_educational_institutions_deposits_test.py
=> (PC-10941) Add script to update educational institution deposits

src/pcapi/flask_app.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-10977
​
​
=> (PC-10977) use flask_saml2 utils to read certificates correctly

src/pcapi/routes/pro/bookings.py, src/pcapi/utils/rate_limiting.py
=> (BSR) Fix basic auth rate limiter logging useless errors

src/pcapi/routes/native/v1/favorites.py
Un except un peu trop large nous empêche de comprendre d'où vient cette erreur Sentry: https://sentry.internal-passculture.app/organizations/sentry/issues/153465/?environment=production&project=5&query=is%3Aunresolved&statsPeriod=14d
​
​
=> (MOB) Raise integrity error when favorite not found tu understand it

src/pcapi/routes/adage/v1/serialization/prebooking.py, tests/routes/adage/v1/get_prebookings_test.py
=> (PC-11017) Make offer description field optional

src/pcapi/routes/native/v1/offerers.py, tests/admin/custom_views/venue_view_test.py, tests/routes/native/v1/offerers_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-10071
1. Renvoyer une 404 pour les lieux non permanents demandés par l'app native : ceux-ci ne sont pas indexés et ne sont pas censés être accessibles.
2. Ajouter des tests pour vérifier qu'une modification d'un lieu sur l'interface d'administration ajoute le lieu dans la file d'attente d'indexation.
=> Pc 10071 last fixes

requirements.txt, src/pcapi/core/object_storage/__init__.py, src/pcapi/core/offerers/models.py, src/pcapi/core/offers/models.py, src/pcapi/models/has_thumb_mixin.py, src/pcapi/models/product.py, src/pcapi/sandboxes/scripts/utils/storage_utils.py, src/pcapi/utils/inflect_engine.py, src/pcapi/utils/string_processing.py, tests/core/object_storage/object_storage_test.py, tests/utils/string_processing_test.py
On n'a probablement pas besoin d'une bibliothèque pour ajouter un "s"
à 3 mots...
=> (PC-9990) Suppression de l'utilisation de la bibliothèques "inflect"

src/pcapi/tasks/cloud_task.py
We can leave the possibility to the caller to raise an exception if the metho returns None
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-10865
=> (PC-10865) Prevent from failing after enqueue_task exception

src/pcapi/routes/native/v1/serialization/bookings.py, src/pcapi/routes/native/v1/serialization/favorites.py, src/pcapi/routes/native/v1/serialization/offers.py, src/pcapi/routes/serialization/offers_serialize.py, tests/routes/native/v1/offers_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-8434
Changement de typing pour l'API native.
​
=> (PC-8434) change type of subcategoryId to enum

src/pcapi/core/bookings/api.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11008
BSR : booking est un attribut de IndividualBooking et non l'inverse (même si les deux peuvent fonctionner en raison de la backref en base)
Changement de la composition dans `offers_api.book_offer`
​
Pas de changement sur la signature de la fonction.
Voir s'il ne vaut pas mieux renvoyer un objet `IndividualBooking`
​
=> (PC-11008) BSR : change composition order - IndividualBooking depends on Booking and not the other way around

Procfile
This file was used by Scalingo. We won't need it anymore.
=> Remove useless Procfile

src/pcapi/core/search/backends/appsearch.py
Lien vers le ticket Jira : Pas de ticket
Le script d'indexation des offres crashe si la description d'une offre est null:
```
Found <Offer #1453/AWWQ> to add to index (Digital product 4...)
Traceback (most recent call last):
File "/usr/src/app/src/pcapi/scripts/setup_app_search.py", line 132, in <module>
main()
File "/usr/src/app/src/pcapi/scripts/setup_app_search.py", line 128, in main
callback()
File "/usr/src/app/src/pcapi/scripts/setup_app_search.py", line 70, in index_offers
backend.index_offers(bookable_offers)
File "/usr/src/app/src/pcapi/core/search/backends/appsearch.py", line 340, in index_offers
documents = [self.serialize_offer(offer) for offer in offers]
File "/usr/src/app/src/pcapi/core/search/backends/appsearch.py", line 340, in <listcomp>
documents = …
```
=> (AppSearch) description is nullable

src/pcapi/core/search/backends/appsearch.py, src/pcapi/scripts/benchmark_search.py, src/pcapi/scripts/setup_app_search.py, tests/core/search/test_backend_appsearch.py
Ticket [PC-11032](https://passculture.atlassian.net/browse/PC-11032).
=> (PC-11032) App Search : Utilisation d'un meta-engine + configuration de la précision

src/pcapi/routes/native/v1/serialization/offers.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-8434
Rendre un champ non optionnel (searchGroupName) pour l'api native.
=> (PC-8434) make search_group_name non optional

src/pcapi/routes/serialization/offers_serialize.py, tests/routes/pro/get_offer_test.py
=> (PC-10534): add nonhumanized id on get offer route

src/pcapi/routes/serialization/offers_serialize.py, tests/routes/pro/get_offer_test.py
=> (PC-10645): add venue booking email

src/pcapi/scheduled_tasks/CONTRIBUTING.md, src/pcapi/scheduled_tasks/algolia_clock.py, src/pcapi/scheduled_tasks/clock.py, src/pcapi/scheduled_tasks/titelive_clock.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-10863
Corriger un problème au rollback dû au manque de contexte applicatif sur le `db.session.commit()` ou `db.session.rollback()`.
=> (PC-10863) Fix update used booking cron

src/pcapi/core/bookings/factories.py, src/pcapi/domain/payments.py, tests/conftest.py, tests/domain/payments_csv_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11077
Add column to specify booking type in payment details
- Correction de la méthode `app_fixture` pour pouvoir lancer les tests sans encombre (`relation provider does not exist`)
​
=> (PC-11077) Update information in payment scripts

src/pcapi/scheduled_tasks/algolia_clock.py, src/pcapi/scheduled_tasks/clock.py, src/pcapi/scheduled_tasks/decorators.py, src/pcapi/scheduled_tasks/titelive_clock.py, tests/scheduled_tasks/clock_test.py, tests/scheduled_tasks/decorators_test.py
=> Correction des cron

src/pcapi/domain/user_emails.py, tests/domain/user_emails_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-10999
​
​
=> (PC-10999) Send cancellation mail for all users

helm/pcapi/values.production.yaml
=> (PC-11120) Fix: replace letsencrypt certificate by gandi certificate

helm/pcapi/values.production.yaml
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11151
Ajout d'un destinataire supplémentaire pour les paiements passés en production.
​
=> (PC-11151) : Add extra recipient to PAYMENTS_REPORT_RECIPIENTS

src/pcapi/validation/routes/users_authorizations.py, tests/routes/pro/get_booking_by_token_v2_test.py, tests/routes/pro/patch_booking_keep_by_token_test.py, tests/routes/pro/patch_booking_use_by_token_test.py, tests/validation/routes/users_authorizations_test.py
=> (PC-10672): change error message to validate booking

src/pcapi/core/offerers/models.py, tests/routes/native/v1/offerers_test.py, tests/routes/pro/post_venue_test.py, tests/routes/webapp/get_booking_by_id_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11153
Faire en sorte que les lieux soient non-permanents par défaut.
=> (PC-11153) Venue.isPermanent: false by default

alembic_version_conflict_detection.txt, src/pcapi/alembic/versions/20211004_5129a4e3aabb_create_subscription_messages.py, src/pcapi/core/subscription/factories.py, src/pcapi/core/subscription/models.py, src/pcapi/models/__init__.py
Message toward the user to inform about the progress of the
subscription procedure.
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11013
Ajout du model SubscriptionMessage pour informer l'utilisateur de l'avancer de son dossier bénéficiaire.
​
​
=> (PC-11013) : Add SubscriptionMessage model

src/pcapi/admin/custom_views/inapp_messages.py, src/pcapi/admin/install.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11033
Permettre de creer, modifier, visualiser les messages d'inscription
N/A.
N/A
=> (PC-11033) Afficher les messages d'inscription

src/pcapi/core/bookings/factories.py, src/pcapi/core/offers/api.py, src/pcapi/core/offers/factories.py, src/pcapi/core/offers/validation.py, src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_educational_bookings.py, tests/core/bookings/test_api.py, tests/core/educational/test_api.py, tests/core/offers/test_api.py, tests/core/offers/test_validation.py, tests/routes/adage_iframe/post_educational_booking_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-10949
​
​
=> (PC-10949) Allow educational offers to price above 300 euros

src/pcapi/core/users/api.py
Activate the BENEFICIARY_INFORMATION step for the subscription
process starting with mobile app version 1.155.1.
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-10886
=> (PC-10886) : Add BENEFICIARY_INFORMATION step with mobile app v1.155.1

src/pcapi/core/categories/subcategories.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11182
Ajout d'une nouvelle sous-catégorie "Rencontre en ligne"
​
=> (PC-11182): Add rencontre en ligne subcategory

src/pcapi/core/subscription/messages.py, src/pcapi/routes/external/users_subscription.py, tests/routes/external/user_subscription_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-10960
Enregistrer un message "InApp" lors de la reception d'une notification DMS d'un nouveau dossier déposé
N/A.
N/A.
=> (PC-10960) Add inapp User Message on DMS application received

tests/scripts/payment/batch_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11278
Vérifier que les offres numériques remboursables (barème standard) sont bien remboursées.
- Edition de test
​
- L'application du barème à une réservation numérique remboursable a déjà été testée [ici](https://github.com/pass-culture/pass-culture-api/blob/4865db4c9ff1d4edeaa6439aaf55702609d3eb0e/tests/domain/reimbursement_test.py#L92) et [ici](https://github.com/pass-culture/pass-culture-api/blob/4865db4c9ff1d4edeaa6439aaf55702609d3eb0e/tests/domain/reimbursement_test.py#L129)
=> (PC-11278) tests: edit test_generate_and_send_payments

src/pcapi/core/subscription/messages.py, src/pcapi/scripts/beneficiary/remote_import.py, tests/scripts/beneficiary/remote_import_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-10963
Générer un message pour l'afficher à l'utilisateur lorsqu'on detecte un doublon 
lors du parcours d'inscription
N/A.
N/A.
=> (PC-10963) Add subscription user message for duplicate user (DMS)

src/pcapi/core/subscription/messages.py, tests/use_cases/create_beneficiary_from_application_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-10956
Corrige le texte du message utilisateur pour se conformer aux specs
=> (PC-10956) Fix user message text

tests/routes/external/user_subscription_test.py
Aucun Jira: simple nettoyage de code: Réutilisation d'un setting defini globalement pour les tests
=> DMS: simplify tests using defined webhook token

src/pcapi/core/fraud/api.py, src/pcapi/core/fraud/factories.py, src/pcapi/core/fraud/models.py, src/pcapi/core/users/constants.py, src/pcapi/core/users/external/educonnect/api.py, src/pcapi/routes/saml/educonnect.py, tests/core/fraud/test_api.py, tests/routes/saml/educonnect_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-10370
Ajouter le règles métier pour la fraude dans le cas d'utilisateurs se connectant via Educonnect
=> [PC 10370] Add pass 15-17 fraud result

src/pcapi/admin/custom_views/beneficiary_user_view.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11414
Permettre la modification du champs needsToFillCulturalSurvey sur la vue jeunes de F.A.
(Ajout de fonctionnalités, Problèmes résolus, etcin)
=> (PC-11414) Add missing editable needsToFillCulturalSurvey field in F.A.

src/pcapi/core/users/api.py, src/pcapi/core/users/external/__init__.py, src/pcapi/core/users/models.py, src/pcapi/notifications/push/__init__.py, src/pcapi/notifications/push/backends/batch.py, src/pcapi/notifications/push/backends/logger.py, src/pcapi/notifications/push/backends/testing.py, src/pcapi/routes/native/v1/account.py, tests/routes/native/v1/account_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-7716
Lorsqu'un utilisateur IOS désactive les notifications, toutes ses informations doivent être supprimées côté Batch.
=> (PC-7716) handle notification deactivation

src/pcapi/core/categories/subcategories.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11569
Modifier les plafonds pour certains sous-catégories
- édition de `subcategories.py`
​
​
=> (PC-11569) subcategories: edit deposit attributes

.env.testauto, alembic_version_conflict_detection.txt, helm/pcapi/values.integration.yaml, helm/pcapi/values.perf.yaml, helm/pcapi/values.production.yaml, helm/pcapi/values.staging.yaml, helm/pcapi/values.testing.yaml, src/pcapi/alembic/versions/20211029T183341_7376d1cdc5a7_add_user_ine_hash.py, src/pcapi/core/fraud/api.py, src/pcapi/core/fraud/exceptions.py, src/pcapi/core/fraud/factories.py, src/pcapi/core/fraud/models.py, src/pcapi/core/subscription/api.py, src/pcapi/core/users/api.py, src/pcapi/core/users/external/educonnect/api.py, src/pcapi/core/users/external/educonnect/models.py, src/pcapi/core/users/factories.py, src/pcapi/core/users/models.py, src/pcapi/models/feature.py, src/pcapi/routes/saml/educonnect.py, src/pcapi/settings.py, tests/core/fraud/test_api.py, tests/core/subscription/test_api.py, tests/core/users/test_api.py, tests/domain/password_test.py, tests/routes/saml/educonnect_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11348
- enregistrer le INE hash sur l'utilisateur (colonne avec contrainte d'unicité)
- filtrer les INE qui ne font pas partie de la phase de test
=> (PC-11348) Add user.ineHash and filter them

src/pcapi/core/subscription/api.py, src/pcapi/routes/saml/educonnect.py, tests/core/subscription/test_api.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11545
​
​
=> (PC-11545) refactor: make create_beneficiary_import responsible to update user on success

src/pcapi/alembic/versions/20211029T083046_3be7014806b6_add_third_party_id_column_to_beneficiary_import.py, src/pcapi/alembic/versions/20211029T183341_7376d1cdc5a7_add_user_ine_hash.py, src/pcapi/alembic/versions/20211102T160639_4584c4d37792_add_thirpartyid_index.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11300
Ajout de l'index de manière concurrente pour que ça se passe bien conformément à cette doc https://www.notion.so/passcultureapp/Clarifier-les-pratiques-de-migration-de-BDD-5f8edeba57ed4a17b80c847a74def027#7ffdc1ea90bc4cca90f1903d9ba0f573
=> (PC-11300) Add index on beneficiary_import.thirdPartyId concurrently

src/pcapi/core/bookings/repository.py
The get_domains_credit could return an amount greater than what is really left if he had bookings with status null
​
​
=> (PC-11646) Fix get_bookings_from_deposit function

src/pcapi/use_cases/create_beneficiary_from_application.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11608
Corriger une exception mal logguée
=> (PC-11608) Fix logging Exception name

.env.testauto, alembic_version_conflict_detection.txt, helm/pcapi/values.integration.yaml, helm/pcapi/values.perf.yaml, helm/pcapi/values.production.yaml, helm/pcapi/values.staging.yaml, helm/pcapi/values.testing.yaml, src/pcapi/alembic/versions/20211103T151720_bf9641a0f5a8_ine_whitelist_table.py, src/pcapi/core/fraud/api.py, src/pcapi/core/fraud/factories.py, src/pcapi/core/fraud/models.py, src/pcapi/settings.py, tests/core/fraud/test_api.py, tests/core/subscription/test_api.py, tests/routes/saml/educonnect_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11637
Créer une table pour stocker les INE hashés éligibles pour la phase de test du pass 15-17
- Ajouts du modèle IneHashWhitelist 
​
- Cette table sera remplie "A la mano" après chaque déploiement (notamment en prod)
​
=> (PC-11637) Create table for hashed INE whitelist

.env.testing
=> (PC-11680) Fix educonnect identity-id in testing

src/pcapi/core/search/backends/algolia.py, tests/core/search/test_serialize_algolia.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11611
Indexation du champs 'venue.city' dans Algolia, pour l'utiliser dans l'app native.
=> (PC-11611) index venue.city in algolia

src/pcapi/scripts/bulk_update_is_synchronization_compatible_product_via_isbns.py, tests/scripts/bulk_update_is_synchronization_compatible_product_via_isbns_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11466
(Ajout d'un script qui permette de mettre à jour le champ isSynchronized pour une liste d’ISBN
=> (PC-11466): add script to update products isSynchronizationCompatible attribut

src/pcapi/core/bookings/repository.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11170
​
​
=> (PC-11170) Fix performance regression in production

requirements.txt
=> (FIX) Fix wtforms version waiting for the code fix

src/pcapi/core/bookings/repository.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11170
​
​
=> (PC-11170) Fix production performance for get_all_bookings route

src/pcapi/core/categories/subcategories.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11717
=> (PC-11717): Set is_physical_deposit to False for ABO_PRATIQUE_ART

src/pcapi/admin/custom_views/custom_reimbursement_rule_view.py, src/pcapi/core/payments/exceptions.py, src/pcapi/core/payments/validation.py
Suite à la revue des PO. Commits à relire séparément.
=> (PC-9246) Améliorations sur l'interface de gestion des règles de remboursement

src/pcapi/routes/saml/educonnect.py, tests/routes/saml/educonnect_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11764
​
​
=> (PC-11764) Change saml login response when not redirecting

src/pcapi/routes/error_handlers/generic_error_handlers.py, src/pcapi/routes/error_handlers/utils.py, tests/routes/error_handlers/generic_error_handlers_test.py
Afficher la requête SQL paramétrée au lieu d'avoir à remplacer les valeurs par celles fournies dans la partie params
​
=> (MOB) Improve Sentry database error format
