- app.py
A vérifier mais c'est possible que cela plante si la variable d'environnement n'existe pas, ce qui n'est pas terrible. Je ne sais pas le moyen le plus propre d'éviter ça ...
> Added CORS from env_file

- routes/__init__.py
- routes/occasions.py
- routes/offers.py
- utils/includes.py
occasions: c'est la route qui permet d'avoir tous les events/things de tous les offerers d'un user pro.
@arnoo 
on va merger mais ca serait bien d'optimiser encore plus la route occasions: car en gros, en parsant toutes les offers dans le code python pour recuperer les events associés, je fais à la main le fait de ne pas prendre deux fois le même events (car plusieurs offers pointent vers le meme events).
Or comme on a déjà offerers.offers dans la db en backref, on pourrait directement avoir offerers.events aussi et ca rendrait le code bcp plus performant.
> added occasions routes

- routes/offerers.py
- routes/offers.py
- routes/venues.py
- utils/includes.py
C'est plus simple côté frontend de redemander les offerers et venues bound to the user.
(plutot que des les recuperer avec user.offerers etc lors de la requete de login get user)
> Offerers venues get api

- alembic/versions/1ccdca2e1e6e_add_amount_to_booking.py
- alembic/versions/e8c43e6dc0d8_only_occasion_has_thingId_or_eventId.py
Corrige deux problèmes sur les migrations. Comme on ne les a pas encore jouées sur les serveurs, pas besoin de faire une migration corrective, on peut encore les modifier.
- à cause d'un bug, un booking avait un offerId NULL sur la base de prod. On ne peut rien en faire et la migration s'étouffait dessus → drop. On a bien ajouté la contrainte NOT NULL sur la colonne, ça n'arrivera plus.
- La migration qui remplace thingId/eventId par occasionId ne remplissait pas toutes les colonnes occasionId qu'elle créait : ça manquait dans mediation et dans recommendation.
> Fix migration for booking.amount and thingId/eventId

- routes/offerers.py
- templates/validation_email.html
- tests/utils_mailing_test.py
- tests/utils_string_processing_test.py
- utils/mailing.py
Dans le mail de validation envoyé à la création ou au rattachement d'une structure, les informations utilisateur ne sont actuellement renvoyées que pour les rattachements (validation d'un UserOfferer). Il faut les renvoyer aussi pour les créations (valdation d'un Offerer).
> 118 info user in validation email

- domain/build_recommendations.py
- models/offer.py
- models/stock.py
- recommendations_engine/offers.py
- repository/offer_queries.py
- routes/recommendations.py
- tests/12_routes_recommendations_test.py
- tests/domain_build_recommendations_test.py
- tests/score_offer_test.py
- utils/test_utils.py
Correction d'un bug de production qu'on croyait avoir fixé.
En fait, avant on ne remontait que les recommendations d'offres gratuites qu'on créait, mais on ne filtrait pas les offres existantes.
Avec cette PR, on va filtrer *toutes* les recommendations qu'on remonte (les lues, non lues, créées).
> 517 paying offers

- models/pc_object.py
Sinon, on faisait dans certains cas (signup pro par ex) un flush donc un commit des objets qui auraient du être validés.
> Disable autoflush for <object>.errors in check_and_save

- models/pc_object.py
- tests/models_pc_object_test.py
- tests/routes_stocks_test.py
- utils/date.py
Le bug venait du fait que populateFromDict, dans un patch, mettait les datetimes envoyées en json tel quel dans l'instance d'event occurence (donc comme un string). Donc si on ne changeait qu'une des deux dates, on se retrouvait à comparer des str avec des datimes.
Le fix consiste à faire en sorte que populate from dict transforme les str en datimes.
> Populate from dict deserializes strings as datetimes

- routes/offerers.py
- tests/routes_offerers_test.py
Quand un admin essayait de créer un offerer, l'envoi d'email de validation plantait parce qu'il n'y avait pas de création d'user_offerer. Vu qu'on n'a a priori pas besoin de valider les offerers créés par les admins, j'ai mis l'envoi d'email uniquement lorsque l'user n'est pas admin
> 577 error 500 when in route things and no venue

- tests/19_routes_venue_providers_test.py
added skipif to test_11_create_venue_provider - skip if open agenda is down
> Not making tests fail when open agenda is down

- domain/admin_emails.py
- domain/user_emails.py
- tests/domain_internal_emails_test.py
- tests/domain_user_emails_test.py
- tests/utils_mailing_test.py
- utils/mailing.py
venue validation email is sent to passculture-dev when feature_send_user_emails disabled, test this for venue validation confirmation email too
> [1014] [BUG] Send emails to passculture-dev instead of pass-culture for testing

- recommendations_engine/recommendations.py
- repository/recommendation_queries.py
- routes/recommendations.py
- scripts/sandbox.py
L'apparition des cartes tutos apres une deuxieme connexion n'etait pas encore au point.
Au poins d'ailleurs que Nicolas voyait sur testing que ca ne marchait pas.
Et voici je pense la raison, surement fixée ici pour flask et y aura aussi surement un fix sur webapp complementaire.
A la première connexion /decouverte de l'appli webapp, je ne sais pas bien encore si on peut y faire grand chose (à voir un fix est possible), l'appli frontend appelle DEUX fois en moins de qqes ms la route PUT /recommendations. ... Du coup on passe deux fois quasi en meme temps dans create_recommendations_for_discovery qui pour les deux appels considere que recommendation_count = 0...
Du coup on passait deux dans inser_tuto_mediations => on cree en double les cartes tutos.
Du coup on a beau dire qu'on a lue les …
> 453 [POST PO REVIEW FIX] prevent insert_tuto_mediation to create already existing tuto mediation

- scripts/interact.py
- utils/import_module.py
pratique quand on fait un 
```
pc -e testing -f <name_file> python
```
il suffit ensuite de faire:
```
>> my_module = get_imported_module(<name_file>)
```
pour avoir son module comme ça pouf pour jouer avec.
> added util fonction to upload file from path

- routes/recommendations.py
- tests/routes_recommendations_test.py
... On a besoin de cette mini route au moment du signout d'un user jeune sur webapp.
Avant de signout il doit put les cartes qu'il a lues.
C'est vrai qu 'on pourrait le faire deja avec la route PUT recommendations, mais je trouve que ca serait  un peu lourd comme appel pour juste ça.
> (PC 453) added recommendations/read route

- recommendations_engine/recommendations.py
- repository/offer_queries.py
- repository/user_offerer_queries.py
- routes/offerers.py
- routes/offers.py
- tests/repository_offer_queries_test.py
- tests/repository_user_offerer_queries_test.py
- tests/routes_recommendations_get_test.py
Le merge de pc-1364 (api) a cassé la recherche des offres sur pro.
On aurait vu ce problème lors de la MES, mais je fais tout de suite ici le fix pour eviter de l'avoir le hour même de la MES.
> (PC-1395) [MES prefixing] fix de la recherche des offres pour la routes /offers dans pro 

- recommendations_engine/recommendations.py
- repository/offer_queries.py
- routes/recommendations.py
- tests/routes_recommendations_get_test.py
- le filtre par date spécifique ne fonctionnait pas car la fonction attendait deux paramètres dans la requête :
une date 
un laps de jour (0-1)
Or la requête de la webapp ne contient pas de laps de jour.
On a a simplifié côté api
si y'a une date -> on cherche la date
si y'a un maps de jour -> c'est date du jour + laps de jour
Du coup, faudra simplifier côté webapp aussi car la résponsabilité a été géré côté api
Question mystère : et l'utc dans tout ça ?
> PC-1428 get recommandation for search by specific date param now

- routes/venues.py
- tests/routes/venues_test.py
- tests/validation_venues_test.py
- validation/venues.py
Pour faire plus safe: on va empecher de remodifier un siret quand il existe deja.
Par contre quand il existe pas, c'est bon on peut l'ajouter.
> (pC-1839) authorize to modify siret in patch venues route

- app.py
Là encore, je n'arrivais pas à lancer ce fichier dans Docker à cause de l'erreur suivante `OSError: [Errno 8] Exec format error`.
Il fallait donc ajouter le shebang en début de fichier pour que cela fonctionne.
> Ajout du shebang

- models/user.py
- sandboxes/scripts/utils/helpers.py
- tests/models/users_test.py
- tests/routes/get_user_profile_test.py
- utils/includes.py
Création de deux nouvelles propriétés permettant de rediriger les utilisateurs vers offres ou structures suivant s'ils ont déjà créé un lieu physique ou pas. Et de leur afficher des messages sur le pro en fonction de ces valeurs (hey créé un lieu !)
Par défaut, ils ont tous un lieu virtuel dans lequel ils peuvent créer une offre numérique.
> (PC-1890) add new properties hasPhysicalVenues and hasOffers to user

- .circleci/config.yml
- domain/expenses.py
- domain/favorites.py
- models/booking.py
- models/favorite.py
- models/recommendation.py
- models/user.py
- routes/bookings.py
- routes/favorites.py
- routes/recommendations.py
- routes/users.py
- tests/models/recommendation_test.py
- tests/routes/delete_favorites_test.py
- tests/routes/post_favorites_test.py
- utils/includes.py
- validation/offers.py
(Reprise de la branche pC-2139-adapted-expenses-and-booking-includes (https://github.com/betagouv/pass-culture-api/pull/719) mais pour l'appeler sour le meme nom que la branche cote webapp afin de lancer les tests end to end avec cet état d'api:) !
La pr correspondante sur webapp a besoin de deux choses:
- mettre la propriété 'expenses' comme property dans le model user pour etre plus consistent avec le reste du code
- faire en sorte que les POST et PATCH /bookings renvoie en meme temps l'objet user, pour pouvoir directement rafraichir le wallet_balance cote front ; et cela sans demander de faire une deuxieme requete get uses/current.
- faire en sorte aussi les POST et PATCH /bookings renvoie d'avantage d'informations sur l'objet recommendation : { offer { offerType } } associé au …
> (pC-2139) [A MERGER EN MEME TEMPS QUE CELLE SUR WEBAPP] recto verso booking share for all pages

- alembic/versions/284df157db6d_add_reimbursement_by_venue_feature.py
- alembic/versions/2ae0f4147390_remove_duo_offer_feature_flag.py
- alembic/versions/37ba62c7fdb3_add_favorite_feature.py
- alembic/versions/8ab840b8db67_add_qr_code_feature.py
- alembic/versions/914fef4f49ab_add_duo_offer_feature_flag.py
- alembic/versions/d4c38884d642_add_feature_table.py
- models/feature.py
- suppression de la dépendance à l'enum FeatureGoogle importée depuis le modèle Feature dans toutes les migrations
- simplification du downgrade dans la dernière migration qui supprimer la feature OFFRE_DUO : on insère et on supprimer l'énum de la table feature.
> (PC-2728) - remove duo offer from feature table

- requirements.txt
La CI était rouge car Flask appelait la dernière version de ce package.
Je l'ai donc fixé.
https://circleci.com/gh/betagouv/pass-culture-api/8363
> add werkzeug package

- recommendations_engine/recommendations.py
- repository/offer_queries.py
- routes/recommendations.py
- tests/recommendation_engine/recommendations_v3_test.py
- tests/repository/get_offers_for_recommendation_v3_test.py
- tests/routes/put_recommendations_v3_test.py
1) if user is not geolocated, return offers regardless of location. 
2) When user is geolocated but does not match iris, return only national offers
> (PC-3175) adapted recommendations/v3 for when user is not assigned to an iris

- .circleci/config.yml
- Envoyer une notification sur le channel OPS à chaque fois que le job tests-analytics échoue
> (PC-3238): Add analytic tests

- alembic/versions/2b44409d9f54_create_get_recommendable_offers_ordered_by_digital_offers.py
- alembic/versions/747f6c0639b0_create_discovery_view_v3.py
- models/__init__.py
- models/discovery_view_v3.py
- models/install.py
- repository/offer_queries.py
- sandboxes/scripts/creators/industrial/__init__.py
- scheduled_tasks/clock.py
- tests/recommendation_engine/recommendations_v3_test.py
- tests/repository/get_offers_for_recommendation_test.py
- tests/repository/get_offers_for_recommendation_v3_test.py
- tests/routes/put_recommendations_v3_test.py
L'idée est de mettre à jour la fonction SQL existante `get_recommendable_offers` avec le nouvel `ORDER BY`.
- Pour récupérer ce bout de SQL, j'ai tout simplement affiché le requête de reco v1 et fait un copié/collé (cf `_order_by_digital_offers()`);
- J'ai aussi supprimé le `PARTITION BY` ;
- J'ai repris les tests de la v1 en adaptant ;
- Il n'y a pas de feature flipping, on refera une MEP en enlevant cette fonction ;
- J'ai skipé certains tests pour les remettre par la suite ;
- J'ai ajouté une vue matérialisée pour la v3 ;
- J'ai refacto DiscoveryView pour être un peu plus POO.
Pour changer la date, changer la variable d'env END_OF_QUARANTINE_DATE puis :
````python
DiscoveryView(db.session)._create_function_get_recommendable_offers_ordered_by_digital_offers()
db.session.commit()
```
> (pC-3194) discovery view ordered by digital offers

- repository/product_queries.py
- tests/repository/product_queries_test.py
Correction d'une erreur sur le cron titelive_things qui remontait des erreurs dues à des products Null non catché suite à l'ajout d'un filtre dans une query
> (PC-3240) : Modification of query in product_queries and tests

- repository/beneficiary_import_queries.py
- repository/user_queries.py
- scheduled_tasks/clock.py
- scripts/beneficiary/old_remote_import.py
- scripts/beneficiary/remote_import.py
- scripts/interact.py
- tests/domain/user_activation_test.py
- tests/repository/beneficiary_import_queries_test.py
- tests/repository/user_queries_test.py
- tests/scripts/beneficiary/fixture.py
- tests/scripts/beneficiary/old_remote_fixture.py
- tests/scripts/beneficiary/old_remote_import_test.py
- tests/scripts/beneficiary/remote_import_test.py
L'ancienne procédure démarche simplifiée va être remplacée au profit d'une nouvelle version de cette même procédure.
Pour simplifier la suppression de l'ancienne procédure, j'ai dupliqué le code (j'ai renommé l'original `old_remote_import`) et fait les ajustements. Il suffira de supprimer tout l'ancien code "old_*" pour s'en débarasser.
Modifications essentielles sur cette PR : 
- Chaque beneficiary_import est associé à une procédure
- On relance l'import de chaque procédure a partir du dernier import associé a cette procédure ci.
- Quelques ajustements sur le format des champs
> (PC-2985): Gathering last import date by procedure

- mypy.ini
- utils/attr_dict.py
- utils/logger.py
- disallow_untyped_defs a été rapatrié dans mypy.ini pour que l'IDE puisse l'utiliser ;
- correction du logger qui générait pas mal de bruit à chaque fois que mypy scannait un fichier le contenant.
> update mypy config

- routes/serialization/bookings_recap_serialize.py
- tests/routes/serialization/bookings_recap_serialize_test.py
Il se peut qu'une date donnée soit None pour un statut de reservation. 
On ne la formate pas en chaine de caractère de date dans ces cas-là.
> (pC-3938): Serialisation de date du changement de statut de reservation, pour une reservation remboursé mais qui n'a pas de date de validation.

- app.py
- flask_app.py
- workers/decorators.py
Problème : 
Le process `worker.py` tourne avec un `app.app_context()` qui ne possède pas la config mailjet
Solution : 
Faire en sorte que ce process tourne avec un app le plus proche possible du process principal `app.py` (avec notament la config mailjet)
Implémentation : 
Malheureusement l'objet app de `app.py` ne peut pas être utilisé directement à cause d'import circulaire
La solution est d'importer l'objet app de `flask_app.py` qui comprend déjà une partie de la configuration, et d'y déplacer la configuration manquante et nécéssaire à worker.py
> (PC-3402): Worker app context

- algolia/infrastructure/builder.py
- domain/favorite/favorite.py
- models/offer_sql_entity.py
- tests/models/offer_sql_entity_test.py
- tests/routes/get_offer_test.py
- utils/includes.py
Renommer thumb_url de offer en thumbUrl pour être cohérent avec le nommage front et ne pas avoir a modifier le code de la webapp existant.
> (PC-4118): Fix thumb for offer

- .circleci/config.yml
Exemple de résumé désormais automatiquement fourni par CircleCI : https://app.circleci.com/pipelines/github/pass-culture/pass-culture-api/316/workflows/87bca590-2c17-4c66-8393-bbd2634acfb8/jobs/450/tests.
> PC-4526 : Meilleur affichage des tests en échec dans CircleCI

- domain/password.py
- models/user_sql_entity.py
- scripts/beneficiary/file_import.py
- tests/models/users_sql_entity_test.py
- tests/scripts/beneficiary/file_import_test.py
- tests/scripts/offerer/file_import_test.py
2 commits à relire individuellement (dans la même _pull request_ parce que le second dépend du premier).
Sur ma machine, `pytest tests/routes` passe de 170s à 80s. Sur Circle CI, l'amélioration n'est pas aussi notable. En fait ça semble difficile à quantifier : les 3 runs successifs de cette branche ont pris 6min38s, 5min57s et 5min41s. Le temps de run a donc l'air déjà très variable de base.
> PC-4514 et 4515 : Modifications sur le password hasher : meilleure perf en tests + correction mineure de sécurité

- .circleci/config.yml
- Dockerfile
- requirements.txt
- start-api-when-database-is-ready.sh
Now everything can be installed in a single command:
pip install -r requirements.txt
This will help with Scalingo deployments for which we don't seem to
have other manual steps where we could specifically install the
"pcapi" local package.
> requirements: Install pcapi (local) package

- .circleci/config.yml
- Dockerfile
- bin/post_compile
- requirements.txt
- start-api-when-database-is-ready.sh
This reverts commit eadf0104382f1526072b445009399da23434851e.
The "-e ." part of `pip install -r requirements.txt` failed in the
"build-container" job on CircleCI when building a Docker image,
because at that point of the Dockerfile, the source code is not
accessible from the container. Also, it was a bad idea: the Docker
image is used as part of a Docker Compose file which includes the
local version of the API through a volume. That is, it's the Docker
Compose file that installs the "pcapi" package. It should not be part
of the Docker image.
The point of the reverted commit was to fix the deployment on
Scalingo. Since we cannot include the installation of the "pcapi"
package through requirements.txt file, we should use a post-compile
hook that does just that.
(The main point here is that …
> (PC-4517) Do not include pcapi (local) package in requirements.txt

- src/pcapi/validation/routes/headers.py
Not having a "Origin" header means two things:
- The person calling the API is not on a browser (no need for CORS header validation)
- The person calling the API is on the same domain as the API itself (no need for CORS header validation since it's a same-domain call)
Hence, we should return true when no Origin Header is received
> Fix cors header validation

- src/pcapi/connectors/api_recaptcha.py
- src/pcapi/domain/beneficiary/beneficiary_licence.py
- tests/connectors/api_recaptcha_test.py
[Jira ticket](https://passculture.atlassian.net/browse/PC-4233)
Google's reCaptcha docs can be found at https://developers.google.com/recaptcha/docs/v3
This change allows us to handle the different errors that the Google API can return,
and implements stricter control over the reCaptcha v3, via the score and a check on the action.
The minimum required score is 0.5 by default, and it can be tuned via a new env variable.
> (PC-4233) Activate reCaptcha challenge for ID CHECK

- src/pcapi/models/user_sql_entity.py
Link to Jira : https://passculture.atlassian.net/browse/PC-4709
Why : we discovered that some users can have their `hasSeenTutorials` set to `None`, resulting in them not seeing the tutorials.
> [PC-4709] Webapp - Le tutoriel ne s'affiche pas lors de la première connexion sur téléphone

- .circleci/config.yml
Since some dependencies are not pinned, it's useful to know the exact
versions used on CircleCI when test failures t be reproduced locally.
> CircleCI: Show all installed Python packages

- requirements.txt
These libraries used to be pinned until 9823c24db24b1d98. They should
still be pinned (albeit lightly) to avoid uncontrolled upgrades.
-----
J'ai pris les versions utilisées par le dernier build master, que l'on connaît depuis 1b28192e8b03b3698e2fb64241b742d33ff1a08a.
> (PC-4715)  requirements: Pin Flask and SQLAlchemy

- requirements.txt
- src/pcapi/flask_app.py
- src/pcapi/routes/native/v1/authentication.py
- src/pcapi/routes/native/v1/serialization/authentication.py
```
xordoquy@mbp15dexavier api % curl -v -H "Content-Type: application/json" -X POST http://localhost/native/v1/signin -d '{"password": "user@AZERTY123", "identifier": "pctest.jeune93.has-booked-some@btmx.fr"}'
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 80 (#0)
> POST /native/v1/signin HTTP/1.1
> Host: localhost
> User-Agent: curl/7.64.1
> Accept: */*
> Content-Type: application/json
> Content-Length: 86
> 
* upload completely sent off: 86 out of 86 bytes
< HTTP/1.1 200 OK
< Server: nginx/1.19.2
< Date: Thu, 22 Oct 2020 10:04:16 GMT
< Content-Type: application/json
< Content-Length: 340
< Connection: keep-alive
< Vary: Accept-Encoding
< X-Frame-Options: SAMEORIGIN
< X-Content-Security-Policy: …
```
> (PC-4887) : JWT token auth

- src/pcapi/connectors/api_recaptcha.py
- src/pcapi/validation/routes/beneficiaries.py
- tests/connectors/api_recaptcha_test.py
- tests/routes/post_verify_id_check_licence_token_test.py
The licence_verify will crash whenever a null token is sent.
Ensure we stay on track when a token is null or empty.
> (PC-5005) : fix beneficiaries/licence_verify crash

- .circleci/config.yml
Also: do run backend tests during nightly builds.
Collecting coverage information is not free. Since we're not paying
much attention to this data for now, it makes sense to toggle coverage
only during nightly builds.
On non-nightly builds, the pytest step time is down from 150s to
90s (-40%). Also, the artefact upload step is now instantaneous since
there is nothing to upload anymore.
> ci: Toggle test coverage only in nightly builds 

- src/pcapi/repository/offer_queries.py
- tests/repository/offer_queries_test.py
... sinon on désindexe pas correctement l'offre dans Algolia.
> [PC-4973] Ignorer les stocks supprimés dans la recherche des offres expirées

- .circleci/config.yml
We will now have an exhaustive view of all failing tests, not only the
first one.
When the build was long, this behaviour may have made sense (depending
on the developer's workflow). But now that the build is relatively
short, it's not worth much to stop the build as soon as possible.
> ci: Do not stop at the first test error/failure

- src/pcapi/alembic/versions/0c6a4a8bbcdb_add_confirmation_date_to_booking.py
- src/pcapi/core/bookings/api.py
- src/pcapi/core/bookings/conf.py
- src/pcapi/core/bookings/exceptions.py
- src/pcapi/core/bookings/factories.py
- src/pcapi/core/bookings/models.py
- src/pcapi/core/bookings/validation.py
- src/pcapi/model_creators/generic_creators.py
- src/pcapi/routes/error_handlers/bookings_error_handlers.py
- src/pcapi/sandboxes/scripts/creators/helpers/sql_creators.py
- tests/core/bookings/test_api.py
- tests/core/bookings/test_validation.py
- tests/routes/bookings/get_booking_by_id_test.py
Cette PR implémente les nouvelles règles d'annulation de réservations d'événements, à savoir ajouter la condition suivante: la réservation d'événement a été faite il y a moins de 48h.
Techniquement, on remplit une nouvelle colonnne confirmationDate lors de la réservation, et on vérifie lors de l'annulation si cette date est passée.
Cela implique d'ajouter les dates de confirmation aux réservations d'événement passées, ce qui sera fait via un script, une fois la MEP passée.
Un mécanisme de fallback est en place et sera supprimé ultérieurement, lorsque les réservations seront bien mises à jour.
> (PC-4692) edit reimbursement rules

- src/pcapi/validation/routes/beneficiaries.py
- tests/routes/post_verify_id_check_licence_token_test.py
For some reason, the token can be the string "null" instead of
the null value when calling `verify_id_check_licence_token`.
Since we don't want to crash on that, `verify_id_check_licence_token`
also needs to reject calls with {"token": "null"}.
> (PC-5072) : reject token "null" on licence-verify endpoint.

- .circleci/config.yml
This will help distinguish the jobs ran in the commit and nightly workflows,
as the jobs of the commit workflow are currently automatically renamed by CircleCI `run-tests-1`
> .circleci: edit run-tests name when running in separate workflows

- src/pcapi/utils/mailing.py
- tests/emails/payment_reports_test.py
- tests/scripts/payment/batch_steps_test.py
cf. le ticket Jira pour plus de détails, ou le message de commit,
reproduit ci-dessous :
---
The "payment details" CSV file that we send by e-mail is getting too
large. The last (2020-11-03) CSV file is 12 Mb. Once base64-encoded,
it is around 16.6 Mb, which is above the 15 Mb limit set by Mailjet.
When we tried to send the e-mail with that file, we got the following
error when POSTing to Mailjet API:
Connection aborted: BrokenPipeError(32, 'Broken pipe')
It's not clear whether the error happens because of the size limit: I
could not find any reference in Mailjet documentation nor elsewhere.
But it's a good guess. :)
At least, I have been able to successfully send a zipped CSV file,
which weighted a bit more than 1 Mb.
> (PC-5077) Zipper le fichier CSV joint au mail "Détails des paiements"

- src/pcapi/flask_app.py
- src/pcapi/utils/config.py
Je ne comprends pas pourquoi mais le fait de déclarer la varialbe SENTRY_SAMPLE_RATE dans utils/config l'empêche de bien fonctionner:
> (PC-4699) Fix Sentry on non local envs by bypassing utils config file

- src/pcapi/core/bookings/validation.py
- tests/core/bookings/test_validation.py
This fixes typos in the fallback method that was called in the transition period
(before past event Bookings without confirmationDate are updated by a script)
> (PC-5160) fix booking cancellation by user

- src/pcapi/scripts/interact.py
The `ENV` environment variable may not exist. Fortunately,
`pcapi.utils.config` defines a default value. This is useful
when tests are run with a bare `pytest`.
> scripts: Fix loading of ENV setting in interact script

- src/pcapi/routes/serialization/offers_serialize.py
- tests/routes/get_mediation_test.py
- tests/routes/patch_mediation_test.py
- tests/routes/post_mediation_test.py
L'objectif de cette story est d'ajouter quelques tests préliminaires à la mise en place de Pydantic et de la nouvelle typologie de sérialisation afin de détecter d'éventuelles régressions.
> (PC-4899): Add json tests over mediation endpoints

- src/pcapi/core/bookings/factories.py
- src/pcapi/scripts/booking/update_confirmation_date_from_existing_bookings.py
- tests/core/bookings/test_factories.py
- tests/scripts/booking/test_update_confirmation_date_from_existing_bookings.py
Performance test on local DB: updated 50k Bookings in 75s
> (PC-5078) add script to update past event bookings without confirmationDate

- src/pcapi/routes/serialization/stock_serialize.py
The webapp sends data that is not used... and yet we must define the
corresponding fields in Pydantic input serializer, otherwise the input
is rejected because of the `extra = "forbid"` rule.
And clarify the FIXME so that I don't remove it too quickly again. :)
> (PC-4878) routes: Fix input validation of create_stock

- src/pcapi/scheduled_tasks/clock.py
This cron job (and the `feature_write_dashboard_enabled` function)
have been removed in 7fd505a3a61a167b08544328eae2756a5fb66fde.
> scheduled_tasks: Remove usage of deleted job

- src/pcapi/core/bookings/repository.py
Cette PR corrige mon [commit de linting](https://github.com/pass-culture/pass-culture-api/commit/99f4989739ee17b4c92432f2f1a2d0c7d485352c), qui avait été mal _rebased_ suite à la [grande refonte de `bookings`](https://github.com/pass-culture/pass-culture-api/commit/8a029af8001c1df824ba7940118ba6639611accf).
Merci @apibrac de me l'avoir signalé !
> (PC-5249) bookings: cleanup after bad rebase

- .circleci/config.yml
CircleCI stops at the first failing step. Failing at the isort or
black steps is too soon, we're probably more interested in pytest
results.
> ci: Toujours lancer pytest, même si isort ou black échoue

- src/pcapi/core/bookings/api.py
- src/pcapi/core/offers/api.py
- src/pcapi/core/testing.py
- src/pcapi/models/pc_object.py
Previously discussed and agreed in standardization meeting.
Let any class inheriting from `PcObject` be created by using
standard keyword arguments:
User(email="jon@doe", firstname="jon")
Still keeps the former creation form since it has not been cleaned
yet:
User(from_dict={"email": "jon@doe", "firstname": "jon"})
> PcObject: allow more standard instances creation

- src/pcapi/repository/clean_database.py
Otherwise the CI cannot regularly build a new database for testing.
> repository: Allow to clean the database on testing environment

- src/pcapi/core/offers/repository.py
- tests/core/offers/test_repository.py
Fix to exclude offers with only deleted stocks when filtering offers by time period
> (PC-4293) Fix to exclude offers with only deleted stocks

- src/pcapi/core/offers/api.py
- tests/core/offers/test_api.py
The edition was not possible because the backend *wrongly* detected
changes in the `beginningDatetime` field, which is not allowed to be
modified.
The patch is ugly, it MUST be cleaned up.
> (PC-5454) offers: Fix edition of stock for Allocine offers

- .gitignore
- .tyrion-config.json
- src/pcapi/routes/external/bank_informations.py
- src/pcapi/routes/pro/bookings.py
- src/pcapi/routes/pro/offerers.py
- src/pcapi/routes/pro/providers.py
- src/pcapi/routes/pro/reimbursements.py
- src/pcapi/routes/pro/signup.py
- src/pcapi/routes/pro/types.py
- src/pcapi/routes/pro/user_offerers.py
- src/pcapi/routes/pro/validate.py
- src/pcapi/routes/pro/venue_labels.py
- src/pcapi/routes/pro/venue_providers.py
- src/pcapi/routes/pro/venue_types.py
- src/pcapi/routes/pro/venues.py
- src/pcapi/routes/shared/passwords.py
- src/pcapi/routes/shared/users.py
- src/pcapi/routes/webapp/beneficiaries.py
- src/pcapi/routes/webapp/favorites.py
- src/pcapi/routes/webapp/mailing_contacts.py
- src/pcapi/routes/webapp/recommendations.py
- src/pcapi/routes/webapp/seen_offers.py
- src/pcapi/routes/webapp/signup.py
Lien du répo Tyrion avec la doc associée:
https://github.com/theodo/tyrion
Sur le projet j'utilise le mot clé `@debt` pour éviter de "polluer" le nombre de routes restantes à migrer sur le graphe d'évolution avec tous les autres `FIXME` présents pour d'autres raisons.
C'est challengeable et à terme j'aimerais qu'on track tous les commentaires de dettes pour les traiter et ne pas les laisser pourrir. 
Les commandes utilisées pour générer très rapidement les graphes:
`tyrion -p ./src`:
`tyrion -p ./src -b -e 2`:
> (PC-5243) Track routes to be migrated with Tyrion

- src/pcapi/alembic/env.py
- src/pcapi/settings.py
- Limit the lock on the database during the migration
- isolate each migration into a single transaction to limit the lock duration
> [pc xxx] secure migrations

- src/pcapi/connectors/google_spreadsheet.py
- tests/connectors/google_spreadsheet_test.py
The current version of the code fails with:
Invalid control character at: line 1 column 176 (char 175)
... when calling `json.loads()`. This is because the private key
contains newline characters, and they should be escaped in JSON.
The bug was introduced by 6a656fc05050f9a3a1e076eaf08cfa4193250246 when I removed `strict=False`.
> (PC-5567) Fix loading of PC_GOOGLE_KEY for webapp signup

- src/pcapi/settings.py
- src/pcapi/utils/mailing.py
Load tests are sending massive amount of emails through mailjet
to the dev mailing list (I think I deleted around 10K yesterday).
As we don't want to test load on Mailjet, let's just skip
the email delivery to Mailjet when `SEND_RAW_EMAIL_BACKEND` is set
to `log`.
> (PC-5408) : Allow load tests to turn off emails delivery

- src/pcapi/local_providers/local_provider.py
Bug introduced in fbe15ae.
The previous version of the code would write the image to a single
location only. For example, if `thumbCount` equaled 1 and `thumbIndex`
equaled 3, we would write only to "/ABC_3" on the file storage instead
of writing to both "/ABC_2" and "/ABC_3".
Detected by pylint.
> (PC-5580) local_providers: Fix creation of thumbnails

- src/pcapi/routes/native/v1/account.py
- src/pcapi/settings.py
Required for the validation and tests, we need to be able to create
an account with an invalide recaptacha in testing.
Let's keep the other env protected, we don't want to be spammed
with account creations elsewhere.
> (PC-4964) : Add settings to disable repatcha on the account creation

- src/pcapi/alembic/versions/bc4ad3f45b5c_fill_isemailvalidated.py
Since it appears to be taking way too long because of the related
triggers and times out during deploy, let's just empty it to get
a smooth migration and update the fields through a script.
> (FIX) : remove the migration content

- src/pcapi/alembic/versions/df15599370fd_restore_event_is_in_less_than_10_days_.py
The function was deleted in 94861d27719c776cac31b099883e9c6cc1b04b8e.
... but it is still used in staging and prod because the definition of
the `get_offer_score` SQL function has not been updated on these
environments. In other words, on staging and prod, we still need the
`event_is_in_less_than_10_days` SQL function.
We should create a new migration that updates `get_offer_score` on
staging and prod, but that warrants a thorough validation, and I am
not willing to change recommendation-related code in a patch release.
> (PC-5613) alembic: Restore event_is_in_less_than_10_days SQL function

- src/pcapi/routes/serialization/offers_serialize.py
- src/pcapi/serialization/utils.py
- tests/routes/pro/patch_all_offers_active_status_test.py
This reverts commit 18264761ec525ca0ca0c1ecca8b15e0806c77515.
We cannot safely apply this commit because some routes may send more
data than pydantic models accept. For example,
`patch_all_offers_active_status` sends a "page" field which does not
appear in the body model. The request is hence rejected by pydantic
with a 400 error code.
This field is useless and the frontend should stop sending it... But
there may be other fields and other routes with the same issue, so
let's play it safe.
> (PC-5630) Revert "Add an input base model that contains the right configuration and use it in offer serialization"

- src/pcapi/local_providers/titelive_thing_descriptions/titelive_thing_descriptions.py
They break the creation/update of products with the following
exception when SQLAlchemy prepares the SQL query:
A string literal cannot contain NUL (0x00) characters.
---
Cette fonction n'est pas testée. Je ne vois pas trop l'intérêt
d'ajouter un test unitaire de cette fonction : il serait plutôt
préférable d'écrire un test d'intégration de TiteLiveThingDescriptions,
mais c'est une tâche non négligeable pour qui ne connaît pas le code actuel.
> (PC-5649) local_providers: Ignore NUL caracters in description from TiteLiveThingDescriptions

- src/pcapi/emails/offerer_booking_recap.py
- src/pcapi/utils/mailing.py
- tests/emails/offerer_booking_recap_test.py
When created, the offer name is the same as the product name. However,
the name of the offer can be customized by the offerer. It thus makes
sense to use the (possibly customized) *offer* name in these offerer's
e-mail notifications. We already do so in other e-mail notifications.
> (PC-5206) emails: Use offer name instead of product name in offerer notifications

- src/pcapi/domain/user_emails.py
- src/pcapi/emails/beneficiary_pre_subscription_rejected.py
- tests/domain/user_emails_test.py
- tests/emails/beneficiary_pre_subscription_rejected_test.py
Directly use the email instead of passing the entire User structure
in the beneficiary rejection emails context building functions.
> (PC-5541) : beneficiary rejection mail takes more simple inputs

- src/pcapi/alembic/versions/ad5e76920552_rename_indexes.py
- src/pcapi/core/offers/models.py
- src/pcapi/models/beneficiary_import.py
- src/pcapi/models/feature.py
- src/pcapi/models/iris_france.py
Suite à cette PR, il restera à traiter:
- 7 colonnes à passer en `NOT NULL` (attention, c'est compliqué)
- une clef étrangère sur le propriétaire d'un produit
- une contrainte d'unicité sur `validationToken` dans `venue`
SQL généré par la migration:
```SQL
BEGIN;
INFO  [alembic.runtime.migration] Running upgrade df15599370fd -> ad5e76920552, Rename indexes
-- Running upgrade df15599370fd -> ad5e76920552
ALTER INDEX "idx_api_key_offererId" RENAME TO "ix_api_key_offererId";
ALTER INDEX "idx_api_key_value" RENAME TO "ix_api_key_value";
ALTER INDEX "idx_bank_information_applicationId" RENAME TO "ix_bank_information_applicationId";
ALTER INDEX "ix_status" RENAME TO "ix_email_status";;
UPDATE alembic_version SET version_num='ad5e76920552' WHERE alembic_version.version_num = 'df15599370fd'; …
```
> (PC-5508) : Realign models and database - step 2

- src/pcapi/core/bookings/repository.py
- src/pcapi/scheduled_tasks/clock.py
- src/pcapi/scripts/booking/expiry_notifications.py
- tests/scripts/booking/expiry_notifications_test.py
Cette PR ajoute 2 tâches programmées qui pour l'instant ne font pas d'envoi de mails aux bénéficiaires et offreurs, car cela sera ajouté dans une seconde PR.
On pourra néanmoins récupérer (dans les logs) le nombre de bénéficiaires/offreurs qui seraient contactés.
> (PC-5314) scheduled_tasks: notify users and offerers of daily expired bookings

- .circleci/config.yml
Afin d'accélérer les tests de qualité, nous pouvons paralléliser l'exécution de pylint via la config ou la ligne de commande.
Ce changement passe de 1 à 4 _jobs_, et l'amélioration, bien que non-linéaire, est notable (environ 3 fois plus rapide).
Comparatif de l'exécution du step `Run pylint` dans CircleCI:
* `jobs=1` : 3min41s
* `jobs=2 `: 2min4s
* `jobs=4` : 1min17s
Cela permet d'avoir une durée de _quality check_ inférieure à la durée des tests _python_.
> .pylintrc: use multiple processes

- src/pcapi/flask_app.py
- src/pcapi/settings.py
- src/pcapi/workers/worker.py
It should work out of the box by import pcapi.flask_app but I'm
quite unsure about the side effects of opening connections to
redis or others from inside the flask_app.
> (FIX) : Configure sentry for the RQ worker

- src/pcapi/routes/native/v1/blueprint.py
Spectree has a small imcompatibility with the OpenAPI 3.0.3:
Nested models are generated as `/definitions/{model}` while
no such path exists within OpenAPI 3.0.x
All models should be under `/components/schemas/`.
While this has been reported and fixed upstream with PR:
https://github.com/0b01001001/spectree/pull/91
we need to fix it while waiting the proper solution.
> (PC-5752) : fix OpenAPI 3.0.3 schema

- src/pcapi/alembic/versions/55bf0bb6c53b_add_user_isactive.py
- src/pcapi/alembic/versions/ef6ec02387a3_add_user_suspensionreason.py
- src/pcapi/core/users/api.py
- src/pcapi/core/users/constants.py
- src/pcapi/core/users/factories.py
- src/pcapi/core/users/repository.py
- src/pcapi/models/user_sql_entity.py
- src/pcapi/routes/native/v1/authentication.py
- src/pcapi/routes/shared/passwords.py
- src/pcapi/utils/includes.py
- tests/core/users/test_api.py
- tests/routes/native/v1/authentication_test.py
- tests/routes/shared/post_reset_password_test.py
- tests/routes/webapp/post_signin_beneficiary_test.py
Commits à relire séparément. Au menu :
- ajout de `User.isActive` et prise en compte lors du login et de la
demande de réinitialisation du mot de passe;
- ajout de `suspend_account()` et `unsuspend_account()` et remplissage
du nouveau champ `suspensionReason`.
---
**Important : suggestion pour la migration** : puisqu'on n'a pas encore de mécanisme de migration pré-deploiement, je propose la procédure suivante (sur staging et production) :
1. **Avant** le déploiement, créer manuellement les 2 nouvelles colonnes, et simuler (_fake_) les 2 migrations :
```sql
ALTER TABLE "user" ADD COLUMN "suspensionReason" TEXT;
ALTER TABLE "user" ADD COLUMN "isActive" BOOLEAN DEFAULT true;
UPDATE alembic_version SET version_num='55bf0bb6c53b' WHERE alembic_version.version_num = 'ad5e76920552';
```
2. …
> (PC-5799) Rationalisation de la suspension des comptes

- src/pcapi/workers/worker.py
It previously overrode the flask_app sentry initialization through
an import chain:
> (FIX) : only set sentry when worker is started directly

- src/pcapi/admin/custom_views/suspension_mixin.py
- tests/admin/custom_views/beneficiary_user_view_test.py
- tests/conftest.py
Plus un petit commit en bonus pour que clean_database fonctionne aussi
pour les tests qui échouent.
> (PC-5900) admin: Restrict account suspension/reactivation to super admins

- src/pcapi/routes/error_handlers/generic_error_handlers.py
The catchall exception handler `internal_error` also catches
werkzeug valid exceptions that should be passed as it instead of
returning them as 500.
According to the documentation:
An error handler for Exception might seem useful for changing
how all errors, even unhandled ones, are presented to the user.
However, this is similar to doing except Exception: in Python,
it will capture all otherwise unhandled errors, including all
HTTP status codes. In most cases it will be safer to register
handlers for more specific exceptions. Since HTTPException
instances are valid WSGI responses, you could also pass them
through directly.
https://flask.palletsprojects.com/en/1.1.x/errorhandling/#generic-exception-handlers
> (FIX) : Return werkzeug HTTP exception as correct HTTP response

- src/pcapi/core/bookings/api.py
- src/pcapi/core/bookings/validation.py
- src/pcapi/domain/user_activation.py
- src/pcapi/routes/pro/bookings.py
- tests/core/bookings/test_api.py
- tests/core/bookings/test_validation.py
- tests/domain/user_activation_test.py
- tests/routes/pro/get_booking_by_token_test.py
- tests/routes/pro/get_booking_by_token_v2_test.py
- tests/routes/pro/patch_booking_by_token_test.py
- tests/routes/pro/patch_booking_keep_by_token_test.py
- tests/routes/pro/patch_booking_use_by_token_test.py
- tests/routes/pro/validate_bookings_test.py
- tests/validation/routes/offers_test.py
"Activation" offers are not used anymore to create users. We now use
the admin interface instead. As such, we can remove the special
handling of such bookings in the pro-related endpoints.
> (PC-5891) pro: Remove special handling of "activation" offer bookings

- src/pcapi/routes/native/v1/offers.py
This way the api replies with a 404 instead of 500 when the path is .../offer/ABC
> (PC-5727) Enforce typing of offer-id route parameter

- src/pcapi/core/users/factories.py
- tests/admin/custom_views/beneficiary_user_view_test.py
- tests/admin/custom_views/pro_user_view_test.py
- tests/core/bookings/test_api.py
- tests/core/offers/test_api.py
- tests/core/offers/test_repository.py
- tests/core/users/test_api.py
- tests/routes/pro/delete_stock_test.py
- tests/routes/pro/get_all_bookings_test.py
- tests/routes/pro/patch_booking_by_token_test.py
- tests/routes/pro/patch_booking_keep_by_token_test.py
- tests/routes/pro/patch_booking_use_by_token_test.py
- tests/routes/pro/patch_stock_test.py
- tests/routes/pro/post_stock_test.py
- tests/routes/pro/validate_bookings_test.py
We don't have to specify `isBeneficiary=False` anymore.
> users: We can now simply say UserFactory(isAdmin=True)

- src/pcapi/routes/native/v1/serialization/offers.py
- tests/routes/native/v1/offers_test.py
Because of algolia update delay, the frontend may need to get information such as price or dates even if the stock is no longer available
> (PC-5980) Send all stocks in offer response

- src/pcapi/domain/favorite/favorite.py
- src/pcapi/infrastructure/repository/favorite/favorite_sql_repository.py
- src/pcapi/routes/serialization/favorites_serialize.py
- tests/infrastructure/repository/favorite/favorite_sql_repository_test.py
- tests/routes/webapp/get_favorites_test.py
[Ce ticket de bug](https://passculture.atlassian.net/secure/RapidBoard.jspa?rapidView=16&modal=detail&selectedIssue=PC-5929) "**ETQU** connecté sur l'onglet favoris, **quand** je clique sur un de mes favoris dont j'ai réservé un ticket, **je suis** redirigé sur la page détails de cette offre, et le prix n'apparaît pas **alors qu'il** devrait apparaître."
Lors de l'appel à la route `/favorites` un résultat contenant notamment cela est renvoyé:
```json
{
"booking": {
"id": "WQ", 
"stockId": "AHSA"
}, 
...
"offer":{
...
"stocks": [
{
"beginningDatetime": null, 
"id": "AHSA", 
"offerId": "AHVQ"
}
],
},
...
}
```
Hors sur les pages détails d'une offre (qu'on vienne de l'onglet Accueil, Recherche, Réservations ou Favoris...), on évalue le prix avec les données suivantes:
* `booking.quantity`
* …
> (PC-5929) add stock price and booking quantity to favorites route

- .circleci/config.yml
Ajout d'une notification sur #shérif lorsque le build nightly casse.
Basé sur :
- https://support.circleci.com/hc/en-us/articles/360047082992-Send-slack-notification-at-end-of-workflow
- https://github.com/CircleCI-Public/slack-orb/wiki
- https://circleci.com/blog/circleci-slack-integration/
A nécessité la création d'une application :
https://api.slack.com/apps/A01JAVCSQGH
> Add slack notification to 'shérif' channel when nightly fail

- src/pcapi/alembic/versions/f17831b0a62a_remove_enum_on_feature_name.py
- src/pcapi/models/feature.py
- src/pcapi/models/install.py
- src/pcapi/repository/feature_queries.py
- tests/models/install_test.py
- tests/repository/feature_queries_test.py
- tests/routes/serialization/reimbursement_csv_test.py
- tests/routes/webapp/signup_webapp_test.py
- tests/scripts/payment/batch_test.py
- tests/scripts/payment/generate_new_payments_test.py
- tests/test_utils.py
**Pour le déploiement :** passer la commande SQL suivante **AVANT** le déploiement en staging et en prod :
```sql
ALTER TABLE feature ALTER COLUMN "name" TYPE TEXT;
```
----
Having `Feature.name` as an SQL ENUM column makes it hard to add and
remove feature flags:
- adding one requires a lot of boilerplate code, see
a5fa86ada028d11354a73ae15f09a63e76c65431 for example.
- removing one is complex: we need to update the code before removing
the table row in the database, otherwise the previous version of the
code (that requires the feature to be there) fails. And when we
update the code (which does not have the feature flag anymore in the
Python enum), SQLAlchemy complains that the database returns a value
that is not part of the enum.
Since we rarely manipulate (write) features, the safety …
> feature: Turn Feature.name from an enum into a simpler text column

- src/pcapi/core/bookings/api.py
- src/pcapi/core/bookings/conf.py
- src/pcapi/core/bookings/exceptions.py
- src/pcapi/core/bookings/repository.py
- src/pcapi/core/bookings/validation.py
- src/pcapi/scheduled_tasks/clock.py
- src/pcapi/scripts/booking/handle_expired_bookings.py
- src/pcapi/scripts/booking/notify_soon_to_be_expired_bookings.py
- tests/scripts/booking/handle_expired_bookings_test.py
- tests/scripts/booking/notify_soon_to_be_expired_bookings_test.py
When cancelling several thousands of expiring Bookings, performance tanked so we investigated and improved the script.
Note the use of the flask-sqlalchemy function `get_debug_queries` in tests cf https://flask-sqlalchemy.palletsprojects.com/en/2.x/api/#flask_sqlalchemy.get_debug_queries
> (PC-6036) improve cancel_expired_bookings performance

- src/pcapi/routes/pro/validate.py
- tests/routes/pro/validate_user_test.py
Native application account creation added an isEmailValidated field
which was not set when creating a pro account.
> (PC-6118) : Fix pro creation

- src/pcapi/scripts/beneficiary/import_users.py
Otherwise, we get an import loop when running the script:
$ python src/pcapi/scripts/beneficiary/import_users.py
Traceback (most recent call last):
File "src/pcapi/scripts/beneficiary/import_users.py", line 8, in <module>
import pcapi.core.payments.api as payments_api
File "/path/api/src/pcapi/core/payments/api.py", line 1, in <module>
import pcapi.core.bookings.conf as bookings_conf
File "/path/api/src/pcapi/core/bookings/conf.py", line 4, in <module>
from pcapi.models.feature import FeatureToggle
File "/path/api/src/pcapi/models/__init__.py", line 5, in <module>
from pcapi.core.users.models import Token
File "/path/api/src/pcapi/core/users/models.py", line 28, in <module>
from pcapi.core.bookings.conf import LIMIT_CONFIGURATIONS
ImportError: cannot import name 'LIMIT_CONFIGURATIONS' …
> script: Work around import loop in `import_users`

- src/pcapi/alembic/versions/acbee9d1615b_drop_booking_recommandation_id_column.py
- src/pcapi/alembic/versions/b757109d4694_drop_recommendation_table.py
Le fait de ne pas commiter la transaction `alter table booking drop recommandationId` crée un deadlock si une transaction (comme ici sur user ()) demande un AccessShareLock sur booking.
(“relation 106809768” correspond à `user` et "106809562" à `booking`)
> (PC-6015) Isolate booking.recommandationId drop migration

- src/pcapi/core/testing.py
- src/pcapi/domain/beneficiary_pre_subscription/beneficiary_pre_subscription_validator.py
- src/pcapi/models/feature.py
- src/pcapi/models/install.py
- tests/domain/beneficiary/beneficiary_pre_subscription_validator_test.py
- tests/models/install_test.py
- tests/use_cases/create_beneficiary_from_application_test.py
J'introduis un nouveau *feature flag* `WHOLE_FRANCE_OPENING`. Il est probable qu'on l'active en même temps que `APPLY_BOOKING_LIMITS_V2`, mais ça ne coûte pas cher de distinguer les deux. Et ça pourrait s'avérer utile...
> (PC-6020): Introduction d'un feature flag WHOLE_FRANCE_OPENING

- src/pcapi/algolia/usecase/orchestrator.py
- tests/algolia/usecase/orchestrator_test.py
jira : https://passculture.atlassian.net/browse/PC-5511
Je ne sais pas trop si ça fixe le cas de bug exact défini dans le jira.
Mais il me semble qu'il est bon de ne pas indexer les dates non réservable, le front recherche sur `offer.date`, si on ne veux que le offre réservable à une date donnée, il ne faut pas indexer les autres.  
* Ajout d'un test qui casse avant le changement.
> [PC-5511] Do not index offer stocks when they're not bookable

- src/pcapi/admin/custom_views/criteria_view.py
- src/pcapi/alembic/versions/1efe2b3cb31c_offer_citerion_add_startdate_and_enddate.py
- src/pcapi/models/criterion.py
These informations will be use to track relation between home playlist
offers and booking.
======
jira https://passculture.atlassian.net/browse/PC-5337
-> ajouter des date de début et de fin au criterions afin que la data puisse faire le lien entre les offres mis en avant sur une periode de temps et leurs reservations.
=====
Note, j'ai pu verifier que les champs s'affichaient sur flaskAdmin.
Parcontre je n'ai pas reussi à faire tourné metabase en local pour verifier que les champs y étaient bien.
> [PC-5337] OfferCriterion: add startDate and endDate

- src/pcapi/emails/beneficiary_activation.py
- tests/emails/beneficiary_activation_test.py
Mailjet templating language does not work with booleans.
It will allow integers and strings.
Cast booleans into integers so 1 is true and 0 is false.
> (PC-6111) fix mailjet template

- src/pcapi/routes/native/v1/__init__.py
- src/pcapi/routes/native/v1/universal_links.py
- tests/routes/native/v1/universal_links_test.py
Universal links are links to the native application instead of
links to a website.
In order to make them work, the server has to provide a description
of the links and how to interprete the scheme to the native application
> (PC-6129) : Add universal links description

- src/pcapi/alembic/versions/15f7a576bd85_validate_is_cancelled_not_null_.py
- src/pcapi/alembic/versions/1739553e1d3c_add_not_null_booking_is_cancelled.py
- src/pcapi/alembic/versions/3d08d5ba9f11_drop_is_cancelled_not_null_constraint.py
- src/pcapi/alembic/versions/525b32ead72d_add_not_null_constraint_on_booking.py
Step 1: 
Add a validation constraint not valid not to lock the table - see doc https://www.postgresql.org/docs/12/sql-altertable.html#SQL-ALTERTABLE-NOTES:
> The main purpose of the NOT VALID constraint option is to reduce the impact of adding a constraint on concurrent updates. With NOT VALID, the ADD CONSTRAINT command does not scan the table and can be committed immediately.
Step 2:
Validate constraint - see doc https://www.postgresql.org/docs/12/sql-altertable.html#SQL-ALTERTABLE-NOTES
> After that, a VALIDATE CONSTRAINT command can be issued to verify that existing rows satisfy the constraint. The validation step does not need to lock out concurrent updates, since it knows that other transactions will be enforcing the constraint for rows that they insert or update; only pre-existing …
> (Pc-5508) Add not null constraint in booking.isCancelled column

- src/pcapi/alembic/versions/06a7f387d996_drop_the_mediation_without_offer_step_0.py
- src/pcapi/alembic/versions/0e2e82aa2d40_remove_check_constraint_on_mediation_offerid_step_4.py
- src/pcapi/alembic/versions/7a89c0773774_add_not_null_constraint_on_mediation_step_3.py
- src/pcapi/alembic/versions/b27d6c71fc9d_validate_check_constraint_on_mediation_step_2.py
- src/pcapi/alembic/versions/b295261d5da0_add_check_constraint_on_mediation_step_1.py
Step 0: Drop the two mediations without offer. They were used in earlier version for the first connection cards.
Step 1: Add a validation constraint not valid not to lock the table - see doc https://www.postgresql.org/docs/12/sql-altertable.html#SQL-ALTERTABLE-NOTES:
"The main purpose of the NOT VALID constraint option is to reduce the impact of adding a constraint on concurrent updates. With NOT VALID, the ADD CONSTRAINT command does not scan the table and can be committed immediately."
Step 2: Validate constraint - see doc https://www.postgresql.org/docs/12/sql-altertable.html#SQL-ALTERTABLE-NOTES
"After that, a VALIDATE CONSTRAINT command can be issued to verify that existing rows satisfy the constraint. The validation step does not need to lock out concurrent updates, since it knows …
> (PC-5508) Add not null constraint to mediation.offerId

- src/pcapi/emails/user_reset_password.py
- tests/emails/user_reset_password_test.py
Because we are good web citizens we encode the query arguments in
the urls.
> (PC-6408) : urlencode the password reset url query arguments

- src/pcapi/alembic/versions/9a2cd2388d90_create_unique_index_venue_token.py
Doc psql : 
> Adding a constraint using an existing index can be helpful in situations where a new constraint needs to be added without blocking table updates for a long time. To do that, create the index using CREATE INDEX CONCURRENTLY, and then install it as an official constraint using this syntax. See the example below.
Testé sur staging : la migration en 2 étapes est immédiate, alors que `"ALTER TABLE venue ADD UNIQUE CONSTRAINT venue (validationToken)"` prenait plus de 3 minutes...
`CONCURRENTLY` est incompatible avec une migration lancée dans une transaction.
Mais le `CREATE INDEX` est très rapide sur staging (peut-être parce qu'il n'y a que 3 token `not nulls`, et 9400 `null`).
> (PC-5508) Add unique constraint on venue.validationToken

- .circleci/config.yml
This environment variable is not used since e5c375af0ced84cf8681c4840311a54c8a655e9d.
> ci: Remove export ACTIVATION_USER_RECIPIENTS on GCP

- src/pcapi/alembic/versions/c5dbd02f35f4_add_feature_flag_parallel_.py
- src/pcapi/local_providers/provider_manager.py
- src/pcapi/local_providers/venue_provider_worker.py
- src/pcapi/models/feature.py
- src/pcapi/scripts/stock/fully_sync_library.py
- tests/local_providers/venue_provider_worker_test.py
- tests/scripts/stock/fully_sync_library_test.py
J'ai créé un _feature flag_ pour pouvoir facilement activer ou désactiver le nouveau comportement, et j'ai essayé de limiter le diff pour faciliter le cherry-pick.
----
We used to spawn Scalingo containers to parallelize operations.
Obviously, that won't work too well on Google Cloud Platform.
Spawning containers did not dramatically reduce the overall time spent
synchronizing stock. According to logs from 2021-02-02, cumulative
time spent is around 97 minutes and spawning containers only gain 20
minutes.
Thus, we now run the synchronization of TiteLive stock in a standard
way, one venue at a time.
I am a coward, so the new behaviour requires a feature flag to be
disabled: `PARALLEL_SYNCHRONIZATION_OF_VENUE_PROVIDER`. In other
words, by default the *old* behaviour is the default one. …
> (PC-6627) providers: Do not spawn Scalingo containers when importing TiteLive stock

- src/pcapi/alembic/versions/85adf538245f_add_feature_flag_enable_whole_venue_.py
- src/pcapi/local_providers/local_provider.py
- src/pcapi/models/feature.py
- src/pcapi/scheduled_tasks/algolia_clock.py
- tests/local_providers/titelive_stocks_test.py
J'ai créé un feature flag pour pouvoir facilement activer ou désactiver le nouveau comportement, et j'ai essayé de limiter le diff pour faciliter le cherry-pick.
---
Previously, when synchronizing offers and stock against a provider, we
enqueued the reindexation of the *whole* venue. This is very long and
too expensive when only a few offers have been created or updated and
thus need to be reindexed.
We now ask for the reindexation of offers that have been created or
updated only.
I am a coward, so the new behaviour requires a feature flag to be
disabled: `ENABLE_WHOLE_VENUE_PROVIDER_ALGOLIA_INDEXATION`. In other
words, by default the *old* behaviour is the default one.
> (PC-6627) providers: Reindex offers within offer/stock synchronization

- src/pcapi/core/bookings/api.py
We already reindex when the booking is cancelled by the *beneficiary*,
but it was not done when the *offerer* cancelled.
> bookings: Reindex offer when a booking is cancelled by offerer

- src/pcapi/alembic/versions/7994bf86faea_create_unique_constraint_venue_token_2.py
Cette migration ne doit pas être jouée dans le même déploiement que la migration 9a2cd2388d90.
A merger à partir de jeudi 4/1.
> (PC-5508) Add unique constraint on venue.validationToken (step 2/2)

- src/pcapi/local_providers/local_provider.py
- tests/local_providers/titelive_stocks_test.py
This issue was tricky. Null prices were fixed BUT for existing stocks
there was some strange integrity error risen when the error log was
added in the DB.
It turns out that the stock is being modified then validated.
The validation fails and the backend inserts a message in the DB
about the failure.
HOWEVER when inserting the message a commit happens and since the
stock was modified SQLAlchemy assumes the stock is meant to be
commited.
Because the stock did not meet the validation requirements it also
fails the DB constraints (null price is not allowed) and thus an
integrity is risen.
I HATE implicit actions with SQLAlchemy
So in order to prevent thos cases, I need to EXPLICITLY remove the
stock from the session by expiring it.
Associated Sentry: …
> (PC-6807) : Fix null prices for existing stocks

- src/pcapi/core/testing.py
- src/pcapi/models/feature.py
- tests/core/bookings/test_api.py
- tests/core/bookings/test_validation.py
- tests/core/offers/test_api.py
- tests/core/testing/tests.py
- tests/domain/beneficiary/beneficiary_pre_subscription_validator_test.py
- tests/local_providers/titelive_stocks_test.py
- tests/local_providers/venue_provider_worker_test.py
- tests/routes/webapp/signup_webapp_test.py
- tests/scripts/payment/batch_test.py
- tests/use_cases/create_beneficiary_from_application_test.py
2 classes de test décorées avec `override_features` n'étaient pas
détectées par pytest, donc des tests n'étaient pas exécutés.
> Corrections dans override_settings / override_features

- src/pcapi/routes/native/v1/serialization/__init__.py
- src/pcapi/routes/native/v1/serialization/account.py
- src/pcapi/routes/native/v1/serialization/authentication.py
- src/pcapi/routes/native/v1/serialization/offers.py
The default OpenAPI schema generation does not adds nullable property
to the fields defined as `Optional[...]`. This commit adds a post
schema step to insert the nullable properties to such fields.
PS: meant to replace #1819
> (PC-5915) : Native app OpenAPI schema with nullable fields

- src/pcapi/alembic/versions/2b860ecd3072_update_get_wallet_balance_function.py
- src/pcapi/core/bookings/models.py
- src/pcapi/core/payments/api.py
- src/pcapi/core/users/models.py
- tests/core/bookings/test_validation.py
The `check_booking` SQL function raises the `insufficientFunds` error
when `get_wallet_balance() < 0`. This never happens if we use
`GREATEST(0, xxx)`. As such, it would not prevent a user to book again
with an expired deposit if they had booked something in the past.
What we really want is to avoid exposing a negative deposit value, so
we'd rather do it in `User` properties.
> (PC-6752) Let get_wallet_balance SQL function return a negative number

- src/pcapi/core/users/api.py
- tests/core/users/test_api.py
This is performed by the IDCheck upfront as explained in
https://www.notion.so/Cr-ation-du-compte-ID-Check-5f04139e78f7457eb86e17ac609960ca
No need for now to rush on that check.
> (PC-6629) : temporarily remove the beneficiary age check

- src/pcapi/alembic/versions/0867450b4c30_update_check_booking_function.py
- src/pcapi/core/bookings/models.py
- src/pcapi/core/bookings/validation.py
- tests/core/bookings/test_validation.py
There were multiple bugs:
- a booking can be cancelled even if its user's deposit has
expired (i.e. even if the wallet balance is negative);
- a user whose deposit has expired (i.e. with a wallet balance that is
negative) should still be able to book free offers.
> (PC-6752) Fixes on `check_booking` after introduction of Deposit.expirationDate

- src/pcapi/core/offers/repository.py
- src/pcapi/infrastructure/repository/stock_provider/provider_api.py
- src/pcapi/infrastructure/repository/stock_provider/stock_provider_fnac.py
- src/pcapi/local_providers/fnac/fnac_stocks_provider.py
- src/pcapi/local_providers/fnac/synchronize_fnac_stocks.py
- src/pcapi/scheduled_tasks/clock.py
- src/pcapi/settings.py
- tests/local_providers/synchronize_fnac_stocks_test.py
- Précédent script : lancé en staging, connexion perdu au bout de 3h15, la synchro dure 3h50 en prod d'après kibana
- Script proposé : 6min20s en staging, lancé en deuxième peut être que ça va plus vite
=> **Test concluant**
Remarques (à challenger ?) : 
- Les dateModifiedAtLastProvider ne sont pas implémentées ni utilisées => à quel besoin elles correspondent ?
- Les attributs suivants ne sont pas implémentés ni utilisés, ils ne semblent pas avoir d'impact sur la synchronisation, est-ce normal : 
- Stock : dateModifiedAtLastProvider, lastProviderId, fieldsUpdated
- Offer : dateModifiedAtLastProvider, lastProviderId, fieldsUpdated
- Product : dateModifiedAtLastProvider, lastProviderId, fieldsUpdated
- Venue : idAtProviders, dateModifiedAtLastProvider, lastProviderId, fieldsUpdated
- Les …
> (PC-5372): Better FNAC CRON synchronization performance

- src/pcapi/emails/beneficiary_booking_cancellation.py
- src/pcapi/emails/beneficiary_warning_after_pro_booking_cancellation.py
- tests/domain/user_emails_test.py
- tests/emails/beneficiary_booking_cancellation_test.py
- tests/emails/beneficiary_warning_after_pro_booking_cancellation_test.py
These cancellation e-mails indicate whether the offer is "reimbursed"
and whether the user can book it again if it was cancelled by mistake.
This depends on whether the beneficiary is allowed to book again (i.e.
whether their deposit is still valid).
> (PC-6845) Add can_book_again to cancellation emails data

- src/pcapi/connectors/redis.py
- tests/connectors/redis_test.py
Vu dans Sentry : https://logs.passculture.app/organizations/sentry/issues/2192/
----
`rpush()` takes star arguments:
```python
def rpush(self, name, *values):
"Push ``values`` onto the tail of the list ``name``"
return self.execute_command('RPUSH', name, *values)
```
This is the kind of bug that happens when we mock too much...
Manual validation of the fix:
```pycon
>>> import redis
>>> client = redis.from_url(url=settings.REDIS_URL, decode_responses=True)
>>> # previous version, shows the bug
>>> client.rpush("offer_ids_in_error", ["1", "2"])
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/home/damien/env/pcapi/lib/python3.7/site-packages/redis/client.py", line 2016, in rpush
return self.execute_command('RPUSH', name, *values)
File …
```
> redis: Fix add_offer_ids_in_error

- src/pcapi/emails/offerer_booking_recap.py
- tests/core/bookings/test_api.py
- tests/emails/offerer_booking_recap_test.py
Add reply-to header in booking confirmation pro email and delete all other users private informations
> (PC-3666) Add reply-to header in booking confirmation pro email

- src/pcapi/alembic/versions/877b67c234f9_add_feature_flag_synchronize_venue_provider_in_worker.py
- src/pcapi/models/feature.py
- src/pcapi/routes/pro/venue_providers.py
- src/pcapi/workers/bank_information_job.py
- src/pcapi/workers/beneficiary_job.py
- src/pcapi/workers/mailing_contacts_job.py
- src/pcapi/workers/venue_provider_job.py
- src/pcapi/workers/worker.py
- tests/routes/pro/post_venue_provider_test.py
The worker is not ready to accept long running jobs like the synchronization of venue_providers.
The delegation of this task to the worker now has its own feature flip, so we can postpone
When the feature flip will be activated, the job will run on a new "low priority" worker.
This worker has to be instanciated by the ops team.
Meaning as long as this second worker is not up and running, **we shouldn't change the feature flip**
> (PC-6861): Deuxième worker pour les synchronisations

- src/pcapi/emails/user_reset_password.py
- tests/emails/user_reset_password_test.py
when switching to the universal links, the part that was used to
detect the url redirection should have been removed but was not :(
> (PC-6976) : fix password reset link in email for native app

- src/pcapi/core/testing.py
- src/pcapi/repository/feature_queries.py
- tests/repository/feature_queries_test.py
We noticed the expense computation did query several times the
feature APPLY_BOOKING_LIMITS_V2. This is done though calls to
BaseLimitConfiguration.physical_cap_applies for every user's
booking.
A quick and easy fix here is to cache the feature value inside
the request context to avoid unintended extra db queries.
Note that feature will still work outside the request context -
ie in scripts, crons, workers - but will not benefit caching.
> (PC-6975) : cache feature values when within a request context

- src/pcapi/core/mails/backends/mailjet.py
- src/pcapi/utils/requests.py
- tests/core/mails/tests.py
Pourquoi un monkey patch ? Cf. #1975.
---
Currently, HTTP requests to the Mailjet HTTP API are not logged. We
have no idea how much time these requests take. Having logs would be a
good first step before potentially making e-mail sending asynchronous.
I chose to monkey patch `mailjet_rest` because... we don't have much
choice. The code in `mailjet_rest` is not pluggable, we would have to
copy and paste a lot of code to inject our `requests` wrapper, by
redefining `Client`, `Endpoint` and `api_call`. In the end, monkey
patching is less fragile.
> (PC-6986) mails: Monkey patch `mailjet_rest` library to use our `requests` wrapper

- src/pcapi/core/users/models.py
- src/pcapi/routes/serialization/beneficiaries.py
- src/pcapi/utils/includes.py
- tests/routes/webapp/get_beneficiary_profile_test.py
- tests/routes/webapp/patch_beneficiary_test.py
This property was used by the frontend to calculate the expiration
date of the deposit. But the frontend does not do that anymore and
just uses `User.deposit_expiration` instead. As such, we don't need to
expose `User.wallet_date_created` anymore and can remove it.
> (PC-6974) users/webapp: Remove User.wallet_date_created

- src/pcapi/routes/native/v1/authentication.py
- tests/routes/native/v1/authentication_test.py
Whenever the user follows a link with an expired account creation
token, it would receive a mail for a password reset in return.
If the user follows the email's link and successfully reset its
password, we should consider the email has indeed been validated.
> (PC-6525) : validate email when user resets its password

- .circleci/config.yml
Caching the whole virtual environment directory is not a good idea for
the "master" branch. When a new version of an unpinned dependency is
released (such as pylint), the requirements file does not change, so
CircleCI reuses the cache and the old version. This is wrong. The
build should really pick up the latest version.
This commit is only a quick fix. We should think about a better
solution. An alternative might be to use a cache on master, but use
`pip --upgrade-strategy eager` to be sure to fetch the latest version
of unpinned requirements.
> ci: Do not cache requirements on "master" builds

- src/pcapi/routes/serialization/offerers_serialize.py
- tests/routes/pro/get_offerer_test.py
Ajout d'un champs qui avait disparut suite au switch entre "as_dict" et le serializer de la reponse.
cf: https://github.com/pass-culture/pass-culture-api/commit/347316604d31814382eda42ab98795e8c1f222ab
> [PC-6840] route.offerers: add missing field "demarchesSimplifieesApplicationId"

- src/pcapi/domain/booking_recap/booking_recap.py
The `booking_token` property was redefined in a way pylint lost
the track.
Refactor the property to use `_get_booking_token()` and
`_set_booking_token()`. Lambda are used here so we don't need to
redefine the property for every class that changes its behavior.
> (QA) : refactor a bit redefined BookingRecap's booking_token

- src/pcapi/connectors/google_spreadsheet.py
- src/pcapi/settings.py
- tests/connectors/google_spreadsheet_test.py
This one is base64-encoded, which is easier to work with in
configuration files.
> (PC-7171) Use new PC_GOOGLE_KEY_64 environment variable

- src/pcapi/alembic/versions/021d3f2434f0_add_on_cascade_delete_on_tokens.py
- src/pcapi/core/users/api.py
- src/pcapi/core/users/models.py
- src/pcapi/scheduled_tasks/clock.py
- tests/core/users/test_api.py
Clean the token table from expired ones.
We have no need to keep unused tokens.
Also adds a on cascade delete so that whenever a user is deleted, its tokens also are.
> (PC-6915) : Delete expired tokens

- src/pcapi/domain/user_emails.py
- src/pcapi/emails/beneficiary_activation.py
- tests/domain/user_emails_test.py
Add the link to the native application for the user notification
for its 18 years old birthday email so it can start IDcheck and
become a beneficiary.
> (PC-7219) : Add universal link to IDCheck in the 18th birthday email

- src/pcapi/utils/requests.py
This is similar to 1dfeb34897a54e691d445d80ac3db8b2356ec58e (and similarly harmless).
> utils: Allow access to requests.RequestException for mailjet_rest

- src/pcapi/emails/beneficiary_activation.py
- src/pcapi/emails/user_reset_password.py
- tests/emails/user_reset_password_test.py
Mailjet rewrites the http/https links in order to track who's clicked
the mail. However, this breaks universal links to the native application.
It is still possible to deactivate that url rewriting by sending
`Mj-trackclick` set to 1 along with the other Mailjet's headers.
> (PC-7221) : links to the native app should not be rewritten by Mailjet

- src/pcapi/utils/logger.py
D'après la doc de StreamHandler il log sur stderr par défault, ici on met stdout
MAIS
- ça ne concerne que le jsonlogger
- pas réussit à reproduire en local, les logs étaient déjà tous dans stdout
> (PC-7158): Log to stdout

- src/pcapi/admin/custom_views/beneficiary_user_view.py
- src/pcapi/admin/install.py
Partner accounts are neither admin nor beneficiary, which is why they
were listed. If we specifically filter on `isBeneficiary=True`, we'll
only get beneficiaries, without partner accounts.
> (PC-7426) admin: Do not list partner accounts in beneficiary list view

- src/pcapi/core/bookings/conf.py
- tests/core/bookings/test_validation.py
For version 1 deposits, we actually want to keep the same amount limit
for physical offers after the Big Switch.
> (PC-7427) bookings: Change expense limits for version 1 of deposits

- src/pcapi/routes/native/v1/favorites.py
- tests/routes/native/v1/favorites_test.py
Returns the favorite structure whenever one is created.
This allows the client to cache it and flag the offer as favorite
without the need to refresh the offer from the backend.
> (PC-7415) : return newly created favorite

- src/pcapi/routes/native/v1/favorites.py
- tests/routes/native/v1/favorites_test.py
Commit à relire séparément.
Le passage des favoris en factories fera l'objet d'une PR spécifique avec le renommage de `FavoriteSQLEntity` et le déplacement vers `core`.
TODO:
> (PC-7371) Apply correct price/date rules on favorite offers

- src/pcapi/admin/custom_views/booking_view.py
- src/pcapi/admin/install.py
- src/pcapi/core/bookings/api.py
- src/pcapi/core/bookings/validation.py
- src/pcapi/repository/payment_queries.py
- src/pcapi/scripts/booking/canceling_token_validation.py
- src/pcapi/templates/admin/booking.html
- src/pcapi/templates/admin/forms.html
- src/pcapi/templates/admin/search_many_offers.html
- tests/admin/custom_views/booking_view_test.py
- tests/core/bookings/test_api.py
- tests/repository/payment_queries_test.py
Sometimes a booking is cancelled by mistake or fraudulently, but it
really should be mark as used (because the offer has been retrieved
from the offerer). It cannot be done by the offerer, but we should be
able to do it from the admin.
> (PC-7191) admin: Allow to mark a cancelled booking as used

- tests/admin/custom_views/many_offers_operations_view_test.py
Some tests that involve Flask-Admin do need `clean_database()`
(perhaps those that use ModelView's?), but not all of them.
> tests: Do not use clean_database where it's not necessary

- src/pcapi/core/bookings/validation.py
- src/pcapi/core/users/api.py
- src/pcapi/core/users/models.py
- src/pcapi/routes/native/v1/serialization/account.py
- src/pcapi/routes/serialization/beneficiaries.py
- tests/core/users/test_expenses.py
- tests/routes/native/v1/account_test.py
- tests/routes/webapp/get_beneficiary_profile_test.py
- tests/routes/webapp/patch_beneficiary_test.py
Add a more solid and domain-like model of the credit : replace user.expenses: List[Expense] by get_domains_credit(user)->DomainsCredit.
This will moreover help the frontends that currently have to deal with a list instead of an object, and prevent it from repeating logics like _"is deposit exired?"_  or _"if `all`  credit is lower than `physical` credit then `physical` credit is `all`"_.
Refacto steps :
1.  add `domainsCredit` aside to `user.expenses` (this PR)
2. user `domainsCredit` in App Native and Webapp
3. remove user.expenses
> (PC-7001) Add user credits

- src/pcapi/routes/native/v1/favorites.py
- tests/routes/native/v1/favorites_test.py
Although we don't compute their price/date favorites with inactive
offers or deleted stocks should still appear.
> (PC-7035) : Do not ignore favorites with inactive offers / stocks

- src/pcapi/routes/native/v1/favorites.py
- src/pcapi/routes/native/v1/serialization/favorites.py
- tests/routes/native/v1/favorites_test.py
Flag offers that don't have any stock left as `isExhausted`.
Currently it's a pity in performance as it does a query for
each stock to get the bookings.
We'll improve that later.
> (PC-7034) : add isExhausted to favorite's offers

- src/pcapi/routes/native/v1/favorites.py
- src/pcapi/settings.py
- tests/routes/native/v1/favorites_test.py
We consider that above a given threshold (set by default to 100)
the user will not be able to manage its favorites (too many of
them).
Above that threshold, we'll return an error stating he already
have enough favorites.
> (PC-7416) : add a maximum number to the user's favorite

- src/pcapi/scripts/update_booking_used.py
- tests/scripts/update_booking_used_test.py
This function is usually called by a cron that is "protected" by a
feature flag. But it may be called manually (and it has). And we
really don't want to call it if the feature flag is deactivated.
See PC-7403 for an example.
> scripts: Make sure that `update_booking_used_after_stock_occurrence` is not called by mistake

- src/pcapi/core/logging.py
- tests/core/logging/tests.py
Ci-dessous, visualisation dans Google Cloud Logging. (Un clic sur le bouton gris clair avec des traits horizontaux gris foncés permet d'"afficher tous les journaux de cette trace", c'est-à-dire tous les logs ayant le même _correlation id_.)
Je n'arrive pas écrire des tests permettant une couverture totale du code. Il faudra ce contenter de ça.
> (PC-7668) Inclusion dans les logs d'un "correlation id" et du user_id

- src/pcapi/core/logging.py
(PC-7668) logging: Fix detection of logged-in user
I am not sure why, but we get an indirect AttributeError when trying
to access `current_request` on some log that is emitted very soon,
probably before Flask is properly initialized.
logging: Set log level of spectree logger.
It logs INFO messages that are not very useful to us:
[✓] Attribute "PATH" has been updated to "/"
[✓] Attribute "MODE" has been updated to "strict"
> ___ wip (DO NOT MERGE): build and push Docker image

- src/pcapi/alembic/versions/20210322_bd142e43ea07_add_feature_flag_offer_validation_.py
- src/pcapi/core/offers/api.py
- src/pcapi/models/feature.py
- tests/core/offers/test_api.py
Calculer et enregistrer le statut de validation d'une Offre lors de sa création
- Ajout d'une nouvelle fonction `compute_offer_validation()` qui vérifie le nom de l'Offre pour déterminer son statut de validation. Ce mécanisme est _feature flagged_, et désactivé en Production
- Mise à jour de l'`OfferFactory` pour y ajouter un _post-génération hook_ qui calcule ce statut
- Ajout d'une migration pour ce _feature flag_
Nouveau _feature flag_: `OFFER_VALIDATION_MOCK_COMPUTATION`
> (PC-7528) add a mock offer validation

- src/pcapi/admin/base_configuration.py
- src/pcapi/admin/custom_views/beneficiary_user_view.py
Super-admins should be able to see form fields for the first name and
last name when creating or editing a beneficiary (see 48883f3594e603).
It did not work because the form class (and its fields) was cached by
Flask-Admin when the admin view was registered, i.e. when there was no
logged-in user.
Not populating the form cache seemed hard (as other things in
Flask-Admin expected the cache to be there), so here we simply
override a couple of functions to avoid using the cache.
> (PC-7904) admin: Fix inclusion of first/last name in beneficiary creation/edition

- src/pcapi/core/offers/api.py
- src/pcapi/core/offers/models.py
- src/pcapi/core/offers/validation.py
- tests/core/offers/test_api.py
- tests/core/offers/test_validation.py
- tests/routes/pro/delete_stock_test.py
- tests/routes/pro/patch_all_offers_active_status_test.py
- tests/routes/pro/patch_offer_test.py
- tests/routes/pro/patch_offers_active_status_test.py
- tests/routes/pro/post_stocks_test.py
Tant qu'une offre n'a pas été validée, elle ne doit pas pouvoir être éditée, et on ne doit pas pouvoir lui créer ou ajouter de Stock.
Cela concerne également le statut Active/Inactive, dans la liste des Offres.
- Le statut de validation de l'Offre est désormais vérifié dans les différentes méthodes d'API interne d'édition d'Offre, et de création, édition et suppression de Stock.
> (PC- 7460) prevent Offer and Stock edition when Offer is not validated

- src/pcapi/core/offerers/factories.py
- src/pcapi/local_providers/generic_provider/generic_stocks.py
- src/pcapi/local_providers/provider_api/synchronize_provider_api.py
- src/pcapi/model_creators/generic_creators.py
- tests/scripts/stock/fully_sync_venue_test.py
Un rattrapage des données est nécessaire pour que la synchro fonctionne à partir de venueIdAtOfferProvider.
Voir le ticket pour les requetes SQL.
> (PC-7823): Use venueIdAtOfferProvider instead of SIRET

- src/pcapi/routes/native/v1/favorites.py
- src/pcapi/routes/native/v1/serialization/favorites.py
- tests/routes/native/v1/favorites_test.py
Flags offers that are deactivated or which venue/offerer are
deactivated or not yet validated.
> (PC-7625) : include offer `isReleased` to favorites

- src/pcapi/routes/pro/venues.py
- src/pcapi/routes/serialization/venues_serialize.py
- tests/routes/pro/get_venue_test.py
Jira: https://passculture.atlassian.net/browse/PC-7809
Cette route est utilisé à deux endroit:
* dans le formulaire de preview de l'offre afin d'afficher l'adresse du lieux. (champs utilisées : isVirtual, adresse, city, postalCode, name, publicName)
* dans la création et édition de lieu via requestData. J'ai l'impression que tout les champs sont utilisées.
> [PC-7809] Add serializer for routes.pro.venues.get_venue(venue_id)

- src/pcapi/emails/beneficiary_activation.py
- tests/emails/beneficiary_activation_test.py
Ticket Jira : https://passculture.atlassian.net/browse/PC-7882
Test unitaires ajoutés ? ✅ 
Est-ce que le code a été fait avec classe et élégance ? ✅ 
Template Mailjet associé à la PR : https://app.mailjet.com/template/2016025/build ==> Ajouter `{{var:depositAmount:"300"}}` dans le template pour utiliser la nouvelle variable `depositAmount`.
> (PC-7882) Add depositAmount variable to user eligible for credit confirmation email

- src/pcapi/core/logging.py
- src/pcapi/flask_app.py
With the previous implementation, loggers that were created before we
called `install_logging()` would not use our custom record factory. As
such, the `extra` property in the JSON log was empty. It occurred on
some (but not all) of our own loggers, and depended on the order in
which modules were imported.
An alternative would be to call `install_logging()` first on each
entry point module of the app (`flask_app.app`, `workers.worker`, each
cron module, etc.) but it's tedious.
The easy solution seems to be a monkey patch. Will I regret it?
> (PC-7924) Make sure that all loggers use our custom record factory

- src/pcapi/core/bookings/api.py
- tests/core/bookings/test_api.py
Up to now, cancelling a booking twice had no side effets.
Since the addition of the `Stock.dnBookedQuantity`, cancelling
a booking twice would affect the `Stock.dnBookedQuantity`.
Let's just skip if the booking to be cancelled is already
cancelled.
> (PC-8019) : Fix Stock.dnBookedQuantity when booking is cancelled twice

- src/pcapi/routes/native/v1/bookings.py
- src/pcapi/routes/native/v1/serialization/bookings.py
- tests/routes/native/v1/bookings_test.py
The native app bookings front expects the `externalTicketOfficeUrl`
field to be part of the response.
> (PC-8007) : Add `externalTicketOfficeUrl` to native bookings

- src/pcapi/routes/native/v1/serialization/account.py
`postalCode` will be required for native app account creation
as long as the product is restricted to some area.
Also note that it is currently flagged as optional - for now -
to avoid breaking account creation. Mandatory flag will be
added in a second step depending on the value of the
`WHOLE_FRANCE_OPENING` flag.
> (PC-7963) : Add postalCode to the native app account creation

- src/pcapi/core/users/models.py
- tests/routes/native/v1/account_test.py
Since the grand opening is postponed after the official native
application release the `eligibility_start_datetime` and
`eligibility_end_datetime` are subject to the location.
> (PC-8039) : don't set eligibility date in non eligible area

- src/pcapi/admin/custom_views/offer_view.py
- src/pcapi/core/offers/api.py
- src/pcapi/templates/admin/edit_offer_validation.html
- tests/admin/custom_views/offer_view_test.py
- tests/core/offers/test_api.py
Création d'une page Flask Admin qui permet au validateur des offres du pôle fraude d'approuver ou refuser une offre qui est en attente de validation.
La page permet d'affiche les informations nécessaires qui permettent d'analyser les offres avant d'approuver ou refuser.
> (PC-7143): Offer validation edit page flask admin

- src/pcapi/core/users/api.py
- src/pcapi/routes/native/v1/account.py
- tests/routes/native/v1/account_test.py
Make `postalCode` a mandatory field and use it to fill `postalCode`
and `departementCode` uppon user creation *if* `WHOLE_FRANCE_OPENING`
is false.
Make it optional if `WHOLE_FRANCE_OPENING` is true.
> (PC-7963) : fill postalCode as long as the PASS is locally restricted

- src/pcapi/alembic/versions/20210408_84cab0060952_feature_enable_activation_codes.py
- src/pcapi/app.py
- src/pcapi/models/feature.py
> (PC-7779) Ajout d'un feature flag ENABLE_ACTIVATION_CODES et d'un utilitaire pour simplifier les migrations de feature flags

- src/pcapi/core/bookings/validation.py
- tests/core/bookings/test_api.py
Since digital bookings are automatically marked as used upon creation,
we should not allow to mark them as unused.
> (PC-7783) Do not allow to mark digital bookings as unused

- src/pcapi/admin/custom_views/offer_view.py
- src/pcapi/templates/admin/edit_offer_validation.html
- tests/admin/custom_views/offer_view_test.py
Ajout d'un bouton 'Enregistrer et passer à l'offre suivante' sur la page de validation d'une offre en attente de validation.
> (PC-7891): LCF add save and go to the next offer in offer validation page FlaskAdmin

- src/pcapi/core/offers/repository.py
- src/pcapi/scheduled_tasks/clock.py
- tests/core/offers/test_repository.py
check_stock_consistence was initially meant to return stock objects
to perfom operations on it. Since the design around it changed, we
can lower the memory usage by only fetching the id.
> (FIX) : lower memory usage for check_stock_consistence

- tests/routes/native/v1/offers_test.py
Most of the time, the order would be good but since it is not
enforced it may fail. Ensure we get reliable results by ordering
the results.
> (FIX) fix flacky test by adding order

- src/pcapi/alembic/versions/20210413_719b8b8e632f_add_draft_to_validation_status_enum.py
- src/pcapi/core/offers/api.py
- src/pcapi/core/offers/models.py
- src/pcapi/core/offers/repository.py
- src/pcapi/core/offers/validation.py
- src/pcapi/model_creators/specific_creators.py
- tests/core/offers/test_api.py
- tests/core/offers/test_repository.py
- tests/core/offers/test_validation.py
Modifier le workflow de création d'offre et d'ajout de stocks
- ajout de la valeur `DRAFT` à l'enum `OfferValidationStatus`
- ajout de la migration modifiant le type SQL enum (en ajoutant une valeur) de la colonne `validation` de la table `offer`
- affectation du statut de validation DRAFT à l'offre dans la fonction `create_offer()`
- déplacement du calcul de statut d'offre, de `create_offer()` à `upsert_stocks()`
- ajout de la valeur `DRAFT` à l'enum `OfferStatus`
- exclusion des offres au statut `DRAFT` dans la liste des offres renvoyée par la route `list_offers()`
> (PC-7247) modify offer and stocks creation

- .circleci/config.yml
- Dockerfile
- Dockerfile.gcp
- requirements.txt
- runtime.txt
- src/pcapi/connectors/google_spreadsheet.py
- src/pcapi/core/object_storage/backends/local.py
- src/pcapi/flask_app.py
- src/pcapi/routes/webapp/signup.py
- src/pcapi/workers/worker.py
- tests/local_providers/allocine_stocks_test.py
- tests/local_providers/provider_test_utils.py
Mettre à jour la version de Python d'api vers Python 3.9
- supprimer une dépendance obsolète
- éditer les fichiers de configuration adéquats (CircleCI, Dockerfiles, runtime.txt)
- ignorer un faux positif pylint
En bonus, correction de warnings à l'exécution de l'api
> (PC-8124) bump Python version to 3.9

- src/pcapi/core/offers/repository.py
- src/pcapi/notifications/push/transactional_notifications.py
- src/pcapi/scheduled_tasks/clock.py
- src/pcapi/workers/push_notification_job.py
- tests/core/offers/test_repository.py
- tests/scheduled_tasks/clock_test.py
https://passculture.atlassian.net/secure/RapidBoard.jspa?rapidView=34&projectKey=PC&modal=detail&selectedIssue=PC-6879
**Besoins**
Envoyer des notifications aux utilisateurs qui ont une réservation pour une offre qui a lieu le lendemain.
1. tâche cron lancée chaque nuit (1AM) qui va récupérer la liste des identifiants des `Booking` concernés, et pour chacun créer une tâche asynchrone.
2. chaque tâche s'occupe d'un `Booking` : récupérer les informations liées (utilisateur et offre - via stock), formater les données et envoyer la notification.
**Discussion**
Une tâche asynchrone par Booking -> beaucoup de tâche, mais ça ne devrait pas être un soucis. L'avantage de cette approche est la simplicité. On pourrait chercher à grouper par offre et faire des tirs groupés si c'est …
> PC 6879 Send notification to user for offer that occur tomorrow 

- src/pcapi/core/logging.py
- tests/core/logging/tests.py
I did not notice that it existed. Fortunately, @xordoquy did.
Also, JsonFormatter had no test. Now it does.
> (PC-8166) logging: Use `LogRecord.getMessage()`

- src/pcapi/core/users/repository.py
- tests/core/users/test_repository.py
Extends the birthday email to users that registered the day right
before their birthday.
> (PC-8169) : extend birthday email to users registered the day before

- src/pcapi/routes/native/v1/favorites.py
- tests/routes/native/v1/favorites_test.py
Offers with active but past stocks were flagged as expired while
they are just exhausted
> (PC-7703) : fix favorite's expired offer

- src/pcapi/core/logging.py
- src/pcapi/flask_app.py
En dev, il y a 2 problèmes avec notre logger custom :
1. Les logs au format json sont difficiles à lire
2. La config `app.config["SQLALCHEMY_ECHO"] = True` ne fonctionne pas (boucle infinie)
Avant :
Après:
> Set default logger in dev mode

- src/pcapi/app.py
- src/pcapi/core/providers/api.py
- src/pcapi/local_providers/provider_api/synchronize_provider_api.py
- src/pcapi/routes/CONTRIBUTING.md
- src/pcapi/routes/pro/blueprints.py
- src/pcapi/routes/pro/bookings.py
- src/pcapi/routes/pro/offerers.py
- src/pcapi/routes/pro/offers.py
- src/pcapi/routes/pro/stocks.py
- src/pcapi/routes/pro/users.py
- src/pcapi/routes/serialization/stock_serialize.py
- src/pcapi/routes/webapp/beneficiaries.py
- src/pcapi/utils/rest.py
- src/pcapi/validation/routes/users_authentifications.py
- src/pcapi/validation/routes/users_authorizations.py
- src/pcapi/workers/synchronize_stocks_job.py
- tests/conftest.py
- tests/core/providers/connect_provider_to_venue_test.py
- tests/core/providers/test_api.py
- tests/local_providers/synchronize_provider_api_test.py
- tests/routes/pro/patch_user_has_seen_tuto_test.py
- tests/routes/pro/post_venue_stocks_test.py
Ouverture d'un endpoint pour les synchronisations plus spécifiques, notamment les petits acteurs culturels qui souhaitent s'intégrer eux mêmes sans que le pass valide, créé et gère une synchronisation complète avec eux
Point d'attention / parti pris : 
- fonctionnement calque sur l'api fournisseur pour uniformiser documentation et code
- sauf pour l'utilisation de venue_id au lieu du siret : les premiers partinaires sont ok. Doit-on prévoir un moyen de gérer le siret aussi ?
- utilisation du worker en cas de forte demande, doit-on prendre d'autres précautions ? Comme du rate limit
- y a t-il des erreurs qui peuvent survenir dans le worker et qui ne sont donc pas remontées en direct au fournisseur ?
- utilisation des champs idAtProviders ?
- ceux-ci duppliquent de l'info déjà présente et …
> (PC-8100): API Stock

- src/pcapi/routes/pro/validate.py
- tests/routes/pro/validate_user_test.py
Otherwise pro user nevers receive an e-mail that says that their
offerer has been created and validated.
> (PC-3455) pro: Do not automatically validate offerer and user offerer on integration environment

- src/pcapi/core/providers/api.py
- tests/core/providers/test_api.py
When we synchronize offers from a provider, we may receive data for an
offer with no available quantity that is unknown to us. In that case,
we should not create an offer. Adding this offer would be useless,
because it could not be booked and would not even appear in search
results.
> (PC-8249) Do not create offer with empty stock in provider synchronization

- src/pcapi/core/offers/repository.py
- src/pcapi/notifications/push/transactional_notifications.py
Apparemment l'ORM se charge d'éviter les doublons (avec la jointure sur Booking on pourrait avoir des Stock apparaître plusieurs fois). Dans le doute, on préfère retourner un set d'id plutôt qu'une liste.
> (PC-6879) Corrections : contenu notification + set compr au lieu de list compr

- src/pcapi/core/bookings/api.py
- tests/core/bookings/test_api.py
- tests/core/offers/test_api.py
- tests/routes/pro/delete_stock_test.py
- tests/routes/pro/patch_cancel_booking_by_token_test.py
**Besoin**
Mettre à jour les informations de l'utilisateur lors de la création ou de l'annulation d'une réservation.
Le code pour l'envoi de la requête et le calcul du montant du crédit existe déjà.
**Discussion**
Les nouveaux décorateurs pour les tests (module `utils.py`) permettent de limiter l répétition mais on perd peut-être un peu en lisibilité ?
> Pc 8159 update credit on booking update

- src/pcapi/routes/native/security.py
Since the native app does not use flask-login the current user
is not pushed to the request context and therefore it does not
appear in the logs.
By pushing it to the context just like flask-login does the user
will be available in the logs created by the native application
API.
> (PC-8329) : push native app users to the request context

- src/pcapi/core/users/models.py
- tests/routes/native/v1/account_test.py
We don't want 18+ years old nor 18- years old users to see their
location is outside the eligibility area.
Let's just keep that message for those who are 18 years old.
> (PC-8331) : show start/end egilibility dates for non eligible users

- src/pcapi/scripts/interact.py
Pour certains expressions un bug graphique apparaissait en console python, en particulier pour des expressions plus longue que la taille du shell, ou multiline, et en remontant l'historique
Par exemple :
> (PC): Python shell graphic bugs on long expressions

- src/pcapi/core/bookings/exceptions.py
- src/pcapi/core/bookings/repository.py
- src/pcapi/repository/user_queries.py
- src/pcapi/scripts/offerer/delete_cascade_offerer_by_id.py
- src/pcapi/scripts/suspend_fraudulent_pro_users.py
- tests/scripts/offerer/delete_cascade_offerer_by_id_test.py
- tests/scripts/suspend_suspected_fraudulent_pro_users_test.py
Script qui :
- Suspend le compte d'une liste d'acteurs frauduleux (basé sur #2159) ;
- Supprime ses structures/lieux si pas de réservations (basé sur #2274);
- Annule les réservations associées si existantes (basé sur #2174).
> (PC-7710) Suspend fraudulent pro user

- src/pcapi/core/bookings/api.py
- src/pcapi/core/users/api.py
- src/pcapi/notifications/push/user_attributes_updates.py
- src/pcapi/workers/push_notification_job.py
- tests/core/bookings/test_api.py
**Besoin**
Mettre à jour/créer le champ `lastBookingDate` d'un utilisateur sur Batch. Peu importe le statut de la réservation : même une réservation annulée doit être utilisée.
**Autres**
La fonction `get_last_booking_date` part du principe qu'il y a au moins un `Booking` existant : dans le cas contraire :arrow_right: erreur.
Si elle est appelée alors que l'utilisateur n'a aucune réservation, il vaut peut-être mieux avoir une erreur rapidement plutôt que de gérer des `None` pas très explicites, voire de laisser passer un `None` jusqu'à Batch et faire une mise à jour inattendue.
> (PC-6885) Update u.lastBookingDate field on Batch on Booking creation

- requirements.txt
- src/pcapi/core/offers/api.py
When searching the logs, it's sometimes easier to look for the ISBN
instead of the product ids.
> offers: Log ISBN in `deactivate_inappropriate_products()`

- requirements.txt
- src/pcapi/routes/native/utils.py
- src/pcapi/routes/native/v1/blueprint.py
- src/pcapi/settings.py
- tests/routes/native/v1/utils_test.py
Any request on the native API will now be scanned for the
`app-version` header - if present - and will be checked against
`NATIVE_APP_MINIMAL_CLIENT_VERSION` settings.
If the version is lower - according to semver - or the client's
version is not parsable then a 403 will be returned with the
`{"ERROR": "UPGRADE_REQUIRED"}` body.
Otherwise, the request will be processed as usual.
> (PC-8360) : native API returns 403 when client needs to upgrade

- src/pcapi/alembic/versions/20210428_9cff93fc69f2_feature_new_batch_index_offers.py
- src/pcapi/connectors/redis.py
- src/pcapi/models/feature.py
- src/pcapi/scheduled_tasks/algolia_clock.py
- src/pcapi/scripts/algolia_indexing/commands.py
- src/pcapi/scripts/algolia_indexing/indexing.py
- tests/scripts/algolia_indexing/indexing_test.py
Until now, `index_offers_in_algolia_by_offer` popped a limited amount
of offers from the queue (currently: 1.000) and stopped. The process
took a few seconds, and the cron job would only be run every minute.
During the night, we synchronize offers from various providers, which
requires to index/reindex a lot of offers. The queue gets quite big
and the cron job processes only 1.000 items every minute. The queue
hence takes a lot of time to be fully processed.
With the new behaviour, the cron job pops at least once a batch of
1.000 items and continues to do so until the queue is exhausted (or
until the queue has less than 1.000 items, so that we don't have a
cron job that never stops because something keeps on filling the
queue).
This new behaviour is behind a feature flag which is disabled …
> (PC-8290) algolia: Make offer reindexation cron job the queue consume the full queue

- .circleci/config.yml
In particular, this prevents unit tests to run when alembic migrations
are incorrect.
The directive `when: always` is no longer needed, because the quality
checks are now in a separate job.
> (PC-8458) circleci: stop run-tests job when step fails

- src/pcapi/routes/native/utils.py
- tests/routes/native/v1/utils_test.py
Obvioussly I went too fast in commit 1bac52b47547e0493f0cf868293d626188cf5385
and error message is not aligned with the other part of the native
API which usually returns {"code": "XXXX"}
> (PC-8360) : consistent message when native client needs to upgrade

- src/pcapi/core/users/repository.py
- src/pcapi/notifications/push/user_attributes_updates.py
- tests/core/bookings/test_api.py
Ajout d'une information à Batch : la liste des catégories des réservations d'un utilisateur. Cette liste doit contenir des éléments uniques.
> (PC-8209) Send user's offers' categories to Batch

- src/pcapi/notifications/push/user_attributes_updates.py
- src/pcapi/scripts/batch_update_users_attributes.py
**Fix**
Lors de l'envoi de la requête POST à Batch, les id des utilisateurs étaient passés tel quel (`int`) au lieu d'être envoyé sous forme de `str` -> l'API renvoie une erreur.
**Mise à jour**
On souhaite ajouter les nouveaux champs concernant les réservations : dernière date et catégories. Le code pour la dernière date est sur master, celui pour l'ajout des catégories pas encore ( https://github.com/pass-culture/pass-culture-api/pull/2344 )
> (PC-6882) FIX + UPDATE : cast user id to str + add new user booking attributes

- src/pcapi/core/providers/api.py
- src/pcapi/routes/pro/stocks.py
- src/pcapi/routes/serialization/stock_serialize.py
- tests/core/providers/test_api.py
- tests/routes/pro/post_venue_stocks_test.py
The pro public API now allows the pro users to also set the price
when they create or update books stock.
The price is an optional parameter and will override the default
product's price.
> (PC-8222) : add price to the update_stocks entry point

- src/pcapi/core/bookings/factories.py
- src/pcapi/core/bookings/repository.py
This property isn't usable for this function.
A comment has been added.
Also, fixing the BookingFactory to générate the right amount of
dnBookedQuantity.
> [PC-7746] Stock.dnBookedQuantity for get_active_bookings_quantity_for_venue

- src/pcapi/scripts/stock/fully_sync_venue.py
- tests/scripts/stock/fully_sync_venue_test.py
Only synchronized offers are handled by `fully_sync_venue()`: when
resetting stocks beforehand, offers that have been manually added
should be ignored.
> (PC-8522) fully_sync_venue: Do not reset Stock.quantity on manually added offers

- src/pcapi/repository/user_queries.py
- src/pcapi/scripts/suspend_fraudulent_pro_users.py
- tests/repository/user_queries_test.py
- tests/scripts/suspend_suspected_fraudulent_pro_users_test.py
Après un premier lancement sur prod du script (#2312 ) de suspension d'acteurs pros ayant des adresses mail avec des noms de domaine spécifiques, Le script plante. Certains utilisateurs ne sont ni bénéficiaires ni acteurs pro (Pas de `Offerer`) ont été récupéré par ce script, Une tentative de suppression d'Offerer a planté le script. 
Dans cette PR une jointure avec `UserOfferer` avec un filtre `User.offerers.any()` ont été ajouté à la requête pour récupérer que les acteurs pro 
Sur le script précédent seulement la suspension d'acteurs avec un seul `Offerer` était possible. La possibilité de suspendre des acteurs avec plusieurs `Offerer` est ajoutée dans cette PR.
> (PC-7710): update find pro users by email provider to get only pro users

- src/pcapi/core/providers/api.py
- src/pcapi/routes/serialization/stock_serialize.py
- tests/core/providers/test_api.py
Null stock prices convey the idea that they were not set by
the provider and therefore the stock price should be set to
the product's price.
> (PC-8222) : null prices for stock upset uses the offer's price

- .circleci/config.yml
un dernière ligne à changer dans le build circleci pour passer nightly en vert.
> circleci: switch nightly test pro to sandbox testcafe

- src/pcapi/alembic/versions/20210506_58df8264fe50_enable_native_id_check_version.py
- src/pcapi/models/feature.py
- src/pcapi/routes/native/v1/serialization/settings.py
- src/pcapi/routes/native/v1/settings.py
- tests/routes/native/v1/settings_test.py
Add a feature flag to trigger the integrated version of ID Check
in the native application. Also expose the feature flag through
the settings endpoint API.
> (PC-8614) : native app integration of ID check feature flag

- src/pcapi/core/users/api.py
- src/pcapi/domain/user_activation.py
- src/pcapi/infrastructure/repository/beneficiary/beneficiary_pre_subscription_sql_converter.py
- src/pcapi/infrastructure/repository/beneficiary/beneficiary_sql_repository.py
- src/pcapi/repository/beneficiary_import_queries.py
- src/pcapi/routes/native/v1/authentication.py
- src/pcapi/scripts/beneficiary/remote_import.py
- src/pcapi/use_cases/create_beneficiary_from_application.py
- tests/core/users/test_api.py
- tests/domain/user_activation_test.py
- tests/routes/webapp/post_id_check_application_update_test.py
- tests/scripts/beneficiary/remote_import_test.py
- tests/use_cases/create_beneficiary_from_application_test.py
* un utilisateur dont l'import (id-check) est validé ne devient plus bénéficiaire automatiquement : on vérifie qu'il a passé toutes les autres étapes nécessaires avant (aujourd'hui cela signifie avoir validé son numéro de téléphone).
* désactiver le champ `id_check_token` dans la réponse à `/validate_email` puisque une nouvelle étape a été ajoutée entre la validation d'email et id-check : la validation du numéro de téléphone. On ajoute donc un nouveau champ : `needsToValidatePhone` afin d'indiquer au front la prochaine étape (validation du numéro de téléphone ou id-check).
> PC 8116 Disable automatic beneficiary activation

- src/pcapi/routes/native/v1/bookings.py
- src/pcapi/routes/native/v1/serialization/bookings.py
- tests/routes/native/v1/bookings_test.py
Since we modify the offer's url to fix an issue with the native
application, we need to rollback the changes to ensure they are
neither in an intermediate state nor commited.
session.expunge should have let us do that but somehow it does not
seem to work in all the cases
> (PC-8709) : Rollback offer change on native bookings list API

- src/pcapi/core/offers/utils.py
- src/pcapi/emails/offer_webapp_link.py
- src/pcapi/notifications/push/backends/batch.py
- src/pcapi/notifications/push/backends/testing.py
- src/pcapi/notifications/push/transactional_notifications.py
- src/pcapi/routes/native/v1/offers.py
- src/pcapi/workers/push_notification_job.py
- tests/routes/native/v1/offers_test.py
Ajout d'une route permettant l'envoi d'une notification contenant un lien vers une offre.
Cette nouvelle route sera utilisée iOS uniquement afin de contourner certaines limites de l'os mobile.
+ ajout d'un champ `extra` à `TransactionalNotificationData` afin de passer d'autres informations : ici, on a besoin d'ajouter un champ `deeplink` au JSON envoyé à Batch
+ nouvelle fonction `offer_webapp_link` qui sert à construire le lien webapp d'une offre -> utilisé par les notifications push et email.
> (PC-8242) send offer link notification

- src/pcapi/routes/native/v1/favorites.py
- src/pcapi/routes/native/v1/serialization/favorites.py
- tests/routes/native/v1/favorites_test.py
Since the native application displays a badge with the number of
favorites for a user, it should not need to fetch the full favorites
data since they are costly to compute.
Instead of loading the entire favorites data, we add an endpoint
to return the number of favorites which is fast and simple to get.
> (PC-8591) : add favorites/count to the native API

- src/pcapi/routes/native/v1/serialization/account.py
- tests/routes/native/v1/account_test.py
`True` si l’utilisateur est :
* éligible ;
* qu’il n’est pas bénéficiaire ;
* `phoneValidationStatus` est différent de `VALIDATED`.
Si la fonctionnalité `ENABLE_PHONE_VALIDATION` n'est pas activée, `needsToValidatePhone` vaut `False`.
> (PC-8394) /me add needsToValidatePhone

- src/pcapi/routes/native/v1/offers.py
- src/pcapi/routes/native/v1/serialization/offers.py
- tests/core/bookings/test_validation.py
- tests/routes/native/v1/offers_test.py
In order to display the activation code's expiration date during
the booking process, the offer on native API should return the
information if available.
> [PC-8667] Show activation code expiration in native offer's API

- src/pcapi/core/users/api.py
- src/pcapi/core/users/exceptions.py
- src/pcapi/notifications/sms/sending_limit.py
- src/pcapi/routes/native/v1/account.py
- src/pcapi/settings.py
- tests/conftest.py
- tests/routes/native/v1/account_test.py
- tests/routes/webapp/phone_validation_test.py
In order to limit fraud we want to limit the number of SMS a user
can send to check its phone number.
> [PC-8398] : Limit the number of SMS sent to verify a phone number

- src/pcapi/routes/native/v1/favorites.py
- tests/routes/native/v1/favorites_test.py
This should fix most concurent requests when creating a favorite.
Returns the existing favorite if it was already created and act
as if it was just created - might be because the client missed
a request or though it missed it.
> (PC-8796) : Fix double favorite creation

- src/pcapi/alembic/versions/20210519_e63d336e9da8_populate_provider_prices_in_cents.py
- src/pcapi/alembic/versions/20210519_e7a7fdd9c4e1_add_provider_prices_in_cents.py
- src/pcapi/core/providers/models.py
- src/pcapi/local_providers/provider_api/synchronize_provider_api.py
- src/pcapi/routes/pro/providers.py
- src/pcapi/routes/pro/stocks.py
- tests/core/providers/test_api.py
- tests/local_providers/synchronize_provider_api_test.py
Commits à relire séparément. Pourquoi 2 commits ?
1. On veut hotfix la prod aujourd'hui ou demain **avec le premier commit seulement**.
2. Le second commit ne sera **pas** déployé en hotfix sur la prod, car il contient une migration.
Inclure la migration dans le hotfix aurait nécessité de ré-ordonner les migrations qui sont sur master mais pas encore en prod.
> (PC-8765) + (PC-8813): Gestion du fournisseur qui envoie les prix en centimes

- src/pcapi/core/providers/api.py
Here `stock["price"]` is a Decimal. We must convert it to a float to
compare it to the product price and JSON-serialize it in the logx.
> providers: Fix price comparison in _get_stocks_to_upsert

- tests/conftest.py
When tests were launched in docker the default behaviour redis.Redis() did not work
> (PC-8398) Add settings.REDIS_URL in conftest

- src/pcapi/scripts/beneficiary/send_mail_after_idcheck_outage.py
- tests/scripts/beneficiary/send_mail_after_idcheck_outage_test.py
script to send a mail to newly created users that should have
been able to start the ID-Check process but were not able to due
to ID-Check being turned off.
Note that the script DOES NOT conttact users that were already created.
> (PC-8076) : mail newly created user script after ID-Check outage

- src/pcapi/core/offers/api.py
- src/pcapi/core/offers/validation.py
- tests/core/offers/test_api.py
Une KeyError python était levée avant de passer dans notre if.
> PC-8821: correct bug KeyError in check validation configuration file format

- src/pcapi/routes/native/v1/authentication.py
- tests/routes/native/v1/authentication_test.py
When adding the limitation on IdCheck token quantity for a given
user, the email validation route was forgotten and had sometime
an uncaught exception when trying to create a new token and the
user is not allowed to create one anymore.
Let's catch that exception and return an empty token just like
a non eligible user.
> (PC-8909) : fix email validation when user has no idcheck token left

- src/pcapi/core/users/repository.py
- src/pcapi/routes/webapp/beneficiaries.py
- tests/routes/webapp/post_verify_id_check_licence_token_test.py
licence_verify was trying to get an active and valid token before
falling back to recaptcha.
However it creates false warning about broken recaptcha.
Therefore the API will now try to sort out whether it's a token
or a recaptcha and then will check the token is valid in a second
step.
> (PC-8910) : Don't let expired tokens be tested as recaptchas

- src/pcapi/alembic/versions/20210523_0fe847be8089_feature_enable_idcheck_fraud_control.py
- src/pcapi/connectors/beneficiaries/jouve_backend.py
- src/pcapi/models/feature.py
- tests/connectors/beneficiaries/beneficiary_jouve_repository_test.py
In order to bypass security checks on staging to run the
IDCheck process, let's add a feature flag to skip it.
> (PC-8919) : Add a IDCheck fraud control feature flag

- src/pcapi/alembic/versions/20210524_9908a2709641_add_idx_offer_validation.py
- src/pcapi/core/offers/models.py
This is especially necessary for the FA Validation section
> PC-8943: add index on the Validation column from the Offer table

- src/pcapi/core/users/api.py
- src/pcapi/domain/user_activation.py
- src/pcapi/infrastructure/repository/beneficiary/beneficiary_pre_subscription_sql_converter.py
- tests/scripts/beneficiary/remote_import_test.py
- tests/use_cases/create_beneficiary_from_application_test.py
Ne pas mettre à jour le numéro de téléphone de l'utilisateur lors de l'import ID-Check s'il en a déjà un.
**Au passage**
Ajout de `**kwargs` à `create_user` pour faciliter la création d'utilisateurs. Ici : passer le paramètre `phoneNumber` dans des tests.
**Note**
Aucun test n'a été ajouté dans `tests/use_cases/create_beneficiary_from_application_test.py` pour le cas où l'utilisateur n'existe pas, car il est déjà pris en compte : on vérifie que le numéro de téléphone est bien celui d'ID-Check (backend de test).
> Pc 8503 phone number id check

- helm/pcapi/values.integration.yaml
- src/pcapi/alembic/versions/20210523_0fe847be8089_feature_enable_idcheck_fraud_control.py
> Correctoin ALGOLIA_API_KEY + fix typo dans une migration

- src/pcapi/routes/native/v1/account.py
- src/pcapi/routes/native/v1/serialization/account.py
- tests/routes/native/v1/account_test.py
To make easier for the native app to track non eligible users
the backend will now return a specific error code when a
non eligible user tries to get an IDCheck token.
> [PC-8995] : return 400 on non eligible user asking for id check

- requirements.txt
- src/pcapi/core/users/api.py
- src/pcapi/core/users/constants.py
- src/pcapi/core/users/utils.py
- src/pcapi/notifications/sms/backends/sendinblue.py
- tests/routes/native/v1/account_test.py
- tests/routes/webapp/phone_validation_test.py
Valider et normaliser les numéros de téléphone des utilisateurs : 
1. vérifier que le numéro est valide (nombre de chiffre correct, format général cohérent) ;
2. vérifier que le code de pays du numéro correspond bien à un numéro français (métropole + dom-tom)
3. normaliser le format des numéros de téléphone des utilisateurs en base de données (format E.164)
Renvoyer une erreur si le numéro de téléphone n'est pas conforme lors des opérations suivantes : 
* changer le numéro de téléphone de l'utilisateur (`/send_phone_validation_code`)
* envoyer un code de validation à l'utilisateur (`/send_phone_validation_code`)
* valider le code envoyé précédemment (`/validate_phone_number`)
:heavy_plus_sign:  Mettre à jour les versions des secrets BLACKLISTED_SMS_RECIPIENTS (version 1 à 2)
> (PC-8771) phone number: validate and normalize

- src/pcapi/admin/custom_views/mixins/suspension_mixin.py
- tests/admin/custom_views/beneficiary_user_view_test.py
`suspend_account()` already did the job but the admin code called it
with the suspension reason as a string, instead of passing a
`SuspensionReason`. As such, bookings were not cancelled.
> (PC-9013) Cancel bookings on suspend from admin

- src/pcapi/domain/user_emails.py
- src/pcapi/emails/beneficiary_activation.py
- tests/domain/user_emails_test.py
Ne pas créer de token id check pour l'envoi de l'email à un utilisateur qui devient éligible afin d'éviter le cas (minoritaire) où l'utilisateur clique sur le lien après l'expiration du token.
> (PC-9015) eligible email: no more idcheck token

- src/pcapi/alembic/versions/20210526_3605366e5ded_add_validation_date_to_offer.py
- src/pcapi/alembic/versions/20210531_8bdc4dd58856_feature_enable_native_id_check_verbose_debugging.py
Since we added a new migration in v137.0.2 (8bdc4dd58856) and
it was added in master after migrations that were not part of
v137.0.2, we need to reorder them to get them applied in the
upcoming version.
`alembic history` diff (v137.0.2 on the left, master on the right) after the PR:
```
>	77d29ab6c382 -> 5bca073597c4, add_feature_flipping_for_bookin
>	3605366e5ded -> 77d29ab6c382, add_index_for_last_validation_d
>	8bdc4dd58856 -> 3605366e5ded, add_validation_date_to_offer
e8199ef92975 -> 8bdc4dd58856, Add ENABLE_NATIVE_ID_CHECK_VERB	e8199ef92975 -> 8bdc4dd58856, Add ENABLE_NATIVE_ID_CHECK_VERB
20290f0b5d4f -> e8199ef92975, migrate_id_at_provider_part_2	20290f0b5d4f -> e8199ef92975, migrate_id_at_provider_part_2
9908a2709641 -> 20290f0b5d4f, migrate_id_at_provider_part_1	9908a2709641 -> …
```
> (FIX) : reorder migration after v137.0.2

- src/pcapi/core/users/api.py
- src/pcapi/core/users/models.py
- src/pcapi/core/users/repository.py
- tests/routes/native/v1/account_test.py
- Allow duplicated phone number if they are not validated
In order not to forbid a user to set its phone number if someone
else also entered it, we will restrict the phone number uniqueness
if the phone number is validated.
- don't validate an already validated phone number 
Do not allow a user to validate a phone number that is already validated.
This may happen if several users used the same unvalidated number and start validating it.
> (PC-8960) unique validated phone number

- src/pcapi/admin/custom_views/offer_view.py
- src/pcapi/core/offers/api.py
- tests/admin/custom_views/offer_view_test.py
Limiter l'accès à la vue admin de validation des offres aux utilisateur _super admin_
- ajout de `is_accessible()` à la `ValidationView`
En bonus, une correction de niveau de log dont le relecteur pardonnera l'ajout cavalier.
> (PC-7143) fix ValidationView access

- src/pcapi/routes/native/v1/authentication.py
- src/pcapi/routes/native/v1/serialization/authentication.py
- tests/routes/native/v1/authentication_test.py
Ne plus créer de token id check lors de la validation de l'email afin de n'avoir plus qu'un seul moyen de créer des tokens id check : lors d'un appel à `GET /id_check_token`. Ceci permet de ne pas consommer inutilement une tentative à l'utilisateur s'il ne bascule pas immédiatement sur le parcours id check.
> (PC-9076) remove id-check token from /validate_email response

- src/pcapi/infrastructure/repository/beneficiary/beneficiary_pre_subscription_sql_converter.py
- tests/use_cases/create_beneficiary_from_application_test.py
Since we now have a check that the ID card number is not duplicated
we also need to store that number in the database.
> (PC-8989) : Save the ID card number after IDCheck

- src/pcapi/routes/native/security.py
Logging an error pollutes Sentry, while we don't have anything to do
about it. An info log is enough.
---
Le log en question dans Sentry : https://logs.passculture.app/organizations/sentry/issues/2545
> native: Lower log level on unknown user authentication

- src/pcapi/admin/custom_views/offer_category_view.py
- src/pcapi/admin/install.py
- src/pcapi/templates/admin/offer_categories_list.html
- src/pcapi/templates/admin/offer_subcategories_list.html
Ajouter des vues _FlaskAdmin_ pour `OfferCategoryGroup` et `OfferCategory`
Un réarrangement des imports de `src/pcapi/admin/install.py` a été fait au passage, afin d'éviter les imports de nombreuses classes du même module.
Cette PR devra être fusionnée APRES https://github.com/pass-culture/pass-culture-api/pull/2601 (renommage de modèles)
Un grand dilemme m'a saisi: `subcategory` ou `sub-category` ? Si l'orthographe avec trait d'union (_hyphenated_) est souvent acceptée en anglais UK ou CA, elle est en revanche déconseillée en anglais US. J'ai donc choisi de conserver l'orthographe sans trait d'union, qui fait l'économie de bosses de chameau au passage.
> (PC-8283) add admin views for OfferCategoryGroup and OfferCategory

- src/pcapi/core/offers/api.py
- src/pcapi/routes/serialization/offers_serialize.py
- src/pcapi/validation/routes/offers.py
- tests/core/offers/test_api.py
- tests/validation/routes/offers_test.py
Importer les informations d'un livre depuis un ISBN13 lors de la création d'offre.
Avoir qu'un seul `product` pour un isbn.
Validation du champs `isbn` qui devient obligatoire pour la création d'offre de type LIVRE_EDITION.
Vérification si le livre est éligible au pass Culture.
Création de l'offre.
PR [front](https://github.com/pass-culture/pass-culture-pro/pull/1338)
> (PC-5091): Validate isbn on LIVRE_EDITION offer creation and associate it to existing product

- src/pcapi/alembic/versions/20210604_25468af34cb8_make_require_provider_identifier.py
- src/pcapi/core/providers/models.py
- src/pcapi/model_creators/generic_creators.py
- src/pcapi/routes/pro/providers.py
- src/pcapi/routes/serialization/offers_serialize.py
- src/pcapi/routes/serialization/venue_provider_serialize.py
- tests/routes/pro/get_providers_by_venue_test.py
- tests/routes/pro/post_venue_provider_test.py
This field is not used by the pro portal anymore. Here we stop exporting it
and set it as nullable. Once this commit is deployed, we will finally
delete the column.
---
PR liée côté portail pro : pass-culture/pass-culture-pro/pull/1340
> (PC-9250) providers: Stop using Provider.requireProviderIdentifier

- README.md
- requirements.txt
Pylint 2.8.3 + astroid 2.5.8 :arrow_right: :boom: 
`AttributeError: 'ListComp' object has no attribute 'name'`
Ce n'est pas la première fois qu'on a ce type d'incompatibilité, autant être serein avec deux versions dont on sait qu'elles fonctionnent ensemble.
> (PC-fix) set pylint and astroid versions

- src/pcapi/routes/native/v1/account.py
If - for some reasons - a user already beneficiary tries to call
/id_check_token, let's just return an error to tell the user that
he can't do that.
> (PC-9326) : Raise error on id_check_token if already beneficiary

- tests/conftest.py
The current pattern is quite annoying. This commit tries to ease it a bit:
If the request you're trying to test requires a Bearer token (mostly on the api):
```
def shinny_test(client):
user = users_factories.UserFactory()
client.with_token(user.email)
client.verb("url", params)
```
If the request you're trying to test requires a simple authorization (mostly pro):
```
def shinny_test(client):
user = users_factories.UserFactory()
client.with_auth(user.email)
client.verb("url", params)
```
> pytest configuration :  add client fixture

- src/pcapi/connectors/user_profiling.py
- src/pcapi/utils/requests.py
- tests/routes/native/v1/account_test.py
As every call, we want to have the same harmonised logs on external api calls.
And a quick cleanup of the try/except to only wrapps the actual request call
> Log User Profiling calls duration and errors using pcapi.utils.requests

- src/pcapi/admin/custom_views/mixins/suspension_mixin.py
The text was escaped by `Markup.format()`, which caused this to be
displayed in the browser:
Suspendre&hellip;
The bug was introduced in aa10f18a0adfa2dc82a05148027bf2e899c0a2bb.
> (PC-9311) admin: Fix over-escaping of suspend/reactivate link in user lists

- src/pcapi/domain/user_activation.py
- src/pcapi/scripts/beneficiary/remote_import.py
- tests/scripts/beneficiary/fixture_dms_with_selfie.py
- tests/scripts/beneficiary/remote_import_test.py
The beneficiairy creation now saves the ID card number - or the
other piece that was used - along with the user if it is available.
> (PC-9264) : Save the ID piece number during DMS process

- src/pcapi/core/users/api.py
- tests/core/users/test_api.py
Créditer automatiquement les comptes PRO crées sur intégration.
Dans `create_pro_user()`
- Passer `isBeneficiary` à `True`
- Créer un `deposit` et l'associer à l'utilisateur pro
> (PC-8440): Automaticaly grant wallet to new pro users after sign-up on integration

- src/pcapi/domain/user_emails.py
- src/pcapi/emails/user_document_validation.py
- tests/core/users/test_api.py
Ne plus utiliser l'utilisateur dans les données des templates : puisqu'en cas d'erreur, il y a peu de chances pour que l'utilisateur ait son prénom en base de données, le prénom a été retiré du template d'email.
En plus : il semble que l'API de Mailjet n'apprécie pas particulièrement une variable avec une valeur nulle.
> (PC-9303) send email on document validation error

- src/pcapi/domain/demarches_simplifiees.py
- src/pcapi/scripts/beneficiary/remote_import.py
- tests/domain/demarches_simplifiees_test.py
- tests/scripts/beneficiary/remote_import_test.py
- tests/use_cases/create_beneficiary_from_application_test.py
DMS somtimes missed files when it crashes while processing
applications.
Former behaviour was taking only the files that were processed
after the last imported beneficiairy was created on the backend.
If it crashed for some reasons (most likely couldn't reach the
DMS server) the files that were not processed were not recovered
after because there process time was before the latest created
beneficiary.
New behaviour is to ignore process time and only look in the
beneficiary import table whether the file has been processed or
not
> (PC-9457) fix dms crashes recovery

- src/pcapi/scheduled_tasks/clock.py
In order to avoid unnecessary spam in staging the backend will
now send birthday email only in production or testing.
> (PC-9518) : only send birthday email in production or testing

- requirements.txt
- src/pcapi/flask_app.py
- tests/utils/db_test.py
Takes advantage of bootstrapv4 to use more css components
as described in the docs
https://getbootstrap.com/docs/4.0/getting-started/introduction/
for now, I only found a "subtile" change in the header color which is lighter.
> flask-admin: migrate to bootstrap v4

- src/pcapi/connectors/beneficiaries/id_check_middleware.py
Pas de test #yolo
J'ai aussi mis l'email, comme dans les autres logs du circuit, pour pouvoir retrouver un utilisateur si besoin
Mais c'est pas top il faudrait enlever l'email de tout ces logs et remplacer par une donnée non personnelle je pense : leur id
> (PC-9509): Ajout d'un log au retour de réponse jouve

- src/pcapi/models/db.py
when using PG's JSONB field, we might want to serialize complex types, such as datetime etc..
This commit configure flask's json encoder to simplify this, avoiding us to store json as string
> db: configure jsonencoder to ease jsonb usage

- .pylintrc
- src/pcapi/core/fraud/factories.py
- src/pcapi/models/db.py
Using flask serializer was not enough : the date time serialized didn't have a common format for instance.
using Pydantic help us using standard formats, and allows us to directly hydrate a pydantic object.
> Add pydantic serializer to control sqlalchemy json serialization

- src/pcapi/core/bookings/api.py
- tests/core/bookings/test_api.py
This is a revert of c67da9cce8df76599cf0b6b97dc4676ca4874790. In that
former commit, we made `mark_as_used()` a no-op if the booking was
already used. This was done to prevent errors when the offerer tried
to validate a booking that had been automatically marked as used.
This was both:
- useless: offerers never use our API to mark bookings as used for
automatically-validated bookings. These bookings always have an
activation code, which the beneficiary uses on the offerer's web
site. The booking token is never used in that case.
- wrong: for bookings that are not automatically validated upon
creation, we (obviously) do NOT want to allow a token to be used
twice. Therefore, the mark-as-used API must fail if it's given
a booking that has already been used.
> (PC-9690) bookings: Raise error in `mark_as_used()` if already used

- src/pcapi/connectors/beneficiaries/jouve_backend.py
- tests/use_cases/create_beneficiary_from_application_test.py
Since there's quite some false negative hard checks, we want to make
them soft to make those cases go through a manuel check.
> (PC-9703) : Change "hard" security checks into "soft" during IDCheck

- src/pcapi/scripts/booking/handle_expired_bookings.py
- tests/scripts/booking/handle_expired_bookings_test.py
This fixes the fact that only the latest batch of cancelled bookings
was used to recompute dnBookedQuantity on the associated stock.
We also want to commit the recomputed dnBookedQuantity along with
the cancelled bookings so that if something goes south for whatever
reason during the process, the already cancelled bookings will be
aligned with the stock's dnBookedQuantity.
> (PC-9729) : Recompute dnBookedQuantity for each booking batch cancelled

- .github/workflows/gitguardian.yml
Those two lines have been introduced in be5ad43730dd98a1032dffdb0ab5b078db1035ba.
They are bogus, GitGuardian fails with:
The workflow is not valid.
.github/workflows/gitguardian.yml (Line: 24, Col: 9): Unexpected value 'matches-ignore'
In fact, I don't think this exemption is necessary, since that
password-looking code has been removed in the aforementioned commit.
> qa: Fix GitGuardian configuration

- src/pcapi/core/users/api.py
- tests/routes/native/v1/account_test.py
SQLA's default parameter is not applied until the object is saved
into DB, which can cause some trouble if some code expects that
externalIds is never None.
> (PC-9689)[FIX] set externalIds if None

- src/pcapi/core/search/__init__.py
Avoid this:
Traceback (most recent call last):
File "/src/pcapi/scheduled_tasks/algolia_clock.py", line 4, in <module>
from pcapi.core import search
File "/src/pcapi/core/search/__init__.py", line 5, in <module>
import pcapi.core.offers.models as offers_models
File "/src/pcapi/core/offers/models.py", line 36, in <module>
from pcapi.models.db import Model
File "/src/pcapi/models/__init__.py", line 8, in <module>
from pcapi.core.offerers.models import ApiKey
File "/src/pcapi/core/offerers/models.py", line 33, in <module>
from pcapi.core.offers.models import Offer
ImportError: cannot import name 'Offer' from partially initialized module 'pcapi.core.offers.models' (most likely due to a circular import) (/src/pcapi/core/offers/models.py)
Enough is enough. I'll fix that import mess next …
> search: Fix import loop when `core.search` is imported early

- src/pcapi/admin/base_configuration.py
- src/pcapi/admin/custom_views/beneficiary_user_view.py
- tests/admin/base_configuration_test.py
Flask admin cache all forms at loading time, which breaks when we want to customize some forms field depending on the user role for instance.
This has been done in `beneficiary_user_view` admin views already, but I think we would like to have this behavior to all our admin views.
The form cache is probably not necessary for our needs
> FlaskAdmin : custom view disable edit and creation form cache

- src/pcapi/flask_app.py
The request may be encoded in something other than "utf-8" (although
it's unlikely). Also, if the client sends badly encoded content, cope
with it and don't fail when logging the request.
---
Exemple d'erreur dans Sentry : https://logs.passculture.app/organizations/sentry/issues/21825
> flask_app: Cope with badly encoded query string

- src/pcapi/routes/serialization/beneficiaries.py
- src/pcapi/routes/serialization/users.py
- tests/routes/shared/signin_test.py
- tests/routes/webapp/get_beneficiary_profile_test.py
- tests/routes/webapp/patch_beneficiary_test.py
Commits à relire séparement
:one: Le premier commit ajoute le retour des rôles sur la route `GET /beneficiaries/current`
:two: Le deuxième commit corrige spectree pour prendre en compte le fait que les codes de départements sont maintenant optionels
> (FIX) Return roles for beneficiaries and fix spectree serialization

- src/pcapi/domain/beneficiary_pre_subscription/beneficiary_pre_subscription_validator.py
- src/pcapi/infrastructure/repository/beneficiary/beneficiary_pre_subscription_sql_converter.py
This is meant to help with validation on testing/staging.
Turns the id card check off and do not save the id card so one
can be used to create several beneficiaries.
> (PC-9772) : Jouve id card check skipped if fraud controls is off

- src/pcapi/domain/beneficiary_pre_subscription/beneficiary_pre_subscription_validator.py
La PR précédente a rendu le code de département optionnel ce qui créé une erreur dans `is_eligible` qui fait une vérification sur le département. L'erreur remontée arrivait au moment de l'inscription, lors de l'envoi de l'email, le template a besoin de savoir si l'utilisateur est éligible ou non.
**FIX**
Rendre optionnel le paramètre `code` de `_is_postal_code_eligible` : on ne casse rien et on règle le problème.
Il faudra ensuite revoir toutes les vérifications sur les départements, plus en détail.
> (PC-9461)[FIX] make departmentCode optional for eligibility

- src/pcapi/connectors/beneficiaries/jouve_backend.py
- src/pcapi/core/fraud/api.py
Since they only seem to be false negative, let's juste remove
them.
> (PC-9791) : remove poste/serviceCodeCtrl from security checks

- src/pcapi/admin/custom_views/fraud_view.py
- src/pcapi/alembic/versions/20210630_29c8b67b67a5_add_beneficiary_validation_after_fraud_.py
- src/pcapi/models/feature.py
- tests/admin/custom_views/fraud_view_test.py
Since we have not yet group permissions let's add a feature flag
to allow the validation of beneficiaries by super admins for
validation purposes.
> (PC-9738) : Add FF to disable beneficiary activation from admin

- src/pcapi/scheduled_tasks/clock.py
By default the scheduled tasks are not commited. This needs to be
make explicitely.
> (PC-9722) : Commit the token deletion on the scheduled task

- src/pcapi/core/search/__init__.py
- src/pcapi/core/search/backends/algolia.py
- src/pcapi/local_providers/local_provider.py
- tests/core/search/test_api.py
Spotted by @fseguin.
search: Don't catch errors during tests
This could mask errors, such as calling a function of the Redis client
with wrong arguments.
____ WIP: DO NOT MERGE : Revert "search: Fix call to async_index_offer_ids"
This reverts commit 2fca021513c2238e45887c58f13cc1610b98122d.
> search: Fix call to async_index_offer_ids

- src/pcapi/routes/native/v1/serialization/offers.py
- tests/routes/native/v1/offers_test.py
This field is not used on the mobile app. Last commit:
https://github.com/pass-culture/pass-culture-app-native/commit/e7948b4bb7d8ee2c9c619d053820df486ea92191
and was not in production so it is safe to remove.
> (Api native) Remove unused field offer.isActive

- src/pcapi/core/bookings/repository.py
- src/pcapi/scripts/payment/batch_steps.py
We don't need the alias on Booking (since the table is only joined
once) and `sql.and_()` is also useless.
payments: Ignore free offers when looking for bookings to reimburse
It used to be implicit that free bookings were not reimbursed, because
"standard" rules yielded a 0 € reimbursement that was ignored (i.e. it
did not generate a Payment object).
However, an offer may now have a custom reimbursement rule. If one of
its stock used to be 0 € for a while (because of a manual entry
error), then the corresponding bookings would be free and yet we would
calculate a custom reimbursement amount (based on the real price of
the offer) for them.  Of course we don't want to reimburse an offerer
for free bookings.
(Yes, it happened on stock 5160973 which had 4 free bookings: 601757,
615731, 624400 …
> payments: Remove SQLAlchemy sugar from get_venues_to_reimburse()

- src/pcapi/admin/custom_views/fraud_view.py
- src/pcapi/core/fraud/api.py
- src/pcapi/core/users/api.py
- src/pcapi/templates/admin/fraud_details.html
- tests/admin/custom_views/fraud_view_test.py
- tests/core/fraud/test_api.py
- tests/core/users/test_api.py
* Allows to filter frauds if no manual review as been done
* Fix the display of the manual review in F.A.
* Stores the beneficiary data from the External ID checks
> Fraud fix after manual tests

- src/pcapi/local_providers/titelive_things/titelive_things.py
- tests/local_providers/titelive_things_test.py
Some books are marked with 'xxx' in their title and author fields. It's a convention for titelive and means the book is not released yet so dont import it
> (PC-9144) Skip books marked with 'xxx' in titelive synchronization

- src/pcapi/scripts/clean_duplicated_offers.py
- tests/scripts/clean_duplicated_offers_test.py
**Besoin**
Corriger les offres dupliquées, lieu par lieu puisqu'il semble que ces offres sont concentrées dans quelques lieux uniquement.
⚠️ cette PR active [le module `intarray `de Postgresql](https://www.postgresql.org/docs/12/intarray.html), qui nous permet de trier une liste d'entier ⚠️ 
Note : la conversion des id des offres en `integer `(`big integer` -> `integer`) ne devrait pas poser de soucis, ça devrait rester largement dans les limites du type `integer`.
> (PC-9334) add clean duplicated offers script

- src/pcapi/alembic/versions/20210705_20349c929b56_adding_perf_venue_stats_feature_flag.py
- src/pcapi/alembic/versions/20210705_d9f2a9027e7d_adding_offerid_and_venueid_to_bookings.py
- src/pcapi/core/bookings/api.py
- src/pcapi/core/bookings/factories.py
- src/pcapi/core/bookings/models.py
- src/pcapi/core/bookings/repository.py
- src/pcapi/infrastructure/repository/beneficiary_bookings/beneficiary_bookings_sql_repository.py
- src/pcapi/model_creators/generic_creators.py
- src/pcapi/models/feature.py
- src/pcapi/routes/pro/offerers.py
- src/pcapi/routes/pro/venues.py
- src/pcapi/routes/serialization/offerers_serialize.py
- src/pcapi/sandboxes/scripts/creators/bookings_recap/bookings_recap.py
- src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_activation_offers.py
- src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_bookings.py
- tests/core/bookings/test_models.py
- tests/core/bookings/test_repository.py
- tests/infrastructure/repository/beneficiary_bookings/beneficiary_bookings_sql_repository_test.py
- tests/local_providers/titelive_things_test.py
- tests/repository/offer_queries_test.py
- tests/repository/payment_queries_test.py
- tests/routes/pro/get_booking_by_token_v2_test.py
- tests/routes/pro/get_offerer_test.py
- tests/routes/pro/patch_booking_keep_by_token_test.py
- tests/routes/pro/patch_booking_use_by_token_test.py
- tests/routes/webapp/get_booking_by_id_test.py
- tests/routes/webapp/get_bookings_test.py
- tests/scripts/booking/cancel_bookings_of_events_from_file_test.py
- tests/scripts/payment/batch_steps_test.py
- tests/scripts/payment/generate_new_payments_test.py
This Pull request contains 2 commits :
1. Migration from legacy fixtures to Factory Fixtures (Prérequesite for point 2)
2. Adding a new route for pro, Adding feature flip PERF_VENUE_STATS, adding 2 foreign keys to booking and the corresponding indexes to make the queries far more efficient
A manuel migration of data will be perfomed during MEP (according to the corresponding notion page)
> [PC-8993]: Performance improvements on homepage pro : venue stats

- src/pcapi/utils/requests.py
pro testcafe fail since 21ef8b7f19dcd1338765a2395c2c986aef17bc2d
=====
Fix rapide afin que la CI de pro repasse au vert.
Source de l'erreur: 
https://github.com/pass-culture/pass-culture-api/commit/21ef8b7f19dcd1338765a2395c2c986aef17bc2d
> [PC-9858] fix pro testcafe

- src/pcapi/utils/date.py
- tests/emails/beneficiary_booking_confirmation_test.py
- tests/utils/date_test.py
Lorsqu'un utilisateur sans département essaie de réserver une offre numérique, on a une erreur lors de la construction de l'email de confirmation de réservation.
Le code cherche à s'assurer que le département est bien de type `str`, ce qui est inutile puisqu'une clé de dict peut être d'un autre type. La clé peut même être `None `puisque `None` est _hashable_.
> (PC-6977) [FIX] booking confirmation email: missing departement code

- src/pcapi/scripts/payment/batch.py
- src/pcapi/scripts/payment/batch_steps.py
- tests/scripts/payment/batch_steps_test.py
If we fail too soon in the payment generation function, there is no
point in catching the exception and continuing. We will have to fix
the problems and re-execute the function. So let's not catch
exceptions and let them raise to stop the execution of the code.
Also, do not change the payment status of all payments to
`NOT_PROCESSABLE` when the generated XML is invalid. We would either
have to run the full command again (including the call to
`generate_payments()` that is very long, to mark those payments as
`PENDING` again), or rollback those status changes to manually execute
`generate_and_send_payments()` with the latest batch date. Now the
payment statuses stay the same, and we can simply do the latter
without having to touch the payment statuses.
> (PC-9939) payments: Remove dubious error handling in payment generation script

- tests/utils/db_test.py
The flaky test in action : https://app.circleci.com/pipelines/github/pass-culture/pass-culture-api/8677/workflows/e0170743-99cb-486f-b48c-7cae143a4164/jobs/20271
> Fix flaky test in db_test : comparison of an unordered list of Users

- src/pcapi/connectors/beneficiaries/jouve_backend.py
- src/pcapi/core/fraud/api.py
- src/pcapi/domain/beneficiary_pre_subscription/beneficiary_pre_subscription_validator.py
- tests/connectors/beneficiaries/beneficiary_jouve_repository_test.py
- tests/core/fraud/test_api.py
- tests/domain/beneficiary/beneficiary_pre_subscription_validator_test.py
- tests/domain_creators/generic_creators.py
- tests/routes/webapp/post_id_check_application_update_test.py
- tests/use_cases/create_beneficiary_from_application_test.py
Deux tickets:
- PC-9937 : Le dossier est suspicieux en fonction de retours  de jouve en erreur de lecture de la pièce d'identité
- PC-9862 : ne pas rejeter les dossiers ID check si le champs N° de CNI est une chaine vide
> PC-9862 : Checks Jouve ID number before rejecting the subscription

- src/pcapi/scripts/payment/update_custom_reimbursements.py
Errors are blocking. Warnings are, well, just warnings, and should not
avoid the creation of rules.
> payments: Warnings must not be blocking in `update_custom_reimbursements()`

- src/pcapi/admin/custom_views/category_view.py
- src/pcapi/admin/install.py
- src/pcapi/core/categories/subcategories.py
- src/pcapi/templates/admin/categories_list.html
- src/pcapi/templates/admin/offer_categories_list.html
- src/pcapi/templates/admin/offer_subcategories_list.html
- src/pcapi/templates/admin/subcategories_list.html
- tests/admin/custom_views/category_view_test.py
Ajout des vues FA permettant d'afficher les attributs des `Categories` et `Subcategories`.
- Ajout de 2 vues
- Ajout de 2 templates
> (PC-9770) add view for categories

- src/pcapi/admin/base_configuration.py
- src/pcapi/admin/custom_views/fraud_view.py
- src/pcapi/core/fraud/api.py
- src/pcapi/core/fraud/factories.py
- src/pcapi/core/users/models.py
- src/pcapi/templates/admin/fraud_details.html
- tests/admin/base_configuration_test.py
- tests/admin/custom_views/fraud_view_test.py
- tests/core/fraud/test_api.py
- tests/core/fraud/test_factories.py
Renommage de la branche https://github.com/pass-culture/pass-culture-api/pull/2806 qui ne respectait pas le bon nom de ticket, mon mauvais.
But : permettre de modifier le n° de carte d'identité d'un utilisateur dont le profil est flaggué comme potentiellement frauduleux,
et relancer la machine (de verification de fraude).
Ces interfaces doivent être accessibles par les operationnels ayant pour role "JOUVE" qui ne doivent accéder qu'a ces interfaces spécifiques.
> PC-9905 : Allows to update the user's ID numbers

- src/pcapi/core/users/api.py
- src/pcapi/routes/native/v1/account.py
- src/pcapi/routes/native/v1/serialization/account.py
- tests/routes/native/v1/account_test.py
the update of this field had been forgotten. Do not update user phone number if it is already present on user, which will be the case when PhoneValidation will be activated
> (PC-9965) Update user phone number on beneficiary_information route

- src/pcapi/connectors/api_adage.py
- src/pcapi/routes/native/v1/account.py
- tests/connectors/api_adage_test.py
Avoid JSONDecodeError('Expecting value: line 1 column 1 (char 0)')
cf this error on sentry https://sentry.internal-passculture.app/organizations/sentry/issues/42981/?environment=testing&project=5&query=is%3Aunresolved
> (PC-9388) Fix log message on adage 503 error

- src/pcapi/alembic/versions/20210712_f151ee109bd4_add_on_delete_cascade_to_offer_report_.py
- src/pcapi/core/offers/api.py
- src/pcapi/core/offers/models.py
- src/pcapi/domain/offer_report_emails.py
- src/pcapi/emails/offer_report.py
- src/pcapi/routes/native/v1/offers.py
- tests/routes/native/v1/offers_test.py
**But**
1. ajouter la raison du signalement précisée par l'utilisateur si la raison est _OTHER_. (note : le code qui génère le contenu de l'email ne vérifie pas que `reason == "OTHER"` puisque cette vérification est censée être faite en amont).
2. ajouter un lien vers la page PRO de l'offre.
**Au passage**
1. Corriger un oubli de contraintes sur la table `offer_report`.
➡️ ajouter un `on delete cascade` sur `offerId`
➡️ ajouter un `on delete cascade` sur `userId`
2. Corriger les informations de l'API pour la route `GET /offers/reports`
> (PC-9478)[FIX] enrich email sent to support

- src/pcapi/connectors/beneficiaries/jouve_backend.py
- src/pcapi/core/fraud/api.py
- tests/connectors/beneficiaries/beneficiary_jouve_repository_test.py
- tests/core/fraud/test_api.py
The fields BodyFirstNameCtrl, BodyFirstNamelvl, InitialSizeCtrl, InitialNumberlvl, CreatorCtrl are not used in fraud check validation
> (PC-9979): Remove unused jouve fraud fields

- src/pcapi/connectors/beneficiaries/jouve_backend.py
- src/pcapi/core/fraud/api.py
- src/pcapi/domain/beneficiary_pre_subscription/beneficiary_pre_subscription.py
- src/pcapi/domain/beneficiary_pre_subscription/beneficiary_pre_subscription_validator.py
- src/pcapi/use_cases/create_beneficiary_from_application.py
- src/pcapi/workers/beneficiary_job.py
- tests/use_cases/create_beneficiary_from_application_test.py
- tests/workers/beneficiary_job_test.py
For a good amount of uploaded identity cards, Jouve sends a wrong value for idPieceNumber field, for example ''. Some files have been manually checked by admins and must be reimported by bypassing the check
> (PC-9977) Add a beneficiary_import mode to bypass idPieceNumber duplicate check

- src/pcapi/core/fraud/models.py
- tests/connectors/user_profiling_fixtures.py
- tests/connectors/user_profiling_test.py
Objectif: corriger un probleme sur le retour de la réponse de l'user_profiling : lorsque la requete est valide, la reponse ne contient pas le champs known_session
> (PC-9987): UserProfiling might response with known session

- src/pcapi/core/users/api.py
- tests/core/users/test_api.py
Objectif: ne pas remplir les données utilisateurs lorsque jouve retourne des données vides
> (PC-9981): Only fill user info from jouve if defined

- src/pcapi/core/bookings/api.py
- src/pcapi/notifications/push/user_attributes_updates.py
- src/pcapi/scripts/batch_update_users_attributes.py
- src/pcapi/workers/push_notification_job.py
- tests/admin/custom_views/beneficiary_user_view_test.py
- tests/core/bookings/test_api.py
- tests/notifications/push/backends_test.py
- tests/notifications/push/user_attributes_updates_test.py
- tests/routes/native/v1/account_test.py
- tests/routes/webapp/post_id_check_application_update_test.py
- tests/scripts/beneficiary/remote_import_test.py
- tests/use_cases/create_beneficiary_from_application_test.py
This PR fixes three problems : 
- attribute parameters size cannot exceed 30 caracters, cf this error in sentry : https://sentry.internal-passculture.app/organizations/sentry/issues/11115/?environment=testing&project=5&query=is%3Aunresolved
- when a pro uses a booking, the update was not triggered
- flaky test in batch attribute update
We take advantage of the second point to improve the code by merging "user attributes" and "user booking attributes" update, for better maintenability. For example, there was another mistake : there was no update of "user booking attributes" on booking cancellation, only an update of "user attributes".
We also remove a wise number of test assertions on batch payload content, which are useless if we test well the function that builds the payload.
> (PC-9959) Fix batch attribute update

- src/pcapi/local_providers/allocine/allocine_stocks.py
- tests/local_providers/allocine_stocks_functions_test.py
- tests/local_providers/allocine_stocks_test.py
Collecter plus d'information sur les films synchronisés via Allociné.
Copie de plus de clés/valeurs dans le JSON reçu
Mise à jour du dictionnaire exemple d'information de film dans `tests/local_providers/allocine_stocks_functions_test.py`
> (PC-3174) local_providers: collect more info on movies

- .circleci/config.yml
- src/pcapi/scripts/batch_update_offer_withdrawal_details_for_offerer.py
Raccourcir la durée d'exécution de la CI du dépôt `api`
Définir 3 jobs parallèles de tests au lien d'un seul:
- Le parallélisme est effectué manuellement en définissant des jobs pour tests/core, tests/routes, et le reste. 
- L'utilisation de `pytest-xdist` ou de `circleci tests split` ne s'est pas avérée concluante, et les temps d'exécution du _step_ `Running tests` sont assez homogènes (un peu plus d'une minute) contre environ 3 minutes auparavant.
Au passage, on a corrigé 2 erreurs de syntaxe, et on affiche les 10 tests les plus lents de chaque job, et on n'affiche plus la barre de progression de `pip`.
> (PC-10027) circleci: improve configuration

- .circleci/config.yml
Afin d'accélérer le job `quality` de la CI, augmenter à 8 l'option `--jobs` de Pylint.
> (PC-10027) speed up pylint job

- src/pcapi/domain/payments.py
- tests/domain/payments_test.py
Accounting wants the humanized id of the venue, not the raw id.
> (PC-9995) payments: Include humanized venue id in venues CSV file

- src/pcapi/core/fraud/api.py
- src/pcapi/core/fraud/models.py
- src/pcapi/core/users/api.py
- src/pcapi/core/users/exceptions.py
- tests/routes/native/v1/account_test.py
create fraud checks on phone number validation/update errors:
+ phone already exists
+ blacklisted phone number
+ sms sending limit reached
+ phone validation attempts reached
also create a fraud result on two of them:
+ sms sending limit reached
+ phone validation attempts reached
These check and results will be visible from the admin panel and help
track the user errors regarding phone validation.
> (PC-9793) add fraud checks and results on user actions

- src/pcapi/templates/admin/categories_list.html
- src/pcapi/templates/admin/subcategories_list.html
Améliorer l'affichage des templates de listes de catégories et sous-catégories
- figer les en-têtes de tableau lors du déroulement de la page
- rendre les cellules d'en-têtes gris foncé avec caractères blancs 
- surcharger le `z-index` à 0 de la classe `sticky-top` au sein du `body`, pour éviter que les th recouvrent les menus déroulants de la navbar
Before:
After:
> templates: tweak subcategories and categories list templates

- src/pcapi/repository/repository.py
As stated in [PEP 484](https://www.python.org/dev/peps/pep-0484/#arbitrary-argument-lists-and-default-argument-values), arbitrary argument lists can be annotated with the type of the expected arguments, be they one or several.
> repository: edit typing for arbitrary argument lists

- src/pcapi/admin/custom_views/fraud_view.py
- src/pcapi/core/fraud/models.py
- src/pcapi/core/users/models.py
- src/pcapi/templates/admin/fraud_details.html
- tests/admin/custom_views/fraud_view_test.py
Objectif :
- Permettre aux opérateurs de jouve de pouvoir utiliser la fonctionnalité d'ajout de revue
- Ajouter un état à la revue "Renvoi vers DMS" et envoyer un mail à l'utilisateur
> (PC-10109) Allows Jouve users to validate fraud review

- src/pcapi/admin/custom_views/fraud_view.py
- tests/admin/custom_views/fraud_view_test.py
Objectif : la vérification des droits d'accès à la validation des n° de pièce d'identité sur la page de fraude
etait incorrecte.
Il faut donner les droits pour les admins jouve et les admins classiques en staging et super admin en prod
> (PC-10108) Correctly check access to id number validation

- helm/pcapi/values.integration.yaml
- helm/pcapi/values.production.yaml
- helm/pcapi/values.staging.yaml
- helm/pcapi/values.testing.yaml
- requirements.txt
- src/pcapi/connectors/notion.py
- src/pcapi/local_providers/provider_api/provider_api_stocks.py
- src/pcapi/settings.py
A débattre : 
Est ce qu'on ne catcherait pas que le ProviderAPIException, dans lequel on rajouterait des détails sur l'erreur (ISBN par exemple) qu'on pourrait du coup mettre dans le tableau ? Et avoir des erreurs plus précise qu'un champ texte qu'on ne pourra pas traiter automatiquement dans notion ?
Mon avis : commençons comme ça déjà et on voit après
> (MOB): Log to notion when a synchronisation error happen

- src/pcapi/core/categories/conf.py
- src/pcapi/routes/serialization/offers_recap_serialize.py
- src/pcapi/routes/serialization/offers_serialize.py
- tests/core/categories/test_conf.py
Corriger une erreur dans le formulaire d'édition (structure avec lieu obligatoire alors que l'offre est numérique) pour les offres numériques n'ayant pas de `subcategoryId` en DB
- Corriger la correspondance `type` -> `subcategoryId` pour les offres n'ayant pas encore cette dernière, dans le cas où l'offre peut être numérique ou physique.
- Ajouter des tests
Avant:
Après:
> (PC-10158) fix type to subcategory matching

- src/pcapi/core/bookings/exceptions.py
- src/pcapi/scripts/offerer/commands.py
- src/pcapi/scripts/offerer/delete_cascade_venue_by_id.py
- tests/scripts/offerer/delete_cascade_offerer_by_id_test.py
- tests/scripts/offerer/delete_cascade_venue_by_id_test.py
Voila un outils pour répondre au PC-9693
Nous avons actuellement une commande pour tenter d'effacer une structure et tout ces liens, mais la version lieu uniquement est manquante.
* [doc notion](https://www.notion.so/passcultureapp/Suppression-d-une-structure-juridique-et-de-tous-ses-descendants-bf6194a6455f47eebf8a6497acabdf91)
* [commande pour les structures](https://github.com/pass-culture/pass-culture-api/blob/master/src/pcapi/scripts/offerer/delete_cascade_offerer_by_id.py)
A l'image de la commande offerer, voila l'utilisation:
```shell
pc -e ENVIRONMENT bash
python src/pcapi/scripts/pc.py delete_venue --id <id_du_lieu>
pc -e staging -bash
python src/pcapi/scripts/pc.py delete_venue --id 1
``` 
Note post merge: pensez à mettre à jours la documentation dans notion.
> [PC-9693] add script to delete a venue

- .circleci/config.yml
It should be more stable and faster to spin up
https://circleci.com/docs/2.0/circleci-images/#next-generation-convenience-images
> circleci: use CircleCi's next gen convenience Python image

- src/pcapi/routes/native/v1/serialization/offerers.py
Venue.postalCode can be None, the pydantic model should have the same rule.
> (PC-10032)[FIX] pydantic: make postalCode optional

- src/pcapi/admin/custom_views/beneficiary_user_view.py
- src/pcapi/admin/custom_views/mixins/resend_validation_email_mixin.py
- src/pcapi/admin/custom_views/partner_user_view.py
- src/pcapi/templates/admin/resend_validation_email.html
- tests/admin/custom_views/beneficiary_user_view_test.py
- tests/admin/custom_views/partner_user_view_test.py
Ajouter la possibilité de ré-envoyer un nouveau lien de validation d'email sur FA, pour autonomiser l'équipe support sur cette tâche.
> (PC-9832): Resend validation email from FA

- src/pcapi/admin/custom_views/offerer_view.py
- src/pcapi/admin/custom_views/venue_view.py
- src/pcapi/scripts/offerer/delete_cascade_offerer_by_id.py
- src/pcapi/scripts/offerer/delete_cascade_venue_by_id.py
Je ne sais pas si on veux que le support puisse effacer aussi simplement un lieu ou une structure.
Ceci dis, il y à beaucoup de ticket en ce sens coté sherif.
J'ai un soucie de redirection sur cette PR que je ne sais pas comment fixé, suite à une erreur je suis redirigé vers `localhost, localhost/{suite de l'url}`, au lieu de simplement `localhost/{suite de l'url}`
> [PC-9693] Add delete offerer and venue to FA

- src/pcapi/core/fraud/api.py
- src/pcapi/core/fraud/models.py
- src/pcapi/core/users/api.py
- tests/core/users/test_api.py
Objectif : logger les erreurs possibles de la validation des documents dans un fraud_check
afin que le support ait l'information
> (PC-10129): Log Document error in fraudcheck

- src/pcapi/admin/custom_views/booking_view.py
- src/pcapi/core/bookings/api.py
- src/pcapi/core/bookings/exceptions.py
- src/pcapi/templates/admin/booking.html
- tests/admin/custom_views/booking_view_test.py
**Besoin**
Ajouter un bouton qui permet d'annuler une réservation, sur _FlaskAdmin_.
L'annulation doit déclencher l'envoi d'un email au responsable de la structure dont dépend l'offre.
**Au passage**
Correction d'un bug sur _FlaskAdmin_ : si une offre est annulée, le _template_ s'attend à ce qu'une date d'annulation existe, ce qui n'a pas l'air d'être tout le temps le cas.
> Pc 9727 fa add cancel booking button

- src/pcapi/admin/custom_views/offer_view.py
- tests/admin/custom_views/offer_view_test.py
Ne pas afficher les offres de structures non validées dans la page Validation de FA
- éditer get_query() de ValidationView
- éditer get_count_query() de ValidationView
> (PC-9452) admin: filter out offers from non validated offerers

- helm/pcapi/values.testing.yaml
Pour tester il faut faire en sorte que l'api soit indisponible, on peut la rendre indisponible paramétrant le rpm à 2 et en faisant de nombreux appels successifs à l'api. 
On rajoute cette annotation `nginx.ingress.kubernetes.io/limit-rpm: "2`" puis on lance cette commande pour que l'api soit indisponible` for i in $(seq 100); do curl https://backend.passculture-testing.beta.gouv.fr/health/api; done  `
Les pages https://pro.passculture-testing.beta.gouv.fr et https://pro.testing.passculture.team doivent la page de maintenance. 
Il faut bien enlever l'annotation nginx.ingress.kubernetes.io/limit-rpm: "2" après le test
> Pc 10125 nginx enable cors for maintenance page

- src/pcapi/admin/base_configuration.py
- src/pcapi/admin/custom_views/fraud_view.py
- src/pcapi/admin/custom_views/offer_view.py
Since the admin mixin update the column_formatters dict, we need
to make sure they are unique for each view.
The default is a BaseAdmin's dict which means formatters are
commun for most admin view which may lead to issues when one
formatter is specific to a single view.
In order to avoid dealing with those nasty side effects, ensure
any admin view has an isolated column_formatters dict.
> (PC-10302) : Fix admin's column_formatters to avoid later conflicts

- alembic_version_conflict_detection.txt
- src/pcapi/alembic/versions/20210805_ffce4944b6b7_add_venue_type_code.py
- src/pcapi/core/offerers/models.py
- src/pcapi/core/offers/factories.py
- src/pcapi/routes/native/v1/serialization/offerers.py
- src/pcapi/scripts/update_venue_type_codes.py
- tests/routes/native/v1/offerers_test.py
- tests/routes/webapp/get_booking_by_id_test.py
- tests/scripts/update_venue_type_codes_test.py
**Besoin**
Disposer d'une clé stable (enum) pour le type d'un lieu et renvoyer cette information dans `GET /venue/<venue_id>`
**Contexte**
La table venue_type n'est pas utilisable puisqu'elle ne contient qu'un label qu'on ne peut donc pas utiliser comme code pour le type d'un lieu.
Le problème est qu'aujourd'hui le front a besoin d'un code pour effectuer le mapping (code -> icône/image par défaut/etc), alors que le code existant fait une sorte de mapping côté back. Il faudrait uniformiser et clarifier l'utilisation de VenueType. En attendant, cette PR propose une étape intermédiaire qui permet de centraliser les informations, notamment les types de lieux existants et valides.
1. ajout d'un colonne venueTypeCode (enum mais juste du texte pour PG) ;
2. ajout de cette …
> (PC-10199) add venueTypeCode to Venue

- helm/pcapi/values.production.yaml
- helm/pcapi/values.staging.yaml
- helm/pcapi/values.testing.yaml
- src/pcapi/domain/offer_report_emails.py
- src/pcapi/settings.py
- tests/routes/native/v1/offers_test.py
**Besoin**
Modifier l'adresse email de destination pour le signalement d'une offre.
> (PC-FIX) report offer: change email dst

- src/pcapi/core/users/api.py
- src/pcapi/scripts/beneficiary/import_users.py
**Besoin**
Ne pas mettre à jour les informations, côté Sendinblue, des utilisateurs créés en staging via import_users : on n'en a pas besoin et ça nous cause quelques soucis.
> (PC-fix) import_users: do not updated SIB user

- src/pcapi/core/offers/factories.py
- start-api-when-database-is-ready.sh
- tests/routes/native/v1/offers_test.py
Corriger les erreurs lors de l'exécution des tests e2e pro
- accepter les messages lors de `apt update`
- utiliser commit() au lieu de flush() dans les _post-generation hooks_ des _factories_ d'offres et produits.
> fix e2e tests

- src/pcapi/scripts/bulk_update_old_offers_with_new_subcategories.py
- tests/scripts/bulk_update_old_offers_with_new_subcategories_test.py
Optimiser le script de rattrapage (plusieurs dizaines de millions d'offres)
- utiliser [`bulk_update_mappings()` ](https://docs.sqlalchemy.org/en/14/orm/session_api.html#sqlalchemy.orm.Session.bulk_update_mappings)au lieu de `repository.save()`:
>   The bulk update feature allows plain Python dictionaries to be used as the source of simple UPDATE operations which can be more easily grouped together into higher performing “executemany” operations. Using dictionaries, there is no “history” or session state management features in use, reducing latency when updating large numbers of simple rows.
- afficher des informations d'avancement pendant l'exécution du script
- utiliser `OfferFactory` dans le test
> (PC-8285): scripts: edit bulk update of missing subcategoryIds

- src/pcapi/routes/adage/v1/serialization/educational_institution.py
- src/pcapi/routes/adage/v1/serialization/prebooking.py
- src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_educational_bookings.py
- tests/routes/adage/v1/confirm_prebooking_test.py
- tests/routes/adage/v1/get_educational_institution_test.py
- tests/routes/adage/v1/mark_prebookings_as_used_test.py
- tests/routes/adage/v1/refuse_prebookings_as_used_test.py
This PR aims to fix 2 small problems that our adage partner is facing:
- We need to set all bookings to pending so that it is easier for their tester to do many operations each week
- Better offers naming
- Datetimes must finish with a Z for their JS datetime lib to work correctly
> (BSR) Fix adage small problems

- alembic_version_conflict_detection.txt
- src/pcapi/alembic/versions/20210803_2ed5959876f1_create_venue_contact.py
- src/pcapi/core/offerers/api.py
- src/pcapi/core/offerers/factories.py
- src/pcapi/core/offerers/models.py
- src/pcapi/core/offers/factories.py
- src/pcapi/core/users/api.py
- src/pcapi/core/users/utils.py
- src/pcapi/routes/pro/venues.py
- src/pcapi/routes/serialization/venues_serialize.py
- src/pcapi/utils/phone_number.py
- tests/core/offerers/test_api.py
- tests/routes/pro/get_venue_test.py
- tests/routes/pro/patch_venue_test.py
- tests/utils/phone_number_test.py
**Besoin**
Côté PRO, on veut que l'utilisateur ait la possibilité de renseigner des informations de contact d'un lieu : email, site web, numéro de téléphone et réseaux sociaux.
Seule l'adresse email est obligatoire.
1. Création d'une table venue_contact qui contient ces informations.
2. Mise à jour de `PATCH /venues/<id>` qui va créer ou mettre à jour (écraser) les informations de contact d'un lieu.
**Note**
La partie validation du numéro de téléphone qui était dans users.api / users.utils a été déplacée dans un module à part puisque le modèle Pydantic de mise à jour des informations de contact en a besoin : ça évite d'avoir le module de sérialisation des lieux qui importe du code de user.api/utils (pas très logique).
> (PC-10269) add contact to venue

- src/pcapi/routes/native/v1/bookings.py
This is related to the issue https://sentry.internal-passculture.app/organizations/sentry/issues/118348. The bug occured when a booking is used but has not dateUsed, which is not supposed to happen. We have to fix this root cause (in production, there are 1625 bookings used but without dateUsed) but this PR provides a quick fix for this route issue.
> (PC-10481) Fix get /bookings route when an ended booking has no endDate

- src/pcapi/core/offers/utils.py
- src/pcapi/routes/adage/v1/serialization/prebooking.py
- src/pcapi/utils/mailing.py
- src/pcapi/utils/urls.py
- tests/core/offers/test_utils.py
- tests/routes/adage/v1/confirm_prebooking_test.py
- tests/routes/adage/v1/get_educational_institution_test.py
- tests/routes/adage/v1/get_prebookings_test.py
- tests/routes/adage/v1/mark_prebookings_as_used_test.py
- tests/routes/adage/v1/refuse_prebookings_as_used_test.py
- tests/utils/urls_test.py
The new webapp will have the following format for its offers pages : `/offre/:not_humanized_offer_id`, therefore we have to adapt for it.
> (PC-10260) Use new format for webapp offer URL when webapp v2 is enabled

- src/pcapi/tasks/decorator.py
We need to use `json.loads(payload.json())` because payload.dict() does not output a json but a dict where values could be datetime objects which lead to a TypeError(f'Object of type {o.__class__.__name__} ' is not JSON serializable')
> (PC-10444) Fix cloud task payload conversion from pydantic to json

- src/pcapi/routes/native/v1/serialization/offerers.py
- src/pcapi/routes/serialization/venues_serialize.py
- tests/routes/native/v1/offerers_test.py
**Besoin**
Renvoyer les nouvelles informations d'un lieu  :
* description ;
* informations d'accessibilité ;
* informations de contact
**Contexte**
Ces informations ont été ajoutée par ces deux PRs récentes : 
* [(PC-10269) add contact to venue](https://github.com/pass-culture/pass-culture-api/pull/2947)
* [(PC-10404) add description and accessibility to Venue](https://github.com/pass-culture/pass-culture-api/pull/2977)
> (PC-10078) add new venue information to GET /venue/<venue_id>

- src/pcapi/core/providers/api.py
- tests/core/providers/test_api.py
- tests/local_providers/local_provider_test.py
- tests/local_providers/titelive_things_test.py
Enregistrer la `subcategoryId` d'une offre lors de sa création pendant une synchronisation de stocks
- modification de `_build_new_offer()`
- ajout de tests manquants
> (PC-9687) providers: fix Offer creation when syncing stocks

- src/pcapi/scripts/beneficiary/remote_import.py
- tests/scripts/beneficiary/remote_import_test.py
Adds the user's id that has the same piece number as the ongoing
import to give more context to the support.
> (PC-10535) : include the user id which has the same piece number

- src/pcapi/routes/error_handlers/generic_error_handlers.py
- src/pcapi/utils/login_manager.py
- src/pcapi/utils/rate_limiting.py
- src/pcapi/validation/routes/users_authentifications.py
- tests/routes/login_manager_test.py
Exemple [ici](https://sentry.internal-passculture.app/organizations/sentry/issues/126541/) (entre autres)
---
`werkzeug.http.parse_authorization_header()` raises a
UnicodeDecodeError if the login or the password contains characters
that have not been encoded in "utf-8", which we'll happily send to
Sentry, where the password could appear as clear text.
Example (of the previous behaviour):
$ AUTH=`python -c "import base64; print(base64.b64encode('login:é'.encode('latin1')).decode())"`
$ echo $AUTH
bG9naW466Q==
$ curl -H "Authorization: Basic $AUTH" "http://localhost:5000/v2/bookings/token/-"
{
"global": [
"Il semble que nous ayons des problèmes techniques :( On répare ça au plus vite."
]
}
New behaviour:
$ curl -H "Authorization: Basic $AUTH" "http://localhost:5000/v2/bookings/token/-"
API …
> security: Catch badly-encoded basic authentication headers to avoid password leak

- src/pcapi/connectors/api_entreprises.py
- src/pcapi/core/offerers/models.py
- tests/admin/custom_views/offer_view_test.py
- tests/connectors/api_entreprises_test.py
- tests/core/offerers/test_models.py
Permettre d'afficher la page de Validation lorsqu'un lieu à un SIRET factice
- gérer les erreurs lors de l'appel à l'API Entreprises hors environnement PROD
> (PC-10612) api_entreprises: handle errors on non prod

- src/pcapi/core/users/repository.py
- src/pcapi/routes/native/v1/authentication.py
- src/pcapi/routes/shared/passwords.py
- src/pcapi/routes/shared/users.py
- tests/core/users/test_api.py
- tests/routes/native/v1/authentication_test.py
- tests/routes/shared/post_new_password_test.py
Besoin
Unifier la manière d'utiliser les token à usage unique : le marquer comme utilisé dans les cas suivants 
* ré-initialisation du mot de passe ;
* id-check (comportement actuel)
**Note**
Reste la méthode `check_activation_token_exists` et la route `GET /users/token/<token>` : est-ce qu'on veut vraiment la garder, à quoi sert-elle ?
L'activation de l'email sera corrigée plus tard.
> Pc 9952 update token workflow

- src/pcapi/routes/pro/bookings.py
Rate limit was only skipping the HTTP 200 code while rate-limitting.
This means that endpoint returing 204 codes were counted as failed
attempts.
> (PC-10653) : take the correct HTTP code to skip rate-limit

- src/pcapi/core/search/__init__.py
When reindexing a venue, we did not call the right method. For _each_
backend, we enqueued all offers of the reindexed venue on _both_
backends. The queue is a _set_ for App Search, so the bug did not have
any impact there. However, on Algolia, the queue is a _list_: each
offer of a venue was enqueued twice for Algolia.
Spotted by Jérémie.
> search: Fix twice-enqueued offers on Algolia on venue reindex

- src/pcapi/sandboxes/scripts/getters/webapp_09_lost_password.py
correction d'un test e2e cassé à cause du changement de gestion des tokens.
avant, les tokens consommés étaient supprimés. maintenant les tokens consommés sont juste marqués comme utilisés. Il fallait juste en tenir compte lors de la récupération d'un utilisateur avec un token de changement de mot de passe
> test de fix test e2e

- src/pcapi/core/bookings/factories.py
- src/pcapi/routes/serialization/bookings_serialize.py
- src/pcapi/sandboxes/scripts/getters/pro_10_desk.py
- tests/routes/pro/get_booking_by_token_v2_test.py
- Sur la route de validation des contremarques, le front pro fait un premier appel à `GET /bookings/v2/token/<token>` qui permet de relever une éventuelle erreur et de désactiver le bouton de validation + afficher message erreur
- SI aucune erreur : la route renvoie un booking serialisé, avec notamment `booking.user.email` et `booking.user.publicName`
- Pas d'objet `User` dans les bookings eac => correction de la serialisation
> (PC-10419) : update booking serialization method to take into account eac booking specificities regarding the user

- tests/scripts/batch_update_users_attributes_test.py
- UserFactory créait un utilisateur non-bénéficiare par défaut (date de naissance fixe 1/1/2000)
- Elle a été rendue relative à la date d'aujourd'hui
- Un test a échoué car l'utilisateur est desormais eligible
> FIX : user is now eligible when created through UserFactory. Need to update one test

- src/pcapi/core/offers/validation.py
- src/pcapi/utils/requests.py
Users often mistype URLs. In that case, logging an exception means
sending the error to Sentry, but it's useless: we cannot do anything
about it. An INFO message is enough if we ever need to debug.
---
Je ne suis pas tout à fait convaincu par le nom de l'argument, mais je
n'ai pas trouvé aussi concis et explicite. (`log_errors_at_error_level`
serait plus explicite, mais ça serait un peu long, je trouve. :) )
---
Exemples Sentry : 
- https://sentry.internal-passculture.app/organizations/sentry/issues/136135/
- https://sentry.internal-passculture.app/organizations/sentry/issues/126448/
- etc.
> requests: Log as INFO, not ERROR, when a user-provided URL is not available

- src/pcapi/connectors/notion.py
The max length in Notion for this field is 2000 characters.
---
Erreur dans Sentry : https://sentry.internal-passculture.app/organizations/sentry/issues/116517
Un champ est trop long, d'après la réponse de l'API de Notion :
body failed validation: body.properties.Détail.title[0].text.content.length should be ≤ `2000`, instead was `13514`.
Je suis incapable de retrouve dans Notion le template pour,
éventuellement, modifier la longueur maximale du champ. À défaut, je
propose d'envoyer une version tronquée. (Je ne sais pas trop qui
utilise cette page Notion.)
> notion: Truncate synchronization error message to max size

- src/pcapi/core/providers/api.py
- src/pcapi/core/providers/repository.py
- src/pcapi/routes/pro/venue_providers.py
- src/pcapi/utils/human_ids.py
- src/pcapi/validation/routes/users_authorizations.py
- tests/routes/pro/put_venue_provider_test.py
nouveau endpoint: `PUT /venueProviders`:
- attend en requête un [`PostVenueProviderBody`](https://github.com/pass-culture/pass-culture-api/blob/bc52b3d90762c0505c93863a834b48bf8c277a91/src/pcapi/routes/serialization/venue_provider_serialize.py#L13)
- renvoie en réponse un [`VenueProviderResponse`](https://github.com/pass-culture/pass-culture-api/blob/bc52b3d90762c0505c93863a834b48bf8c277a91/src/pcapi/routes/serialization/venue_provider_serialize.py#L36)
(+ pas mal d'avertissements MyPy corrigés)
> [PC-8558] add an endpoint to update allocine venue provider mode

- src/pcapi/scripts/payment/batch_steps.py
A previous commit (2c27ac2d3b6feba4ecb28) introduced a subquery, but I
forgot to use `DISTINCT` (although I am pretty sure that I tested the
query with it). The query plan is very different without it and the
query takes 15 minutes, versus less than 10 seconds with `DISTINCT`.
With `DISTINCT`:
Nested Loop  (cost=540069.28..540077.31 rows=1 width=40) (actual time=3354.615..3557.732 rows=3249 loops=1)
->  Unique  (cost=540068.99..540069.00 rows=1 width=8) (actual time=3354.582..3551.094 rows=3249 loops=1)
->  Sort  (cost=540068.99..540068.99 rows=1 width=8) (actual time=3354.580..3503.019 rows=535060 loops=1)
Sort Key: booking."venueId"
Sort Method: external merge  Disk: 9480kB
->  Gather  (cost=231296.37..540068.98 rows=1 width=8) (actual time=2516.415..3277.991 rows=535060 loops=1) …
> payment: Fix performance issue in get_venues_to_reimburse

- src/pcapi/scheduled_tasks/utils.py
Somehow, either apscheduler or sentry documentation has an issue
with what is expected to be captured leading to a mmissing
exception.
This can be fixed by explicitly building the exc_info when
calling Sentry.
> (PC-10715) : cron exceptions are caught by Sentry

- src/pcapi/domain/offer_report_emails.py
- tests/domain/offer_report_email_test.py
- tests/routes/native/v1/offers_test.py
Reported offer emails are now sent to support if the report is
categorized as "OTHER" otherwise reports are sent to the
offer report dedicated mail.
> (PC-10590) : offer reported as type OTHER are emailed to support

- src/pcapi/core/bookings/conf.py
- src/pcapi/core/bookings/models.py
- src/pcapi/core/bookings/repository.py
- tests/core/bookings/test_repository.py
- tests/scripts/booking/handle_expired_bookings_test.py
**Objectif :** Réduction du délai de retrait pour les livres (subcategory:`LIVRE_PAPIER`) à 10 jours, et envoi de notification à J-5.
** Implémentation :**
-  Ajout du cas des livres à la requête `find_expiring_bookings` avec le nouveau délai d'annulation automatique.
- Ajout du cas des livres à la requête `find_soon_to_be_expiring_booking_ordered_by_user` avec le nouveau délai d'envoi de notification.
- ajout de `ACTIVATION_NEW_BOOKING_AUTO_EXPIRY_DELAY_DATE` pour empêcher la rétroactivité sur les réservation faite avant le passage au nouveau délai de retrait.
- Modification des tests.
- Ajout des commentaires pour le nettoyage 20 jours après l'activation du nouveau délai de retrait.
> (PC-10382): Add new auto expiry delay books bookings

- src/pcapi/routes/pro/venue_providers.py
- tests/routes/pro/post_venue_provider_test.py
Ajout de l'attribut `quantity` à la création de venue provider oublié lors d'une précédente refacto.
> (PC-8558): Fix create venue provider quantity bug

- src/pcapi/routes/pro/blueprints.py
- On est passé récemment du blueprint `public_api` à `pro_api_v2` sans configurer les CORS
- `pro_api_v2` doit être public
> FIX : CORS on api_pro_v2 blueprint

- Dockerfile.gcp
lsb-release is not included in Bullseye
> Dockerfile: fix build

- .circleci/config.yml
Invalider le cache du venv de CircleCI en cas de changement de version de Python 
- ajout d'un hash de la version de Python utilisée
Inspiré de https://github.com/CircleCI-Public/python-orb/commit/b757a4f5d1b6a6df168b1f815774fe3d7ece48e0
Tests:
1. créer une branche à partir de 5a64879433feeae4dfa16bf54ed64629a8871cb1 (python 3.9.4)
-> succès
2. rebaser sur master 39a1dc930566af45a1f166f8455981c30207f51a (python 3.9.7)
-> échec `Error: [Errno 2] No such file or directory: '/home/circleci/pass-culture-api-ci/venv/bin/python3'`
3. butiner le commit de cette PR
-> succès
On retrouvera ici ces essais: https://app.circleci.com/pipelines/github/pass-culture/pass-culture-api?branch=fseguin%2Ftest-new-cache
> (PC-10773) circleci: add pyenv version prefix to venv cache

- src/pcapi/core/bookings/repository.py
- src/pcapi/repository/payment_queries.py
- src/pcapi/routes/pro/bookings.py
- src/pcapi/scripts/booking/cancel_old_unused_bookings_for_venue.py
- tests/routes/pro/get_all_bookings_test.py
- tests/routes/pro/get_booking_by_token_v2_test.py
- tests/routes/pro/patch_booking_by_token_test.py
- tests/routes/pro/patch_booking_keep_by_token_test.py
- tests/routes/pro/patch_booking_use_by_token_test.py
- tests/routes/pro/patch_cancel_booking_by_token_test.py
- tests/routes/serialization/reimbursement_csv_test.py
**Commits à relire séparément.**
À la base, je voulais "juste" utiliser `Booking.venueId` et `Booking.offererId`... mais certains tests échouaient car ils utilisent `pcapi.model_creators.generic_creators.create_booking()`. Je les ai mis à jour pour utiliser `BookingFactory`.
Si j'ai le courage vendredi prochain, je supprimerai les autres usages de ce `create_booking()` dans les tests. Mais ce sera dans une autre pull request. À chaque PR suffit sa peine ! :)
> (PC-9991) Use new Booking.venueId and Booking.offererId attributes in SQL queries

- src/pcapi/core/bookings/models.py
Bug : appeler .is_active() pour vérifier qu'un FF est actif.
EDIT : problème identifié par @victorenaud
> (PC-fix) Fix: .is_active() to check if FF is active

- requirements.txt
- src/pcapi/flask_app.py
- src/pcapi/routes/external/__init__.py
- src/pcapi/routes/external/unsubscribe_users.py
- tests/routes/external/unsubscribe_user_test.py
Ajout d'une route pour que le webhook de sendinblue puisse mettre à jour les données en base chez nous
- Ajouts de la route
- Authentification par whitelist 
​
- Le workflow est ici: https://automation.sendinblue.com/scenarios/2
- Doc Sendinblue pour la whitelist: https://developers.sendinblue.com/docs/how-to-use-webhooks#securing-your-webhooks
​
> [PC-10713] When a user is unsubscribed in Sendinblue, it is synchronized in the database

- .circleci/config.yml
Corriger la configuration CircleCI de génération de cache dans les jobs de tests/quality
- Ajout d'un hash de la version de python utilisée
- Factorisation dans un `parameter` pour éviter de futurs oublis
​
Informations supplémentaires
- On peut consulter les [pipelines](https://app.circleci.com/pipelines/github/pass-culture/pass-culture-api?branch=PC-10773-fix-circleci-cache-generation) de cette branche pour vérifier le bon fonctionnement de ce changement:
- Le cache est généré dans ce [job](https://app.circleci.com/pipelines/github/pass-culture/pass-culture-api/10783/workflows/1ad7b319-c0c0-4cb3-9d70-01b725b9dcb8/jobs/29458/parallel-runs/0/steps/0-104)
- Le cache est restauré dans les jobs suivants, par exemple [celui-ci](https://app.circleci.com/pipelines/github/pass-culture/pass-cultur …
> (PC-10773) circleci: fix venv cache generation

- src/pcapi/routes/external/unsubscribe_users.py
Context: Some IPs are missing fromn the whitelist
Sendinblue's doc: https://developers.sendinblue.com/docs/additional-ips-to-be-whitelisted
---
Screenshot from testing with `195.154.31.153` as its IP
> [PC-10713] Whitelist extra IP addresses acording to Sendinblue's documentation for marketing workflows

- src/pcapi/core/bookings/models.py
- tests/core/bookings/test_api.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-10816
Correction d'un bug : présence de réservation avec le statut `USED` mais sans `dateUsed`
Ce bug intervient dans le cas particulier où l'on 'dés-annule' une réservation pour contrer une tentative de fraude.
Initialement nous ne voulions pas écraser la `dateUsed` initiale lors de la dés-annulation, mais celle-ci n'est jamais renseignée. En effet, comme la réservation a été annulée, elle n'a jamais pu être validée.
Fixer la `dateUsed` à `now()` dans la fonction `mark_booking_as_used_with_uncancelling`
Ajout d'une assertion dans le test `mark_as_used_with_uncancelling` de bookings.api
​
N/A
> (PC-10816) FIX : dateUsed was not set when uncancelling and setting as used a booking

- src/pcapi/core/search/backends/base.py
Éviter un import circulaire qui bloque des crons.
Utiliser [typing.TYPE_CHECKING](https://docs.python.org/3/library/typing.html#typing.TYPE_CHECKING) afin de repousser l'import tout en permettant aux outils de _type checking_ de fonctionner.
> (PC-fix) import only when type checking

- src/pcapi/scripts/beneficiary/remote_import.py
- tests/scripts/beneficiary/remote_import_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-10685
Il s'agit d'éviter de repasser sur les dossiers DMS que nous avons déjà traité,
ce qui provoque des envois d'emails non voulus
On réutilise une fonction disponible pour récupérer les bénéficiaires déjà importés.
N/A
> (PC-10685) Ensure to process valid applications once

- src/pcapi/admin/custom_views/support_view.py
- tests/admin/custom_views/support_view_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-10813
Masquer les utilisateurs beneficiaires de la liste affichée aux opérateurs jouves dans l'onglet "Support" dans Flask Admin
La requete d'affichage est modifiée lorsqu'on sait que la personne identifiée sur Flask Admin est un opérateur jouve:
- on filtre les utilisateurs qui n'ont pas de vérification JOUVE
- on filtre les utilisateurs déjà bénéficiaires
N/A.
> (PC-10813): Hide beneficiary in Support View for jouve operator

- src/pcapi/core/users/api.py
- src/pcapi/routes/native/utils.py
- tests/routes/native/v1/account_test.py
The addition of the extra steps indeed causes issues for native
applications that are nonnt able to understand the step and
redirects to the home.
This is an issue if the user uploaded its ID card but didn't
validate the general conditions in which case the user is locked
out of the beneficiary process.
The workaround is to act as usual for older native app and only
return the new extra step for newer versions.
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-10636
Ne pas casser le parcours pour devenir bénéficiaire sur les "vieilles" version de l'application mobile.
N/A
​
N/A
​
> (PC-10636) : add extra step for beneficiary only for newer clients

- src/pcapi/core/bookings/conf.py
- tests/core/bookings/test_models.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-10384
Résolution du problème `can't compare datetime.datetime to datetime.date` pour la property `expirationDate`
- Remplacer `date()` par `datetime()` pour la constante `BOOKS_BOOKINGS_AUTO_EXPIRY_DELAY_START_DATE`
​
N/A
​
> (PC-10384): Fix books bookings auto expiry delay start date bug

- src/pcapi/core/payments/api.py
- tests/core/payments/test_api.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-10866
Résout un problème de timezone qui crédite à 17 ans des jeunes de 18 ans entre minuit et 2h du matin
Fix temporaire
​
> (PC-10866) Temporary fix timezone issue on signup for beneficiaries

- src/pcapi/app.py
- src/pcapi/scheduled_tasks/algolia_clock.py
- src/pcapi/scheduled_tasks/clock.py
- src/pcapi/scheduled_tasks/titelive_clock.py
- src/pcapi/workers/worker.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-10874
Ajout de tags dans Sentry afin de pouvoir filtrer les événements par source (web, cron, worker).
Voir https://docs.sentry.io/platforms/python/enriching-events/tags/
​
N/A
​
> (PC-10874) : add tags to sentry to be able to filter per source

- src/pcapi/routes/error_handlers/generic_error_handlers.py
1. use `request.is_json` to check the request's content type
instead of guessing it from the body
2. catch JSON exception. Might be because the body is malformatted
on purpose.
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-10854
Corriger une exception lorsque le rate limit est atteint avec une requête JSON mal formatée
N/A
​
N/A​
> (PC-10854) : fix rate limit test against json request

- src/pcapi/routes/error_handlers/generic_error_handlers.py
*Contexte:* On souhaite corriger [cette erreur Sentry](https://sentry.internal-passculture.app/organizations/sentry/issues/133192/?environment=production&project=5&query=is%3Aunresolved)
Il apparait qu'une erreur de décodage json raise une exception au niveau de `rate_limit_handler`
Après investigation, on souhaite:
- Dans un premier temps, avoir plus d'info sur le body de la requête qui raise une `JSONDecodeException`, pour comprendre d'où ça vient --> Ajouter un try/catch pour logguer les infos
- Dans un second temps, corriger le comportement et supprimmer le log
Lorque Sentry log la requête , il masque les champs password. On verra cependant toujours le champs 'identifier'.
> Catch JSONDecodeError in ratelimit_handler

- src/pcapi/repository/user_queries.py
- tests/scripts/suspend_suspected_fraudulent_beneficiary_users_test.py
- tests/scripts/suspend_suspected_fraudulent_pro_users_test.py
Effectuer une requête plus stricte lorsqu'il s'agit de retrouver des utilisateurs en fonction des noms de domaine de leurs adresses email. Tel que le LIKE est construit, on risque d'avoir de très mauvaises surprises. Il semble que le but était de gérer les sous-domaines, mais on devrait trouver un moyen de le faire sans prendre de risques.
> (PC-fix) remove dangerous '%' for LIKE query

- src/pcapi/core/fraud/api.py
- src/pcapi/scripts/beneficiary/remote_import.py
- tests/core/fraud/test_api.py
- tests/scripts/beneficiary/remote_import_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-10852
Dans certains cas, l'utilisateur entre un n° de pièce d'identité avec des espaces dans le champs
du formulaire DMS (ca m'est arrivé ..)
De plus, le n° de CNI portugaise est constitué du NIF, d'espaces, e d'un numero aléatoire
Modificiation de la regex, et ajouts de cas de tests
​
N/A
​
> (PC-10852) Support des n° de CNI portugaise, nettoyage des espaces inutiles

- src/pcapi/core/search/backends/appsearch.py
- tests/core/search/test_serialize_appsearch.py
There is no boolean type in App Search, we must send values as
integers.
> search: Fix App Search serialization of disability-related fields of Venue

- tests/routes/external/unsubscribe_user_test.py
Same as 969fa15e0385d180146299fd7501f51722ae5f6a (which has more explanation).
> tests: Remove use of Origin header (again)

- src/pcapi/core/search/backends/testing.py
- src/pcapi/core/search/testing.py
- tests/core/search/test_api.py
- tests/core/search/test_integration.py
J'ai supprimé un mock de Redis au passage, commits à relire séparément.
> App Search (tests) : TestingBackend hérite maintenant de AppSearchBackend

- src/pcapi/core/search/backends/appsearch.py
- src/pcapi/scripts/setup_app_search.py
Use the value of `Offer.rankingWeight` as a boost on App Search.
> (PC-10609) search: Configure "boosts" on App Search

- src/pcapi/emails/offerer_booking_recap.py
- tests/emails/offerer_booking_recap_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-10388
Ajout d'un nouveau template mailjet de confirmation de réservation envoyé aux acteurs culturels avec un paramètre additionnel `expiration_delay` pour gérer le cas du nouveau délai de retrait des livres.
- Ajout de l'id du nouveau template et l'utiliser dans le cas ou le FF `ENABLE_NEW_AUTO_EXPIRY_DELAY_BOOKS_BOOKINGS` est activé.
- Ajout du nouveau paramètre `expiration_delay`.
- Ajout d'une classe de test pour le comportement FF désactivé qui sera supprimé une fois le FF activé.
- Ajout d'une classe de test pour le comportement FF activé.
​
N/A
​
> (PC-10388): offerer booking recap email: adding new mailjet template with additional parameter

- src/pcapi/admin/custom_views/venue_view.py
- src/pcapi/core/offerers/api.py
- src/pcapi/core/search/__init__.py
- tests/core/search/test_api.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-10591
Filtrer les lieux indexés : ne prendre en compte que ceux qui sont permanents.
Je n'ai pas touché à la signature de la méthode pour maintenir une cohérence entre les différentes fonctions `async_xyz` d'indexation : ça aurait été plus simple de passer des `Venue` au lieu de leurs identifiants.
> (PC-10591) index permanent venues only

- src/pcapi/core/users/api.py
- src/pcapi/routes/native/v1/authentication.py
- tests/core/users/test_api.py
- tests/routes/native/v1/authentication_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-10896
The app native frontend calls the `refresh_access_token` route three times d'affilée (which is to be fixed in frontend side). So as an optimization we don't want to update the value too often. Moreover, Sendinblue only keeps the date and not the datetime, so wait at least one day of differnece before updating​
> (PC-10896) Update sendinblue lastVisitDate only after one day

- src/pcapi/routes/adage_iframe/serialization/venues.py
- tests/routes/adage_iframe/get_venue_by_siret_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-9745
L'attribut `public_name` d'un venue est optionnel dans le modèle. Nous voulons quand même renvoyer un Venue au front adage, même si le public_name n'existe pas.
- Rendre le champ publicName optionnel dans le modèle de serialisation `VenueResponse`
​
N/A
​
> (PC-9745) Make venue public_name optional in find_by_siret response

- .circleci/config.yml
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-10985
Ne pas échouer le build nightly quand l'upload à Coveralls échoue
- édition du fichier de conf CircleCI
​
N/A
​
> (PC-10985) circleci: don't fail nightly workflow if coveralls fails

- src/pcapi/domain/beneficiary_pre_subscription/validator.py
- src/pcapi/repository/user_queries.py
- src/pcapi/scripts/beneficiary/remote_import.py
- tests/repository/user_queries_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-10577
Il arrive qu'un utilisateur soit marqué comme dupliqué de lui-même.
Le but de cette PR est donc d'ignorer l'email donné lorsque l'on recherche des utilisateurs en doublons.
> (PC-10577) : exclude the user from duplicate searches

- src/pcapi/core/users/external/batch.py
- src/pcapi/notifications/push/__init__.py
- src/pcapi/notifications/push/backends/batch.py
- src/pcapi/tasks/__init__.py
- src/pcapi/tasks/batch_tasks.py
- src/pcapi/tasks/cloud_task.py
- src/pcapi/tasks/decorator.py
- tests/conftest.py
- tests/notifications/push/backends/batch_test.py
- tests/tasks/batch_tasks_test.py
- tests/tasks/decorator_test.py
Previous behaviour was: api -> CloudTask -> api -> Batch API ;
Now we have: api -> CloudTask -> BatchAPI so that we put less load on our api. 
We need to conserve the '/batch/update_user_attributes' endpoint until the next release so that the queue with former 'internal call' is leased"
Ajout d'une logique "
- enqueue_task_internal -> pour les taches qui passent par notre api, tel que l'upload de piece d'identité jouve
- enque_task -> le point d'entrée pour appeler CloudTask
​
> (PC-10807) Add external cloud task

- .gitignore
- src/pcapi/domain/user_emails.py
- src/pcapi/emails/beneficiary_soon_to_be_expired_bookings.py
- tests/domain/user_emails_test.py
- tests/emails/beneficiary_soon_to_be_expired_bookings_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-10387
Ajout d'un nouveau template mailjet d'avertissement d'expiration de réservation envoyé aux bénéficiaires avec 2 paramètres additionnel _days_before_cancel_ et _days_from_booking_ pour alimenter les variables du template de mail dédié au cas du nouveau délai de retrait des livres et autres réservations.
- Ajout de l'id du nouveau template dans la fonction build_soon_to_be_expired_bookings_recap_email_data_for_beneficiary
- Ajout de 2 nouveaux paramètres  _days_before_cancel_ et _days_from_booking_ dans build_soon_to_be_expired_bookings_recap_email_data_for_beneficiary
- Ajout d'une fonction filter_books_bookings pour séparer les bookings livres et autres bookings
- si FF …
> (PC-10387) send email 5 days before expiration books

- src/pcapi/emails/beneficiary_booking_confirmation.py
- tests/core/bookings/test_api.py
- tests/emails/beneficiary_booking_confirmation_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-10386
Ajout d'un nouveau template mailjet de confirmation de réservation envoyé aux **bénéficiares** avec un paramètre additionnel expiration_delay pour gérer le cas du nouveau délai de retrait des livres.
Ajout de l'id du nouveau template et l'utiliser dans le cas ou le FF ENABLE_NEW_AUTO_EXPIRY_DELAY_BOOKS_BOOKINGS est activé.
Ajout du nouveau paramètre expiration_delay.
Ajout d'une classe de test pour le comportement FF désactivé qui sera supprimé une fois le FF activé.
Ajout d'une classe de test pour le comportement FF activé.
​
N/A
​
> (PC-10386): Confirmation beneficiary email new book expiration delay

- src/pcapi/domain/user_emails.py
- src/pcapi/emails/beneficiary_expired_bookings.py
- tests/domain/user_emails_test.py
- tests/emails/beneficiary_expired_bookings_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-10389
Ajout d'un nouveau template mailjet de notification d'annulation automatique de réservation aux bénéficiaires avec un paramètre additionnel `withdrawal_period` pour gérer le cas du nouveau délai de retrait des livres.
- Ajout de l'id du nouveau template et l'utiliser dans le cas ou le FF ENABLE_NEW_AUTO_EXPIRY_DELAY_BOOKS_BOOKINGS est activé.
- Ajout du nouveau paramètre `withdrawal_period`.
- Ajout d'une classe de test pour le comportement FF désactivé qui sera supprimé une fois le FF activé.
- Ajout d'une classe de test pour le comportement FF activé.​
N/A
​
> (PC-10389): New mailjet template to notify beneficiary when expired bookings

- src/pcapi/domain/user_emails.py
- src/pcapi/emails/offerer_expired_bookings.py
- tests/domain/user_emails_test.py
- tests/emails/offerer_expired_bookings_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-10400
Ajout d'un nouveau template mailjet de notification d'annulation automatique de réservation aux offerers au bout de X jours avec un paramètre additionnel `withdrawal_period` pour gérer le cas du nouveau délai de retrait des livres.
- Ajout de l'id du nouveau template et l'utiliser dans le cas ou le FF ENABLE_NEW_AUTO_EXPIRY_DELAY_BOOKS_BOOKINGS est activé.
- Ajout du nouveau paramètre `withdrawal_period`.
- Ajout d'une classe de test pour le comportement FF désactivé qui sera supprimé une fois le FF activé.
- Ajout d'une classe de test pour le comportement FF activé.
​
N/A
​
> (PC-10400): New mailjet template to notify offerer of expired bookings with variable withdrawal period

- src/pcapi/core/users/api.py
- tests/routes/native/v1/account_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-10991
retarder l'ajout de l'étape `BENEFICIARY_INFORMATION` après la version v1.160 de l'app native.
> (PC-10991) : BENEFICIARY_INFORMATION step is for client > v1.160

- src/pcapi/core/bookings/conf.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11018
Modifier la date du début du nouveau délai de retrait des livres au 1 octobre 2021
Mettre `BOOKS_BOOKINGS_AUTO_EXPIRY_DELAY_START_DATE` au 1/10/2021 
​
N/A
​
> (PC-11018): update books bookings auto expiry delay start date

- src/pcapi/core/categories/subcategories.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11016
Ne plus rendre selectionnable les catégories livestream_musical et livestream_evenement
passer is_selectable à false
​
> (PC-11016): subcategories: don't select livestreams

- .circleci/config.yml
Lancer les tests e2e de pro et webapp lorsque l'on commit sur master, afin de détecter plus rapidement et précisément les effets de bord, sans bloquer le deploy
- modifier la config circleci afin de jouer les 2 jobs de tests e2e
- notifier sur le canal shérif les échecs de ces jobs
TODO avant merge de PR:
> (PC-10994) run e2e tests on commits to master branch

- src/pcapi/routes/native/v1/serialization/offers.py
- tests/routes/native/v1/offers_test.py
Ajout de l'information du homepageLabelName sur la réponse de Subcategory pour pouvoir faire le mapping côté Front.
> (PC-8434): Add homepageLabelName to SubcategoryResponse

- src/pcapi/core/bookings/models.py
- src/pcapi/core/educational/api.py
- tests/core/educational/test_api.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-10851
Permettre l'envoi de mail à la confirmation d'une pré-réservation
- Utilisation de mailjet
​
- Exemples : Réparation des infos envoyées dans le mail de pré-résa
​
> (PC-10851) send mail on educational booking

- .circleci/config.yml
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-10993
Ne pas marquer le job build-container si les requirements ont changé
- Modification de la syntaxe de la config.yml pour CircleCI
​
Bonus: ne plus envoyer de notifications sur les succès de déploiements en testing, et utiliser le template `basic_fail_1` fourni par l'[orb](https://github.com/CircleCI-Public/slack-orb/wiki#templates)
> (PC-10993) don't fail build-container if requirements change

- .circleci/config.yml
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-10993
Corriger la syntaxe de la config.yml de CircleCI
- mieux écrire du bash
​
@dzen m'avait prévenu !
> (PC-10993) circleci: fix multiline syntax

- src/pcapi/core/search/backends/algolia.py
- src/pcapi/core/search/backends/appsearch.py
- tests/core/search/test_serialize_algolia.py
- tests/core/search/test_serialize_appsearch.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-8434
Changement de champs indexés sur Algolia/AppSearch: indexation de l'id de la sous-catégorie au lieu du label.
> (PC-8434) index subcategory id instead of label

- src/pcapi/core/users/api.py
- tests/admin/custom_views/support_view_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11014
Creer un nouveau BeneficiaryImportStatus si il existe deja un BeneficiaryImportStatus pour cet
utilisateur, afin de logguer les changemnts sur le parcours d'inscription en tant que beneficiaire.
Lorsqu'un operateur modifie le N° de CNI Sur F.A. on rencontre un PB avec la contrainte d'unicité
puisqu'on recree un BeneficiaryImport au lieu d'ajouter un nouveau BeneficiaryImportStatus.
N/A.
N/A.
> (PC-11014) Add a new BeneficiaryImportStatus if one already exist

- src/pcapi/core/offerers/api.py
- src/pcapi/core/offerers/models.py
- src/pcapi/core/offers/factories.py
- src/pcapi/routes/native/v1/offerers.py
- src/pcapi/routes/native/v1/serialization/offerers.py
- src/pcapi/scripts/update_venue_type_codes.py
- tests/routes/native/v1/offerers_test.py
- tests/routes/webapp/get_booking_by_id_test.py
- tests/scripts/update_venue_type_codes_test.py
**Contexte**
(fait suite à https://github.com/pass-culture/pass-culture-api/pull/3149 , branche sans ticket)
[Cette PR](https://github.com/pass-culture/pass-culture-api/pull/2956) a ajouté une nouvelle colonne à la table venue : `venueTypeCode`. Elle vise à remplacer `venueTypeId` (et la table `venue_type`).
Pour rappel : avec les nouveautés côté lieux, on avait besoin d'une logique d'enum qui permettait de lister explicitement tous les types de lieux avec des codes stables. Le fonctionnement avec la table `venue_type` (qui ne comportait qu'un label) ne permettait pas cela.
**Besoin**
La précédente PR a ajouté la colonne et un script qui permet de remplir la colonne `venuTypeCode` de tous les lieux en se basant sur le label du `venue_type` associé.
Le but de cette PR est de s'assurer que …
> (PC-10789) venue: set venue type code on create/update

- src/pcapi/routes/native/v1/serialization/offers.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-8434
Utilisation de l'enum pour les clefs de la route /subcategories.
> (PC-8434) change typing of route /subcategories to use enums

- src/pcapi/scripts/beneficiary/remote_import.py
- tests/scripts/beneficiary/fixture.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11082
Corriger les données lues dans la procédure v4 : entre le moment ou nous l'avons implémenté et ou la procédure à été mise en production, les labels sur lesquels nous nous basons ont changés.
Nous pourrions utiliser des ID de champs, mais chaque procédure a ses propres IDs, tout comme les procédures dupliquées pour avoir des versions production, testing, staging des formulaires, ce qui augmente le nombre d'erreurs possibles.
N/A.​
> (PC-11082): Correction de la lectures des champs DMS procédure v4

- src/pcapi/core/offers/factories.py
- src/pcapi/core/offers/models.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11057
Pouvoir créer une offre de sous-categorie "Abonnement plateforme musicale"
- la propriété is_offline_only du model Offer utilise maintenant des sous-catégories
> (PC-11057): model offer: use subcategory in is_offline_only property

- src/pcapi/admin/custom_views/venue_view.py
- src/pcapi/core/offerers/api.py
- src/pcapi/core/search/__init__.py
- tests/admin/custom_views/venue_view_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-10071
Deux problèmes existent : 
1. un lieu n'est pas systématiquement réindexé lors d'une mise à jour (PRO / FA) ;
2. lorsqu'un lieu passe de permanent à non permanent, il n'est pas désindexé.
Cette PR vise à les régler.
> (PC-10071) FIX: always re/un-index venue on update

- src/pcapi/admin/custom_views/beneficiary_user_view.py
- src/pcapi/admin/custom_views/mixins/suspension_mixin.py
- src/pcapi/core/users/api.py
- tests/core/users/test_api.py
Lien vers Jira: https://passculture.atlassian.net/browse/PC-10989
Permettre aux admin de réactiver en masse des comptes utilisateurs (Plutôt que de passer par un ticket shérif)
Ajouter un bouton dans Flask-Admin
​
> (PC-10989) Flask Admin: Add bulk reactivate button for beneficiary users

- src/pcapi/core/bookings/api.py
- src/pcapi/core/bookings/models.py
- src/pcapi/core/offers/api.py
- src/pcapi/domain/user_emails.py
- src/pcapi/emails/offerer_bookings_recap_after_deleting_stock.py
- src/pcapi/emails/user_warning_after_pro_booking_cancellation.py
- tests/admin/custom_views/offer_view_test.py
- tests/core/bookings/test_api.py
- tests/core/offers/test_api.py
- tests/domain/user_emails_test.py
- tests/emails/offerer_bookings_recap_after_deleting_stock_test.py
- tests/emails/user_warning_after_pro_booking_cancellation_test.py
- tests/routes/pro/delete_stock_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-10999
- Envoi d'un email au rédacteur de projet en cas de suppression du stock de la part de l'acteur culturel
- Correction du bug 500 suite à la tentative d'envoi d'une notif batch à l'utilisateur.
- Ajout de propriétés qui permettent de récupérer firstName, lastName et email sur le booking indépendamment du type de réservation (Educational ou Individual)
​
​
> (PC-10999) send cancellation mail for all users

- src/pcapi/admin/custom_views/venue_view.py
- src/pcapi/core/offerers/api.py
- src/pcapi/core/search/__init__.py
- tests/admin/custom_views/venue_view_test.py
- tests/core/search/test_api.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-10071
FIX : lors de l'ajout d'un lieu à la file d'attente d'indexation, on continuait de filtrer et de ne garder que les lieus permanents. Le problème est que ce filtrage a été déplacé au moment de l'indexation afin de désindexer les lieux qui ne sont pas/plus permanents.
Ce qui signifie qu'un lieu qui passe de permanent a non permanent n'était pas ajoute à la file d'attente, et donc pas désindexé.
> (PC-10071) FIX: remove isPermanent filter

- src/pcapi/core/bookings/api.py
- src/pcapi/scheduled_tasks/CONTRIBUTING.md
- src/pcapi/scheduled_tasks/algolia_clock.py
- src/pcapi/scheduled_tasks/clock.py
- src/pcapi/scheduled_tasks/decorators.py
- src/pcapi/scheduled_tasks/titelive_clock.py
- tests/scheduled_tasks/decorators_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-10863
Corriger le problème du cron `update_booking_used` qui ne fonctionne plus depuis 3 mois.
Éviter que le problème se reproduise sur d'autres cron
- Wrap de la méthode appelée au moment d'exécuter les crons pour permettre de remettre la base de données dans un état correct
​
- Correction des logs qui n'affichaient rien en cas d'exception sur le cron pour prévenir de la date d'arrêt
​
> (PC-10863) Fix update_booking_used cron by improving log_cron method

- src/pcapi/models/feature.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11048
Ajout de 2 FF:
- activer/désactiver l'authentification via educonnect sur l'app native
- activer/désactiver l'accès à idcheck pour les utilisateurs de 15 à 17 ans
​
> (PC-11048/11049) add educonnect + id check underage feature toggle

- src/pcapi/routes/serialization/bookings_serialize.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-8443
En tant qu’acteur culturel
J'aimerais qu’au moment de rentrer une contremarque dans l’onglet Guichet, ça soit le prix de réservation qui s’affiche et non pas le prix de l’offre
remplacement du prix - booking.stock.price (prix de l'offre qui peut être mis à jour à n'importe quel moment) par booking.amount (prix enregistré au moment du booking)
​
- [x ] La branche est bien nommée et les commits réfèrent le ticket Jira
- [x ] Branche : pc-XXX-whatever-describe-the-branch
- [x ] PR : (PC-XXX) Description rapide de l' US
- [x ] Commit(s) : [PC-XXX] description rapide du ticket
> (PC-8443):replace offer price by booking price when counter confirm

- src/pcapi/routes/pro/bookings.py
- src/pcapi/routes/serialization/bookings_serialize.py
- src/pcapi/settings.py
The bug fix cd43b26 is efficient, there is no need for an environment variable ready rollback
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-10838
> (PC-10838) Remove easy-removal of spectree on contremarque api

- src/pcapi/routes/native/v1/serialization/account.py
- tests/routes/native/v1/account_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11011
Ajouter un champs dans la requete à /me pour que le front sache afficher à l'utilisateur
des informations complémentaires sur l'état de son parcours de validation de bénéficiaire
Simple ajout d'un champs avec un type complet pour definir le type du message à envoyer à l'utilisateur:
- CTA (lien, message du bouton etc)
- enum pour typer les messages
N/A
> (PC-11011): Add subscriptionMessage field to /me endpoint

- src/pcapi/core/users/api.py
- src/pcapi/tasks/cloud_task.py
- src/pcapi/tasks/decorator.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-10946
Use external CloudTask to update user attributes.
Keep the endpoint currently called by the cloud task until the tasks are leased
> (10946) Update sendinblue contact directly from cloud task

- Dockerfile
xmlsec1 will be used by PySAML2
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-10687
Les dépendances ajoutées proviennent de ces instructions : https://github.com/abarto/flask-pysaml2-example#debianubuntu
> (PC-10687) Add libraries in dockerfile for xmlsec1

- src/pcapi/core/logging.py
- tests/core/logging/tests.py
---
We often forget to transform data that we want to log and leave
Decimal or enum objects, which are not handled by the default JSON
encoder. Let's use a slightly smarter serializer that handles the most
frequent types of objects we log.
> (PC-10979) Utilisation d'un encodeur JSON plus malin pour les logs

- src/pcapi/core/offerers/models.py
- src/pcapi/routes/native/v1/serialization/offerers.py
Faire en sorte que l'enum VenueTypeCode dans openapi.json contienne les codes et non les labels.
Avec quelques petites modifications, on était arrivé à faire en sorte que SQLA et Pydantic gèrent venue.venueTypeCode en utilisant le nom (code) et jamais la valeur (label) de l'enum. Mais ça coince côté spectree lors de la génération du fichier openapi.json : c'est la valeur de l'enum qui est utilisée et je n'ai pas trouvé de moyen de changer ce comportement.
Donc cette PR propose de créer deux enums pour répondre à ce problème. C'est étrange, ce n'est pas idéal (pour ne pas dire pas très élégant), mais... ça fonctionne.
Si quelqu'un a une meilleure idée, je suis preneur.
> (PC-fix) openapi: fix venue type code

- src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_search_objects.py
Fix : récupérer les ids des objets, pas les objets eux-mêmes.
> (PC-fix) fix: get ids, not objects

- src/pcapi/core/educational/api.py
- src/pcapi/core/educational/exceptions.py
- src/pcapi/routes/adage_iframe/bookings.py
- src/pcapi/routes/adage_iframe/serialization/adage_authentication.py
- tests/routes/adage_iframe/get_authenticate_test.py
- tests/routes/adage_iframe/post_educational_booking_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11055
- Rendre les champs autre qu'email optionnel pour l'authentification via jwt
- Rendre ces champs obligatoires pour l'action de préréservation (pas d'autres actions pour le moment)
- Rendre les champs optionnels dans le modèle Pydantic `AuthenticatedInformation`
- Nouveau modèle Pydantic `RedactorInformation` avec les même champs mais obligatoires
- Construction du second modèle à partir du premier dans la route `book_educational_offer`
​
- Utilisation des fixtures pytest pour réduire le code identique à l'initialisation des tests
​
> (PC-11055): make adage jwt fields optional for auth but required for actions

- src/pcapi/core/bookings/conf.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11148
Fixer la date d'expiration du crédit des bénéficiaires 15-17 à la veille de leurs 18 ans.
> (PC-11148) compute underage deposit expiration date

- src/pcapi/workers/synchronize_stocks_job.py
- tests/routes/pro/post_venue_stocks_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-10836
Taguer les offres importées via l'API Stocks en type "offres importées" 
- Ajout d'un nouveau `Provider` pass Culture API Stocks.
- Utiliser ce nouveau provider comme lastProvider pour les offres importées via l'API Stocks.
​
> (PC-10836): save lastProviderId for offers and stocks imported with pc stocks api

- alembic_version_conflict_detection.txt
- src/pcapi/alembic/versions/20211006_418152da3d41_make_some_redactor_fields_optional.py
- src/pcapi/core/educational/models.py
- src/pcapi/routes/adage_iframe/serialization/adage_authentication.py
- tests/routes/adage_iframe/post_educational_booking_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11055
Rendre optionnel certains champs des educational redactor pour permettre à des profils sans info de préréserver des offres EAC
​
> (PC-11055) Make firstName, lastName and civility optional for educational redactors

- alembic_version_conflict_detection.txt
- src/pcapi/alembic/versions/20211007_e788c9f3cd3b_subscriptionmesage_set_nullable_cta_.py
- src/pcapi/core/subscription/models.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11013
Correction suite à relectures : le CTA est optionnel sur certains cas d'interface
Du coup, les champs en base doivent être optionnels
N/A.
N/A.
> (PC-11013) Sets CTA Fields as nullable on SubscriptionMessage

- src/pcapi/admin/custom_views/support_view.py
- src/pcapi/core/subscription/messages.py
- tests/admin/custom_views/support_view_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-10957
Ajout d'un message inapp quand un dossier Jouve est rejeté manuellement
> (PC-10957) : Add inapp message when Jouve's application is rejected

- src/pcapi/core/bookings/factories.py
- src/pcapi/core/bookings/repository.py
- src/pcapi/core/educational/factories.py
- src/pcapi/scripts/booking/handle_expired_bookings.py
- tests/core/bookings/test_repository.py
- tests/scripts/booking/handle_expired_bookings_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-10926
- Adapter le cron handle_expired_bookings aux réservations éducationnelles. Les règles d'expiration sont différentes (cf ticket)
- décomposition en deux fonctions `handle_expired_individual_bookings` et `handle_expired_educaitonal_bookings`
- Factorisation de la partie `update` dans une fonction commune `cancelled_expired_bookings` prenant une query différente en pramètre (en fonction du type de booking)
​
- Creation d'une factory `PendingEducationalBookingFactory`
​
> (PC-10926) : adapt handle_expired_bookings cron to educational bookings

- src/pcapi/scripts/booking/fill_individual_booking_deposit_id.py
- tests/scripts/booking/fill_individual_booking_deposit_id_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11227
Remplir les individualBooking.depositId avec les deposit des utilisateurs. 
Avec l'introduction du pass 15-17, un utilisateur pourra avoir plusieurs deposits. Par exemple un deposit 15-17 expiré et un deposit 18 actif. Pour calculer le crédit restant sur le deposit 18, il faut prendre en compte les réservations faites sur ce deposit, et non sur l'autre.
Cas particuliers : 
- si le booking a été créé après la date d'expiration du booking et que son montant vaut 0€ -> on n'associe pas de depositId
- si le booking a été créé après la date d'expiration du booking et que son montant est > 0€ -> warning! mais il n'y a un seul cas comme ça sur staging (id = 204, créée le 2 sept 2018)
- le cas où l'utilisateur a …
> (PC-11227) Add script to fill individualBooking.depositId

- src/pcapi/scripts/bulk_mark_incompatible_via_isbns.py
- tests/scripts/bulk_mark_incompatible_via_isbns_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11332
Ajouter un script qui passent une liste de ISBN isGcuCompatible: True
- Modification du script existant `bulk_mark_incompatible_via_isbns`
​
​
> (PC-11332): scripts: bulk update products isGCUCompatible

- src/pcapi/admin/custom_views/support_view.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11197
Corriger le filtre qui détermine quelques utilisateurs sont accessibles depuis la page de support aux bénéficiaires (les comptes suspicieux n'étaient pas accessible car ils n'ont pas encore le role bénéficiaire)
- les utilisateurs sont filtrés par exclusion des rôles PRO et ADMIN, plutôt que par filtrage sur le rôle BENEFICIARY
​
(nope)
​
> [PC-11197] perf(backoffice beneficiary support): fix User filter for beneficiary support

- src/pcapi/core/users/api.py
- src/pcapi/routes/saml/educonnect.py
- tests/routes/saml/educonnect_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11545
Fix pour sauvegarder les infos d'un utilisateur après authentification via Educonnect
Commit le changement en BDD avant de rediriger
​​
> (PC-11545) fix: save educonnect user after educonnect login

- src/pcapi/core/fraud/api.py
- src/pcapi/core/fraud/models.py
- src/pcapi/domain/beneficiary_pre_subscription/exceptions.py
- src/pcapi/domain/beneficiary_pre_subscription/validator.py
- src/pcapi/models/feature.py
- src/pcapi/use_cases/create_beneficiary_from_application.py
- tests/core/fraud/test_api.py
- tests/use_cases/create_beneficiary_from_application_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11608
Permettre de mettre en pause le parcours d'inscription jeune pour un traitement plus important.
Ajout d'un type de raison de fraude
> (PC-11608) Add on hold and configurable fraud status

- src/pcapi/routes/saml/educonnect.py
- tests/routes/saml/educonnect_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11585
Ajout de fonctionnalités: 
- Ajout d'un query params `redirect` qui switch la reponse de `302 redirect` à `200` avec un header `educonnect-redirect`
- Ajout d'un query params `redirect` avec valeur par défault à `(bool) True`
​
- Nécessaire pour la version EAC Web, ou nous ouvrirons non pas la page via une redirect mais via JavaScript et un nouvel onglet.
​
> (PC-11585) Added query params redirect=false to /saml/educonnect/login endpoint

- src/pcapi/core/users/models.py
- tests/core/users/test_users_sql_entity.py
- tests/routes/native/v1/account_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11578
Si le FF ENABLE_NATIVE_EAC_INDIVIDUAL est désactivé, la date d'éligibilité d'un utilisateur -18ans est le jour de ses 18ans.
​
> (PC-11578) fix eligibility datetimes

- src/pcapi/models/offer_criterion.py
- tests/admin/custom_views/criteria_view_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-8173
Bug : une exception se produit lorsque l'admin tente de supprimer un tag dans Flask-Admin, si ce tag est associé à une ou plusieurs offres.
Suppression des _backref_ dans les _relationship_ de l'objet Criterion.
En effet ces _backref_ ne sont utilisées nulle part et causent une double requête à la suppression du Criterion : DELETE puis UPDATE sur les mêmes OfferCriterion.
​
Voir détails dans le ticket JIRA :
https://passculture.atlassian.net/browse/PC-8173
Le test ajouté est _Failed_ sans la correction, et _Passed_ après correction.
​
> (PC-8173) Fix tag deletion from Flask-Admin

- src/pcapi/routes/adage_iframe/security.py
Corriger un mauvais format transmis à l'exception dans la fonction décorateur pour le jwt adage
Harmonisation : dans l'exception `InvalidTokenError`, on passe une string car l'exception indique déjà le type d'erreur (authentication / authorization)
​
N/A
​
> BSR : fix data format in exception raised in adage jwt decorator

- src/pcapi/core/offerers/api.py
- src/pcapi/core/users/repository.py
- tests/core/users/test_repository.py
- tests/routes/pro/validate_offerer_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-10808
correction d'un bug qui empêche les bizdevs de valider des rattachements pro
​
​
> (PC-10808) Fix: Offerer validation: fix when user_offerer is activated first

- src/pcapi/core/fraud/api.py
- src/pcapi/core/fraud/factories.py
- src/pcapi/core/fraud/models.py
- src/pcapi/core/users/api.py
- src/pcapi/models/feature.py
- src/pcapi/routes/native/v1/account.py
- tests/core/fraud/test_api.py
- tests/routes/native/v1/account_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-9647
stopper l'inscription des utilisateurs qui sont classés en risque élevé de fraude par Thread-Metrix
- après la validation du numéro de téléphone, si un utilisateur est considéré par Thread-Metrix comme ayant un `risk_rating = high`, l'étape suivante d'inscription renvoyée est `None`
​
- un fraud result est crée/complété dans le cas ou l'utilisateur est profilé avec un risk_rating high ou medium
​
> [PC-9647] feat(fraud): stop beneficiary onboarding for risky profiled users

- .env.development
- .env.testing
- alembic_version_conflict_detection.txt
- helm/pcapi/values.production.yaml
- helm/pcapi/values.staging.yaml
- src/pcapi/admin/autocomplete.py
- src/pcapi/admin/custom_views/custom_reimbursement_rule_view.py
- src/pcapi/admin/fields.py
- src/pcapi/admin/install.py
- src/pcapi/admin/permissions.py
- src/pcapi/admin/widgets.py
- src/pcapi/alembic/versions/20211104T163224_a5f8cf0d75da_payments_add_customreimbursementrule_subcategories.py
- src/pcapi/core/payments/api.py
- src/pcapi/core/payments/exceptions.py
- src/pcapi/core/payments/models.py
- src/pcapi/core/payments/utils.py
- src/pcapi/core/payments/validation.py
- src/pcapi/routes/__init__.py
- src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_event_occurrences.py
- src/pcapi/scripts/payment/update_custom_reimbursements.py
- src/pcapi/settings.py
- src/pcapi/utils/date.py
- tests/admin/autocomplete_test.py
- tests/admin/custom_views/custom_reimbursement_rule_view_test.py
- tests/admin/permissions_test.py
- tests/core/payments/test_api.py
- tests/core/payments/test_models.py
- tests/core/payments/test_validation.py
- tests/domain/reimbursement_test.py
Nouveautés réutilisables :
- un widget d'autocomplétion (malheureusement basé sur l'antique version de select2 inclue dans flask-admin, publiée en 2014) ;
- un widget de date permettant de définir une date minimale et/ou une date maximale ;
- un champ et un widget `<select>` qui permet d'utiliser des `<optgroup>` ;
- et un mécanisme (très simple) de permissions pour flask-admin (cf. détails dans le message de commit correspondant).
Démo de la nouvelle interface : 
https://user-images.githubusercontent.com/471321/140398951-5dd2169d-b077-49a0-9fb7-dfd7e9a62267.mp4
> (PC-9246) Interface de création des règles de remboursement personnalisées

- src/pcapi/notifications/push/backends/batch.py
- tests/routes/native/v1/account_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-7716
Fix : la méthode du contrôleur Batch avait un paramètre en trop (pas besoin de `attribute_values`). Ce qui créait des bugs.
> (PC-7716) fix:notifications rm extra argument

- src/pcapi/admin/custom_views/category_view.py
- src/pcapi/templates/admin/subcategories_list.html
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11524
Placer les colonnes pro & app label en premier dans la liste des sous-catégories, rendre sticky la première colonne
​
> (PC-11524): Make first column stick left and update order

- src/pcapi/core/offerers/repository.py
- tests/routes/pro/get_venues_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11716
The venues route was issuing one query per offerer which kills
the performance on the route. This aims to improve the route's
performance.
By using a joinedload, we ensure the associated offerers are
loaded along with each venue which drop the query count to
a single one.
​
> (PC-11716) : limit the query count on /venues

- src/pcapi/core/subscription/messages.py
- tests/core/users/test_api.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11701
The in-app message for IDCheck's unread-document error possibly
has a race issue that could result in a crash and retry whenever
a user had the unread-document code after it confirmed the
general conditions.
General conditions would flag the user as hasCompletedIdCheck
which would raise an exception when requested a new idcheck
token leading to a post IDCheck crash and endless retries
on IDCheck step.
​
> (PC-11701) : fix in-app message crash for IDCheck's unread-document

- src/pcapi/routes/pro/venues.py
- tests/routes/pro/patch_venue_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-10266
Lorsqu'on édite les valeurs d’accessibilité d'une offre on veux tout le jeu d'information (moteur, visuel, audio, mental) et non pas la ou les valeurs modifiées
> [PC(10266] routes.pro.venues: fix bulk update offers accessibility

- src/pcapi/core/subscription/messages.py
- tests/core/users/test_api.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11701
Turns out it is more complex to fix than it appeared at first.
Long story made short, we don't have an explicit workflow on the
subscription process which is hard to work around to allow
the user a second attempt on IDCheck.
> (PC-11701) : deactivate second attempt on IDCheck

- src/pcapi/sandboxes/scripts/getters/webapp_08_booking.py
- tests/sandboxes/scripts/getters/webapp_08_booking_test.py
Après avoir découvert un test E2E flaky côté webapp (sans doute provoqué par l'arrivée de nouvelles offres EAC dans la sandbox), il a fallu adapter le getter de sandbox utilisé par ce test afin d'améliorer son usage côté front.
> sandboxes: fix getter

- src/pcapi/flask_app.py
Augmenter la taille limite de MAX_STRING_LENGTH côté Sentry pour éviter les troncatures de descriptions
- Patch de MAX_STRING_LENGTH de sentry utils comme décrit ici: https://forum.sentry.io/t/some-stack-traces-are-truncated/7309/2
Avant:
Après:
​
> (MOB) Increase Sentry Max string length to have longer descriptions

- src/pcapi/core/payments/factories.py
- src/pcapi/repository/reimbursement_queries.py
- src/pcapi/routes/serialization/reimbursement_csv_serialize.py
- src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_bookings.py
- src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_educational_bookings.py
- tests/repository/reimbursement_queries_test.py
- tests/routes/serialization/reimbursement_csv_test.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11548
Faire remontée les réservations eac dans le csv des remboursements
Ajout de Outerjoins dans la query qui remonte les paiements, afin de remonter les infos `EducationalBooking`
​
Modification de la sandbox pour que les `IndividualBooking` et les `EducaitonalBooking` créées remontent dans le fichier des remboursements
​
> (PC-11548) : include eac bookings in reimbursement csv for pro

- src/pcapi/sandboxes/scripts/creators/industrial/create_industrial_educational_bookings.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11548
Dans la PR précédente du même ticket, dans la sandbox `create_educational_bookings`, je récupérais un UserOfferer déjà créé en base (le but était d'avoir un user connu pour faciliter la recette par les PO).
Il a été exposé que cette façon de faire dans la sandbox pouvait poser des soucis de synchronisation.
Création d'un UserOfferer spécifique à partir de la factory
​
N/A
​
> (PC-11548) : correct sandbox - create user_offerer instead of fetching existing one

- alembic_version_conflict_detection.txt
- src/pcapi/alembic/versions/20211110T121107_5ff1b52e2f08_change_default_eligibility_type.py
- src/pcapi/models/beneficiary_import.py
Lien vers le ticket Jira : https://passculture.atlassian.net/browse/PC-11204
Fait suite au bug : https://sentry.internal-passculture.app/organizations/sentry/issues/227441/?project=5&referrer=slack
Il faut paramétrer la valeur par défaut sql avec la clé de l'enum plutôt qu'avec la valeur
> (PC-11204) Fix beneficiary_import.eligibilityType default value
